### ISSUE TITLE
activeadmin routes error

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#106]
I am following a video to see about ActiveAdmin . So while following that, suddenly I faced this problem
![ss](https://user-images.githubusercontent.com/19534210/89237248-88246d00-d614-11ea-813d-e552082a5006.png)

why it is saying routes error?
```
School-House git:(master) rails routes
                               Prefix Verb       URI Pattern                                                                              Controller#Action
               new_admin_user_session GET        /admin/login(.:format)                                                                   active_admin/devise/sessions#new
                   admin_user_session POST       /admin/login(.:format)                                                                   active_admin/devise/sessions#create
           destroy_admin_user_session DELETE|GET /admin/logout(.:format)                                                                  active_admin/devise/sessions#destroy
              new_admin_user_password GET        /admin/password/new(.:format)                                                            active_admin/devise/passwords#new
             edit_admin_user_password GET        /admin/password/edit(.:format)                                                           active_admin/devise/passwords#edit
                  admin_user_password PATCH      /admin/password(.:format)                                                                active_admin/devise/passwords#update
                                      PUT        /admin/password(.:format)                                                                active_admin/devise/passwords#update
                                      POST       /admin/password(.:format)                                                                active_admin/devise/passwords#create
                           admin_root GET        /admin(.:format)                                                                         admin/dashboard#index
          batch_action_admin_students POST       /admin/students/batch_action(.:format)                                                   admin/students#batch_action
                       admin_students GET        /admin/students(.:format)                                                                admin/students#index
                                      POST       /admin/students(.:format)                                                                admin/students#create
                    new_admin_student GET        /admin/students/new(.:format)                                                            admin/students#new
                   edit_admin_student GET        /admin/students/:id/edit(.:format)                                                       admin/students#edit
                        admin_student GET        /admin/students/:id(.:format)                                                            admin/students#show
                                      PATCH      /admin/students/:id(.:format)                                                            admin/students#update
                                      PUT        /admin/students/:id(.:format)                                                            admin/students#update
                                      DELETE     /admin/students/:id(.:format)                                                            admin/students#destroy
                      admin_dashboard GET        /admin/dashboard(.:format)                                                               admin/dashboard#index
           batch_action_admin_schools POST       /admin/schools/batch_action(.:format)                                                    admin/schools#batch_action
                        admin_schools GET        /admin/schools(.:format)                                                                 admin/schools#index
                                      POST       /admin/schools(.:format)                                                                 admin/schools#create
                     new_admin_school GET        /admin/schools/new(.:format)                                                             admin/schools#new
                    edit_admin_school GET        /admin/schools/:id/edit(.:format)                                                        admin/schools#edit
                         admin_school GET        /admin/schools/:id(.:format)                                                             admin/schools#show
                                      PATCH      /admin/schools/:id(.:format)                                                             admin/schools#update
                                      PUT        /admin/schools/:id(.:format)                                                             admin/schools#update
                                      DELETE     /admin/schools/:id(.:format)                                                             admin/schools#destroy
       batch_action_admin_admin_users POST       /admin/admin_users/batch_action(.:format)                                                admin/admin_users#batch_action
                    admin_admin_users GET        /admin/admin_users(.:format)                                                             admin/admin_users#index
                                      POST       /admin/admin_users(.:format)                                                             admin/admin_users#create
                 new_admin_admin_user GET        /admin/admin_users/new(.:format)                                                         admin/admin_users#new
                edit_admin_admin_user GET        /admin/admin_users/:id/edit(.:format)                                                    admin/admin_users#edit
                     admin_admin_user GET        /admin/admin_users/:id(.:format)                                                         admin/admin_users#show
                                      PATCH      /admin/admin_users/:id(.:format)                                                         admin/admin_users#update
                                      PUT        /admin/admin_users/:id(.:format)                                                         admin/admin_users#update
                                      DELETE     /admin/admin_users/:id(.:format)                                                         admin/admin_users#destroy
                       admin_comments GET        /admin/comments(.:format)                                                                admin/comments#index
                                      POST       /admin/comments(.:format)                                                                admin/comments#create
                        admin_comment GET        /admin/comments/:id(.:format)                                                            admin/comments#show
                                      DELETE     /admin/comments/:id(.:format)                                                            admin/comments#destroy
        rails_postmark_inbound_emails POST       /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
           rails_relay_inbound_emails POST       /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
        rails_sendgrid_inbound_emails POST       /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
  rails_mandrill_inbound_health_check GET        /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
        rails_mandrill_inbound_emails POST       /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
         rails_mailgun_inbound_emails POST       /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
       rails_conductor_inbound_emails GET        /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
                                      POST       /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
    new_rails_conductor_inbound_email GET        /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
   edit_rails_conductor_inbound_email GET        /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
        rails_conductor_inbound_email GET        /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
                                      PATCH      /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
                                      PUT        /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
                                      DELETE     /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
rails_conductor_inbound_email_reroute POST       /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
                   rails_service_blob GET        /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
            rails_blob_representation GET        /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
                   rails_disk_service GET        /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
            update_rails_disk_service PUT        /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
                 rails_direct_uploads POST       /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
➜  School-House git:(master) ✗ 

```

**Comment by sadmanahmed** [comment]
Server Log
```
Started GET "/admin/login" for ::1 at 2020-08-04 05:38:11 +0600
  
ActionController::RoutingError (No route matches [GET] "/admin/login"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

```

**Comment by wasifhossain** [comment]
did you change `config/routes.rb` to enable the activeadmin routes

**Comment by sadmanahmed** [comment]
Solved by adding this in the development.rb
```
config.file_watcher = ActiveSupport::FileUpdateChecker
  config.reload_classes_only_on_change = false
```
