### ISSUE TITLE
ERROR in the authentication method(authenticated?)

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#11]
```
sample_app git:(account-activation) ✗ rails t
Running via Spring preloader in process 4800
Started with run options --seed 56160

ERROR["test_authenticated?_should_return_false_for_a_user_with_nil_digest", #<Minitest::Reporters::Suite:0x000055dae1b0d148 @name="UserTest">, 2.4201262970018433]
 test_authenticated?_should_return_false_for_a_user_with_nil_digest#UserTest (2.42s)
NoMethodError:         NoMethodError: private method `authenticated?' called for #<User:0x000055dae1b0ee08>
        Did you mean?  authenticate
            test/models/user_test.rb:68:in `block in <class:UserTest>'

  36/36: [==========================================================] 100% Time: 00:00:02, Time: 00:00:02

Finished in 2.67646s
36 tests, 150 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by sadmanahmed** [comment]
test/models/user_test.rb
```
require 'test_helper'

class UserTest < ActiveSupport::TestCase
  def setup
    @user = User.new(name: "Example User", email: "user@example.com" , password:"foobar", password_confirmation:"foobar")
  end

  test "should be valid" do
    assert @user.valid?
  end

  test "name should be present" do
    @user.name= "  "
    assert_not @user.valid?
  end

  test "email should be present" do
    @user.email = " "
    assert_not @user.valid?
  end

  test "name should not be too long" do
    @user.name = "a" * 51
    assert_not @user.valid?
  end

  test "email should not be too long" do
    @user.email = "a" * 244 + "@example.com"
    assert_not @user.valid?
  end

  test "email validation should accept valid addresses" do
    valid_addresses = %w[user@example.com USER@foo.COM A_US-ER@foo.bar.org
                         first.last@foo.jp alice+bob@baz.cn]
    valid_addresses.each do |valid_address|
      @user.email = valid_address
      assert @user.valid?, "#{valid_address.inspect} should be valid"
    end
  end

  test "email validation should reject invalid addresses" do
    invalid_addresses = %w[user@example,com user_at_foo.org user.name@example.
                           foo@bar_baz.com foo@bar+baz.com]
    invalid_addresses.each do |invalid_address|
      @user.email = invalid_address
      assert_not @user.valid?, "#{invalid_address.inspect} should be invalid"
    end
  end


  test "email addresses should be unique" do
    duplicate_user = @user.dup
    @user.save
    assert_not duplicate_user.valid?
  end

  test "password should be present (nonblank)" do
    @user.password = @user.password_confirmation = " " * 6
    assert_not @user.valid?
  end

  test "password should have a minimum length" do
    @user.password = @user.password_confirmation = "a" * 5
    assert_not @user.valid?
  end

  test "authenticated? should return false for a user with nil digest" do
    assert_not @user.authenticated?(:remember, '')
  end



end
```

**Comment by sadmanahmed** [comment]
app/helpers/sessions_helper.rb
```
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
             # The tests still pass, so this branch is currently untested.
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  #Returns true if the given user is the current user
  def current_user?(user)
    user && user == current_user
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent  session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end



  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end


end
```

**Comment by sadmanahmed** [comment]
app/models/user.rb
```
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 },allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest,nil)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end


    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end
```

**Comment by sadmanahmed** [comment]
Error Update: If we remove this portion from the **user_test.rb** then the error is gone 
```
test "authenticated? should return false for a user with nil digest" do
    assert_not @user.authenticated?(:remember, '')
  end
```

**Comment by wasifhossain** [comment]
> Error Update: If we remove this portion from the **user_test.rb** then the error is gone
> 
> ```
> test "authenticated? should return false for a user with nil digest" do
>     assert_not @user.authenticated?(:remember, '')
>   end
> ```

is it suggested to remove the test in order to make the test suite pass? I believe NO!

**Comment by wasifhossain** [comment]
the thing is, in Ruby you can't have 2 copies of a method with parameter overloading, which is available in other languages like Java.

e.g.
```rb
class A
  def test(a)
    puts a
  end

  def test(a, b)
    puts a, b
  end
end
```
here `test` method is defined twice with different parameter signature. Only the later one will be used.
```rb
a = A.new

a.test(10, 20)
# =>
10
20
 => nil

a.test(10)
# => ArgumentError (wrong number of arguments (given 1, expected 2))
```

In `User` model, you have defined 2 copies of the `authenticated?` method:
```rb
def authenticated?(remember_token); end

def authenticated?(attribute, token); end
```
as we discussed earlier, only the later one will be used whenever this method is called.

But i can see there is the `private` modifier placed before the 2nd authenticated? method, and for this reason, the test is failing to call the private method.

quoting your post from running the test log
```sh
NoMethodError:         NoMethodError: private method `authenticated?' called for #<User:0x000055dae1b0ee08>
        Did you mean?  authenticate
            test/models/user_test.rb:68:in `block in <class:UserTest>'
```

I hope you got enough hints to correct your code!

**Comment by sadmanahmed** [comment]
Now it is working fine.
