### ISSUE TITLE
Paperclip Migration error

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#110]
I am following a tutorial and there they use **Paperclip** for upload pictures

I followed this https://github.com/thoughtbot/paperclip and the tutorial to set up but the migration failed

```
 instagramm git:(master) ✗ sudo apt-get install imagemagick -y
[sudo] password for abir:       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
imagemagick is already the newest version (8:6.9.7.4+dfsg-16ubuntu6.8).
The following packages were automatically installed and are no longer required:
  libatomic1:i386 libbsd0:i386 libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386
  libffi6:i386 libgl1:i386 libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libglapi-mesa:i386 libglvnd0:i386 libglx-mesa0:i386 libglx0:i386 libkeybinder-3.0-0 libllvm10:i386
  libllvm9 libllvm9:i386 libpciaccess0:i386 libsensors4:i386 libstdc++6:i386 libx11-6:i386 libx11-xcb1:i386 libxau6:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386
  libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386 libxcb1:i386 libxdamage1:i386 libxdmcp6:i386 libxext6:i386 libxfixes3:i386 libxinerama1:i386
  libxshmfence1:i386 libxxf86vm1:i386 linux-headers-4.15.0-101 linux-headers-4.15.0-101-generic linux-headers-4.15.0-106 linux-headers-4.15.0-106-generic
  linux-headers-4.15.0-108 linux-headers-4.15.0-108-generic linux-headers-4.15.0-109 linux-headers-4.15.0-109-generic linux-headers-4.15.0-88
  linux-headers-4.15.0-88-generic linux-image-4.15.0-101-generic linux-image-4.15.0-106-generic linux-image-4.15.0-108-generic linux-image-4.15.0-109-generic
  linux-image-4.15.0-88-generic linux-modules-4.15.0-101-generic linux-modules-4.15.0-106-generic linux-modules-4.15.0-108-generic linux-modules-4.15.0-109-generic
  linux-modules-4.15.0-88-generic linux-modules-extra-4.15.0-101-generic linux-modules-extra-4.15.0-106-generic linux-modules-extra-4.15.0-108-generic
  linux-modules-extra-4.15.0-109-generic linux-modules-extra-4.15.0-88-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
```

```
rails g paperclip pic image
Running via Spring preloader in process 20700
      create  db/migrate/20200817234333_add_attachment_image_to_pics.rb

```

```
instagramm git:(master) ✗ rails db:migrate           
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddAttachmentImageToPics < ActiveRecord::Migration[4.2]
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:536:in `inherited'
/home/abir/PRACTICE/instagramm/db/migrate/20200817234333_add_attachment_image_to_pics.rb:1:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1010:in `load_migration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1006:in `migration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1002:in `disable_ddl_transaction'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1368:in `use_transaction?'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1360:in `ddl_transaction'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `block in migrate'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `migrate'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1061:in `up'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1036:in `migrate'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/home/abir/PRACTICE/instagramm/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/PRACTICE/instagramm/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddAttachmentImageToPics < ActiveRecord::Migration[4.2]
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:536:in `inherited'
/home/abir/PRACTICE/instagramm/db/migrate/20200817234333_add_attachment_image_to_pics.rb:1:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1010:in `load_migration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1006:in `migration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1002:in `disable_ddl_transaction'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1368:in `use_transaction?'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1360:in `ddl_transaction'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `block in migrate'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `migrate'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1061:in `up'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1036:in `migrate'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/home/abir/PRACTICE/instagramm/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/PRACTICE/instagramm/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

```
instagramm git:(master) ✗ rails db:migrate:status

database: instagramm_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20200815191151  Create pics
   up     20200817200102  Devise create users
   up     20200817201107  Add user id to pics
  down    20200817234333  Add attachment image to pics

```

Migration file
```
class AddAttachmentImageToPics < ActiveRecord::Migration
  def self.up
    change_table :pics do |t|
      t.attachment :image
    end
  end

  def self.down
    remove_attachment :pics, :image
  end
end

```
schema.rb
```

ActiveRecord::Schema.define(version: 2020_08_17_201107) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "pics", force: :cascade do |t|
    t.string "title"
    t.text "description"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "user_id"
    t.index ["user_id"], name: "index_pics_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

end
```

**Comment by wasifhossain** [comment]
to keep up with the practice of using the latest tools and not limiting your knowledge with deprecated tools like Paperclip (https://robots.thoughtbot.com/closing-the-trombone), I would highly recommend to use **Shrine**: https://shrinerb.com/. as a great alternative (even better than ActiveStorage)
