### ISSUE TITLE
rails db:create yarn error

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#124]
```
abir@abir:~/Ruby code/instagramm$ rails db:create
Usage: yarn [options]

yarn: error: no such option: --integrity


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).





abir@abir:~/Ruby code/instagramm$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
abir@abir:~/Ruby code/instagramm$ yarn install --check-files
Usage: yarn [options]

yarn: error: no such option: --check-files

```

**Comment by wasifhossain** [comment]
looks like a **yarn** issue. anyways...

what do you get with each of the following commands:
```
which yarn
yarn -v
echo $0
```

**Comment by sadmanahmed** [comment]
```
abir@abir:~/Ruby code/instagramm$ which yarn
/usr/bin/yarn
abir@abir:~/Ruby code/instagramm$ yarn -v
ERROR: There are no scenarios; must have at least one.
abir@abir:~/Ruby code/instagramm$ echo $0
-bash
abir@abir:~/Ruby code/instagramm$ 

```

**Comment by wasifhossain** [comment]
searching with the error msg from above
> ERROR: There are no scenarios; must have at least one.

got the idea that you might need to reinstall yarn in correct way (ref: https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one)

first get rid of the current version
```
sudo apt purge yarn cmdtest
```
and then follow the instructions from: https://classic.yarnpkg.com/en/docs/install

**Comment by sadmanahmed** [comment]
```
abir@abir:~/Ruby code/instagramm$ which yarn
/usr/bin/yarn
abir@abir:~/Ruby code/instagramm$ yarn -v
1.22.5
abir@abir:~/Ruby code/instagramm$ echo $0
-bash

```

**Comment by wasifhossain** [comment]
now you should be good to resume your work

**Comment by sadmanahmed** [comment]
```
 yarn -v
1.22.5
abir@abir:~/Ruby code/instagramm$ rails db:create
error Couldn't find an integrity file                                    
error Found 1 errors.                                                    


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).


yarn check v1.22.5
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.

```

**Comment by wasifhossain** [comment]
run `yarn install` and retry the command again

**Comment by sadmanahmed** [comment]
I know the solution of this from #98 but the .env is vanishing after creating it
```
rails db:create
fe_sendauth: no password supplied
Couldn't create 'instagramm_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:189:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:126:in `create'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/home/abir/Ruby code/instagramm/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/Ruby code/instagramm/bin/spring:15:in `require'
/home/abir/Ruby code/instagramm/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)

```

**Comment by sadmanahmed** [comment]
Is this my pc issue? the `.env` is hidden
![Screenshot from 2020-10-29 02-30-33](https://user-images.githubusercontent.com/19534210/97493163-c4a30300-198e-11eb-93ea-62955a7cadc5.png)

**Comment by sadmanahmed** [comment]
Okay , enabled the hidden files from setting

**Comment by wasifhossain** [comment]
developers does not rely on OS settings to view hidden files. just run `ls -al` on some directory and it will show all the files and directories inside of it

**Comment by sadmanahmed** [comment]
```
abir@abir:~/Ruby code/instagramm$ echo $PG_USERNAME

abir@abir:~/Ruby code/instagramm$ rails c
FATAL: Listen error: unable to monitor directories for changes.
Visit https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for info on how to fix this.
abir@abir:~/Ruby code/instagramm$ rails db:create
FATAL: Listen error: unable to monitor directories for changes.
Visit https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for info on how to fix this.

```

**Comment by wasifhossain** [comment]
why bother to check the error msg !!
> Visit https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for info on how to fix this.

**Comment by wasifhossain** [comment]
regarding
> echo $PG_USERNAME

different tools have their own ways of loading environment variables in the app process. you have to learn the tool well that you are using on how to test if those are loaded properly. the above command does not guarantee if its loaded or not

**Comment by sadmanahmed** [comment]
is this anything related to postgresql setup? 
```
abir@abir:~/Ruby code/instagramm$ rails db:create
FATAL:  password authentication failed for user "abir"
FATAL:  password authentication failed for user "abir"
Couldn't create 'instagramm_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "abir"
FATAL:  password authentication failed for user "abir"

```

**Comment by wasifhossain** [comment]
i think so

**Comment by wasifhossain** [comment]
check the older issues for similar case to debug the issue

**Comment by sadmanahmed** [comment]
Checked older one's ,but actually the solutions needed  is absent .I guess #125 is good scope to solve that
