### ISSUE TITLE
LoadError: cannot load such file -- shrine/plugins/validation_helper

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#132]
I am trying to add shrine in my blog but this error shows up, tried on net that but didnot find any solution
```
abir@abir:~/Ruby code/blog$ rails db:migrate
rails aborted!
LoadError: cannot load such file -- shrine/plugins/validation_helper
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/shrine-3.3.0/lib/shrine/plugins.rb:15:in `load_plugin'
/home/abir/.rvm/gems/ruby-2.6.5/gems/shrine-3.3.0/lib/shrine.rb:72:in `plugin'
/home/abir/Ruby code/blog/config/initializers/shrine.rb:24:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:666:in `block in load_config_initializer'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:665:in `load_config_initializer'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `block in <class:Engine>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
/home/abir/Ruby code/blog/config/environment.rb:5:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/application.rb:339:in `require_environment!'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/application.rb:523:in `block in run_tasks_blocks'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
/home/abir/Ruby code/blog/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/Ruby code/blog/bin/spring:15:in `require'
/home/abir/Ruby code/blog/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by wasifhossain** [comment]
I guess you might have misspelled the plugin, which should have an `s` at the end
```rb
plugin :validation_helpers
```

check the doc to confirm: https://shrinerb.com/docs/plugins/validation_helpers
