### ISSUE TITLE
Ip block Issue And observe Heroku behaviour

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#134]
```
2020-11-23T17:17:17.436574+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
2020-11-23T17:17:17.436574+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
2020-11-23T17:17:17.436574+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/configuration.rb:228:in `call'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/server.rb:713:in `handle_request'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/server.rb:472:in `process_client'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/server.rb:328:in `block in run'
2020-11-23T17:17:17.436576+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
2020-11-23T17:17:17.438602+00:00 heroku[router]: at=info method=GET path="/users/sign_in" host=finance-tracker-ayub.herokuapp.com request_id=04d55e32-5cdf-4de4-ad39-d2ee9b32855e fwd="103.138.124.192" dyno=web.1 connect=1ms service=10ms status=500 bytes=1827 protocol=https
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2020-11-23T17:17:17.436574+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
2020-11-23T17:17:17.436574+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
2020-11-23T17:17:17.436574+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/configuration.rb:228:in `call'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/server.rb:713:in `handle_request'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/server.rb:472:in `process_client'
2020-11-23T17:17:17.436575+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/server.rb:328:in `block in run'
2020-11-23T17:17:17.436576+00:00 app[web.1]: [04d55e32-5cdf-4de4-ad39-d2ee9b32855e] puma (4.3.6) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
2020-11-23T17:17:17.438602+00:00 heroku[router]: at=info method=GET path="/users/sign_in" host=finance-tracker-ayub.herokuapp.com request_id=04d55e32-5cdf-4de4-ad39-d2ee9b32855e fwd="103.138.124.192" dyno=web.1 connect=1ms service=10ms status=500 bytes=1827 protocol=https
2020-11-23T17:30:22.556726+00:00 app[web.1]: I, [2020-11-23T17:30:22.556579 #4]  INFO -- : [80062a29-a647-4c5e-a6f7-60201d40830e] Started GET "/" for 103.208.220.195 at 2020-11-23 17:30:22 +0000
2020-11-23T17:30:22.558172+00:00 app[web.1]: I, [2020-11-23T17:30:22.558076 #4]  INFO -- : [80062a29-a647-4c5e-a6f7-60201d40830e] Processing by WelcomeController#index as HTML
2020-11-23T17:30:22.559689+00:00 app[web.1]: I, [2020-11-23T17:30:22.559600 #4]  INFO -- : [80062a29-a647-4c5e-a6f7-60201d40830e] Completed 401 Unauthorized in 1ms (Allocations: 292)
2020-11-23T17:30:22.567725+00:00 heroku[router]: at=info method=GET path="/" host=finance-tracker-ayub.herokuapp.com request_id=80062a29-a647-4c5e-a6f7-60201d40830e fwd="103.208.220.195" dyno=web.1 connect=0ms service=11ms status=302 bytes=1077 protocol=https
2020-11-23T17:30:23.019017+00:00 heroku[router]: at=info method=GET path="/users/sign_in" host=finance-tracker-ayub.herokuapp.com request_id=e3dfbc3b-2907-4d68-8cef-d25093693ddd fwd="103.208.220.195" dyno=web.1 connect=1ms service=46ms status=500 bytes=1827 protocol=https
2020-11-23T17:30:22.974275+00:00 app[web.1]: I, [2020-11-23T17:30:22.974135 #4]  INFO -- : [e3dfbc3b-2907-4d68-8cef-d25093693ddd] Started GET "/users/sign_in" for 103.208.220.195 at 2020-11-23 17:30:22 +0000
2020-11-23T17:30:22.975771+00:00 app[web.1]: I, [2020-11-23T17:30:22.975680 #4]  INFO -- : [e3dfbc3b-2907-4d68-8cef-d25093693ddd] Processing by Devise::SessionsController#new as HTML
2020-11-23T17:30:23.011875+00:00 app[web.1]: I, [2020-11-23T17:30:23.011746 #4]  INFO -- : [e3dfbc3b-2907-4d68-8cef-d25093693ddd] Completed 500 Internal Server Error in 36ms (ActiveRecord: 11.1ms | Allocations: 2360)
2020-11-23T17:30:23.016758+00:00 app[web.1]: F, [2020-11-23T17:30:23.016601 #4] FATAL -- : [e3dfbc3b-2907-4d68-8cef-d25093693ddd]   
2020-11-23T17:30:23.016760+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2020-11-23T17:30:23.016761+00:00 app[web.1]: LINE 8:  WHERE a.attrelid = '"users"'::regclass
2020-11-23T17:30:23.016762+00:00 app[web.1]:                             ^
2020-11-23T17:30:23.016763+00:00 app[web.1]: ):
2020-11-23T17:30:23.016764+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd]   
2020-11-23T17:30:23.016765+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `exec'
2020-11-23T17:30:23.016766+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
2020-11-23T17:30:23.016767+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
2020-11-23T17:30:23.016767+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
2020-11-23T17:30:23.016768+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
2020-11-23T17:30:23.016768+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
2020-11-23T17:30:23.016769+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
2020-11-23T17:30:23.016769+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
2020-11-23T17:30:23.016770+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
2020-11-23T17:30:23.016770+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
2020-11-23T17:30:23.016770+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
2020-11-23T17:30:23.016771+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
2020-11-23T17:30:23.016771+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
2020-11-23T17:30:23.016772+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2020-11-23T17:30:23.016772+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
2020-11-23T17:30:23.016772+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
2020-11-23T17:30:23.016773+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/postgresql_adapter.rb:820:in `column_definitions'
2020-11-23T17:30:23.016773+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/abstract/schema_statements.rb:114:in `columns'
2020-11-23T17:30:23.016773+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
2020-11-23T17:30:23.016773+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
2020-11-23T17:30:23.016775+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/model_schema.rb:488:in `load_schema!'
2020-11-23T17:30:23.016775+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/attributes.rb:247:in `load_schema!'
2020-11-23T17:30:23.016775+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/attribute_decorators.rb:50:in `load_schema!'
2020-11-23T17:30:23.016776+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/model_schema.rb:478:in `block in load_schema'
2020-11-23T17:30:23.016785+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] vendor/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
2020-11-23T17:30:23.016785+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/model_schema.rb:475:in `load_schema'
2020-11-23T17:30:23.016792+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/model_schema.rb:362:in `attribute_types'
2020-11-23T17:30:23.016792+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/attribute_methods.rb:171:in `has_attribute?'
2020-11-23T17:30:23.016793+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/inheritance.rb:55:in `new'
2020-11-23T17:30:23.016793+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] devise (4.7.3) app/controllers/devise/sessions_controller.rb:11:in `new'
2020-11-23T17:30:23.016793+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
2020-11-23T17:30:23.016794+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/abstract_controller/base.rb:195:in `process_action'
2020-11-23T17:30:23.016794+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
2020-11-23T17:30:23.016794+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
2020-11-23T17:30:23.016795+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/callbacks.rb:135:in `run_callbacks'
2020-11-23T17:30:23.016795+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
2020-11-23T17:30:23.016795+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
2020-11-23T17:30:23.016796+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
2020-11-23T17:30:23.016796+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument'
2020-11-23T17:30:23.016797+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2020-11-23T17:30:23.016797+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `instrument'
2020-11-23T17:30:23.016797+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
2020-11-23T17:30:23.016798+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
2020-11-23T17:30:23.016798+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activerecord (6.0.3.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
2020-11-23T17:30:23.016799+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/abstract_controller/base.rb:136:in `process'
2020-11-23T17:30:23.016799+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionview (6.0.3.4) lib/action_view/rendering.rb:39:in `process'
2020-11-23T17:30:23.016799+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_controller/metal.rb:190:in `dispatch'
2020-11-23T17:30:23.016800+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_controller/metal.rb:254:in `dispatch'
2020-11-23T17:30:23.016800+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
2020-11-23T17:30:23.016800+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
2020-11-23T17:30:23.016801+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
2020-11-23T17:30:23.016801+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
2020-11-23T17:30:23.016801+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
2020-11-23T17:30:23.016802+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each'
2020-11-23T17:30:23.016802+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
2020-11-23T17:30:23.016802+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
2020-11-23T17:30:23.016803+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
2020-11-23T17:30:23.016803+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
2020-11-23T17:30:23.016804+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] warden (1.2.9) lib/warden/manager.rb:34:in `call'
2020-11-23T17:30:23.016804+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
2020-11-23T17:30:23.016804+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] rack (2.2.3) lib/rack/etag.rb:27:in `call'
2020-11-23T17:30:23.016810+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
2020-11-23T17:30:23.016811+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] rack (2.2.3) lib/rack/head.rb:12:in `call'
2020-11-23T17:30:23.016811+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
2020-11-23T17:30:23.016811+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
2020-11-23T17:30:23.016812+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
2020-11-23T17:30:23.016812+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:648:in `call'
2020-11-23T17:30:23.016813+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
2020-11-23T17:30:23.016813+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
2020-11-23T17:30:23.016813+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2020-11-23T17:30:23.016814+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
2020-11-23T17:30:23.016814+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
2020-11-23T17:30:23.016815+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
2020-11-23T17:30:23.016815+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app'
2020-11-23T17:30:23.016815+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `block in call'
2020-11-23T17:30:23.016816+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
2020-11-23T17:30:23.016816+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:28:in `tagged'
2020-11-23T17:30:23.016816+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `tagged'
2020-11-23T17:30:23.016817+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `call'
2020-11-23T17:30:23.016817+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
2020-11-23T17:30:23.016818+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
2020-11-23T17:30:23.016818+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
2020-11-23T17:30:23.016819+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
2020-11-23T17:30:23.016819+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2020-11-23T17:30:23.016820+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
2020-11-23T17:30:23.016820+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
2020-11-23T17:30:23.016820+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
2020-11-23T17:30:23.016821+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
2020-11-23T17:30:23.016821+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
2020-11-23T17:30:23.016822+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] puma (4.3.6) lib/puma/configuration.rb:228:in `call'
2020-11-23T17:30:23.016822+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] puma (4.3.6) lib/puma/server.rb:713:in `handle_request'
2020-11-23T17:30:23.016822+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] puma (4.3.6) lib/puma/server.rb:472:in `process_client'
2020-11-23T17:30:23.016823+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] puma (4.3.6) lib/puma/server.rb:328:in `block in run'
2020-11-23T17:30:23.016823+00:00 app[web.1]: [e3dfbc3b-2907-4d68-8cef-d25093693ddd] puma (4.3.6) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
2020-11-23T17:30:23.458056+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=finance-tracker-ayub.herokuapp.com request_id=b9f4c77d-b802-429c-98cc-4854026a5425 fwd="103.208.220.195" dyno=web.1 connect=0ms service=2ms status=200 bytes=143 protocol=https
```

**Comment by wasifhossain** [comment]
> ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist

perhaps you missed running migration?

**Comment by ansary14-zz** [comment]
`heroku run rake db:migrate` run the migration
