### ISSUE TITLE
invalid login credential in active admin

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#138]
in my **finance-tracker** repository, I add this gem first in **Gemfile**
`gem 'activeadmin'`

then run `bundle install --without production`

after that run that installer
`rails generate active_admin:install`

```
> ayub@ayub:~/rails-project/finance-tracker$ rails generate active_admin:install
> Running via Spring preloader in process 6908
>       invoke  devise
>     generate    No need to install devise, already done.
>       invoke    active_record
>       create      db/migrate/20210103120558_devise_create_admin_users.rb
>       create      app/models/admin_user.rb
>       invoke      test_unit
>       create        test/models/admin_user_test.rb
>       create        test/fixtures/admin_users.yml
>       insert      app/models/admin_user.rb
>        route    devise_for :admin_users
>         gsub    app/models/admin_user.rb
>         gsub    config/routes.rb
>       append    db/seeds.rb
>       create  config/initializers/active_admin.rb
>       create  app/admin
>       create  app/admin/dashboard.rb
>       create  app/admin/admin_users.rb
>       insert  config/routes.rb
>     generate  active_admin:assets
>        rails  generate active_admin:assets 
> Running via Spring preloader in process 7018
>       create  app/assets/javascripts/active_admin.js
>       create  app/assets/stylesheets/active_admin.scss
>       create  db/migrate/20210103120608_create_active_admin_comments.rb
> 

```

after that run the migration 
`rails db:migrate`

run the server
`rails s`

**Comment by ansary14-zz** [comment]
https://activeadmin.info/documentation.html
here they say 
```
Visit http://localhost:3000/admin and log in using:

    User: admin@example.com
    Password: password

Voila! You’re on your brand new Active Admin dashboard.
```
after providing the above user and password it says **invalid email or password.**
no dashboard ...

https://user-images.githubusercontent.com/33208962/103480997-2ace5b00-4e02-11eb-9d01-357d9fefe733.mp4

**Comment by wasifhossain** [comment]
if you have run the migration, then you should have a new table called `admin_users` in your db by now.

could you share the output from inside `rails console`
```rb
AdminUser.first
```

**Comment by wasifhossain** [comment]
oh i just noted the line from your OP
```
append    db/seeds.rb
```
which means the seed data might not have been inserted in your db yet.

could you share that file too.

you may also check this SO post to get more clarity on dealing with seed data: https://stackoverflow.com/questions/18569240/how-to-add-new-seed-data-to-existing-rails-database

**Comment by ansary14-zz** [comment]
> if you have run the migration, then you should have a new table called `admin_users` in your db by now.
> 
> could you share the output from inside `rails console`
> 
> ```ruby
> AdminUser.first
> ```

```
2.6.3 :001 > AdminUser.first
   (21.2ms)  SELECT sqlite_version(*)
  AdminUser Load (20.8ms)  SELECT "admin_users".* FROM "admin_users" ORDER BY "admin_users"."id" ASC LIMIT ?  [["LIMIT", 1]]
 => nil 
```

**Comment by ansary14-zz** [comment]
content of `db/seeds.rb`
```

AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
```

**Comment by ansary14-zz** [comment]
```
ayub@ayub:~/rails-project/finance-tracker$ rails db:seed
ayub@ayub:~/rails-project/finance-tracker$ rake db:seed
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Email has already been taken
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:80:in `raise_validation_error'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:53:in `save!'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:318:in `block in save!'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:318:in `save!'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/suppressor.rb:48:in `save!'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:55:in `create!'
/home/ayub/rails-project/finance-tracker/db/seeds.rb:8:in `<main>'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/engine.rb:557:in `block in load_seed'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/engine.rb:675:in `with_inline_jobs'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/engine.rb:557:in `load_seed'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/home/ayub/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/ayub/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/home/ayub/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

```

**now run the server and checked with email and password it shows the dashboard successfully.**
