### ISSUE TITLE
Heroku push rejected

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#142]
Maybe while editing the bootstrap(hidden scss files) in different files(Naming the file in next comment) I messed up.
```
abir@abir:~/Ruby code/alpha-blog$ git push heroku main
Enumerating objects: 88, done.
Counting objects: 100% (88/88), done.
Delta compression using up to 4 threads
Compressing objects: 100% (57/57), done.
Writing objects: 100% (59/59), 3.83 MiB | 794.00 KiB/s, done.
Total 59 (delta 25), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-18 stack
remote: -----> Ruby app detected
remote: -----> Installing bundler 2.1.4
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.6.5
remote: -----> Installing dependencies using bundler 2.1.4
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
remote:        The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
remote:        Using rake 13.0.1
remote:        Using concurrent-ruby 1.1.7
remote:        Using i18n 1.8.5
remote:        Using minitest 5.14.2
remote:        Using thread_safe 0.3.6
remote:        Using tzinfo 1.2.9
remote:        Using zeitwerk 2.4.2
remote:        Using activesupport 6.0.3.4
remote:        Using builder 3.2.4
remote:        Using erubi 1.10.0
remote:        Using mini_portile2 2.4.0
remote:        Using nokogiri 1.10.10
remote:        Using rails-dom-testing 2.0.3
remote:        Using crass 1.0.6
remote:        Using loofah 2.8.0
remote:        Using rails-html-sanitizer 1.3.0
remote:        Using actionview 6.0.3.4
remote:        Using rack 2.2.3
remote:        Using rack-test 1.1.0
remote:        Using actionpack 6.0.3.4
remote:        Using nio4r 2.5.4
remote:        Using websocket-extensions 0.1.5
remote:        Using websocket-driver 0.7.3
remote:        Using actioncable 6.0.3.4
remote:        Using globalid 0.4.2
remote:        Using activejob 6.0.3.4
remote:        Using activemodel 6.0.3.4
remote:        Using activerecord 6.0.3.4
remote:        Using mimemagic 0.3.5
remote:        Using marcel 0.3.3
remote:        Using activestorage 6.0.3.4
remote:        Using mini_mime 1.0.2
remote:        Using mail 2.7.1
remote:        Using actionmailbox 6.0.3.4
remote:        Using actionmailer 6.0.3.4
remote:        Using actiontext 6.0.3.4
remote:        Using msgpack 1.3.3
remote:        Using bootsnap 1.5.1
remote:        Using bundler 2.1.4
remote:        Using ffi 1.13.1
remote:        Using jbuilder 2.10.1
remote:        Using method_source 1.0.0
remote:        Using pg 1.2.3
remote:        Using puma 4.3.7
remote:        Using rack-proxy 0.6.5
remote:        Using thor 1.0.1
remote:        Using railties 6.0.3.4
remote:        Using sprockets 4.0.2
remote:        Using sprockets-rails 3.2.2
remote:        Using rails 6.0.3.4
remote:        Using sassc 2.4.0
remote:        Using tilt 2.0.10
remote:        Using sassc-rails 2.1.2
remote:        Using sass-rails 6.0.0
remote:        Using turbolinks-source 5.2.0
remote:        Using turbolinks 5.2.1
remote:        Using webpacker 4.3.0
remote:        Bundle complete! 19 Gemfile dependencies, 57 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Bundle completed (0.44s)
remote:        Cleaning up the bundler cache.
remote: -----> Installing node-v12.16.2-linux-x64
remote: -----> Installing yarn-v1.22.4
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        yarn install v1.22.4
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@2.1.3: The platform "linux" is incompatible with this module.
remote:        info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        info fsevents@1.2.13: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning " > webpack-dev-server@3.11.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
remote:        warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
remote:        [4/4] Building fresh packages...
remote:        Done in 34.53s.
remote:        yarn install v1.22.4
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@2.1.3: The platform "linux" is incompatible with this module.
remote:        info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        info fsevents@1.2.13: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning " > webpack-dev-server@3.11.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
remote:        warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
remote:        [4/4] Building fresh packages...
remote:        Done in 5.50s.
remote:        I, [2021-02-01T22:13:30.836870 #316]  INFO -- : Writing /tmp/build_fb053d12/public/assets/blog-072150ac7751f4d9a13812301cca312986771954b5d7274ba736adaaf34d059d.jpg
remote:        I, [2021-02-01T22:13:30.840549 #316]  INFO -- : Writing /tmp/build_fb053d12/public/assets/application-baf5634ae8750e75af6c388e0ef719908bd0c6e080828f9158a4d7b6d0034347.css
remote:        I, [2021-02-01T22:13:30.841813 #316]  INFO -- : Writing /tmp/build_fb053d12/public/assets/application-baf5634ae8750e75af6c388e0ef719908bd0c6e080828f9158a4d7b6d0034347.css.gz
remote:        I, [2021-02-01T22:13:30.855567 #316]  INFO -- : Writing /tmp/build_fb053d12/public/assets/custom-500363a931a419253513382003394c1d825a1668b28d357c63d499f127f70466.css
remote:        I, [2021-02-01T22:13:30.856599 #316]  INFO -- : Writing /tmp/build_fb053d12/public/assets/custom-500363a931a419253513382003394c1d825a1668b28d357c63d499f127f70466.css.gz
remote:        Compiling...
remote:        Compilation failed:
remote:        /tmp/build_fb053d12/config/webpack/environment.js:3
remote:        const { environment } = require('@rails/webpacker')
remote:                ^
remote:        
remote:        SyntaxError: Identifier 'environment' has already been declared
remote:            at new Script (vm.js:88:7)
remote:            at NativeCompileCache._moduleCompile (/tmp/build_fb053d12/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
remote:            at Module._compile (/tmp/build_fb053d12/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
remote:            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
remote:            at Module.load (internal/modules/cjs/loader.js:1000:32)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:899:14)
remote:            at Module.require (internal/modules/cjs/loader.js:1042:19)
remote:            at require (/tmp/build_fb053d12/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
remote:            at Object.<anonymous> (/tmp/build_fb053d12/config/webpack/production.js:3:21)
remote:            at Module._compile (/tmp/build_fb053d12/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
remote:            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
remote:            at Module.load (internal/modules/cjs/loader.js:1000:32)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:899:14)
remote:            at Module.require (internal/modules/cjs/loader.js:1042:19)
remote:            at require (/tmp/build_fb053d12/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
remote:            at WEBPACK_OPTIONS (/tmp/build_fb053d12/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
remote:            at requireConfig (/tmp/build_fb053d12/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
remote:            at /tmp/build_fb053d12/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
remote:            at Array.forEach (<anonymous>)
remote:            at module.exports (/tmp/build_fb053d12/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
remote:            at /tmp/build_fb053d12/node_modules/webpack-cli/bin/cli.js:71:45
remote:            at Object.parse (/tmp/build_fb053d12/node_modules/yargs/yargs.js:576:18)
remote:            at /tmp/build_fb053d12/node_modules/webpack-cli/bin/cli.js:49:8
remote:            at Object.<anonymous> (/tmp/build_fb053d12/node_modules/webpack-cli/bin/cli.js:366:3)
remote:            at Module._compile (internal/modules/cjs/loader.js:1156:30)
remote:            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
remote:            at Module.load (internal/modules/cjs/loader.js:1000:32)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:899:14)
remote:            at Module.require (internal/modules/cjs/loader.js:1042:19)
remote:            at require (internal/modules/cjs/helpers.js:77:18)
remote:        
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote:  !
remote:  ! ## Warning - The same version of this code has already been built: bd1eb64b30f5387186bf3c6ed880e8272da636f1
remote:  !
remote:  ! We have detected that you have triggered a build from source code with version bd1eb64b30f5387186bf3c6ed880e8272da636f1
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.
remote:  !
remote:  ! If you are developing on a branch and deploying via git you must run:
remote:  !
remote:  !     git push heroku <branchname>:main
remote:  !
remote:  ! This article goes into details on the behavior:
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to abirblog.
remote: 
To https://git.heroku.com/abirblog.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/abirblog.git'
```

**Comment by sadmanahmed** [comment]
File name: _navbar.scss
line no : 225,228 ,I mistakenly change both of them to white and while closing them in intention of not saving, I mistakenly press save and close. 
Except this , I have not touched any hidden scss files.
![image](https://user-images.githubusercontent.com/19534210/106525445-2df65d00-650e-11eb-9658-24ca900d84bb.png)

**Comment by sadmanahmed** [comment]
```
 const { environment } = require('@rails/webpacker')
remote:                ^
remote:        
remote:        SyntaxError: Identifier 'environment' has already been declared
```
okay Solved.. I have typed a line twice in environment.js ..now it is working fine alhamdulillah.

**Comment by wasifhossain** [comment]
good catch :+1:
