### ISSUE TITLE
Postgres Error with rails 5

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#144]
Do we have any issue with rails 5.2.4 with this issue #98 . As the current udemy practice project .. they advice to use 5.2.4 , but when I used and try to setup postgres it is throwing errors like
```
rails db:create
rails aborted!
NoMethodError: Cannot load database configuration:
undefined method `module_parent_name' for MessageMe::Application:Class
Did you mean?  module_exec
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/railtie.rb:192:in `method_missing'
```
so I open another project on rails v6 and follow the postgres setup list. This time it is perfectly worked. 
```
abir@abir:~/Ruby code/message_me_v6$ rails db:create
Created database 'message_me_v6_development'
Created database 'message_me_v6_test'
abir@abir:~/Ruby code/message_me_v6$ rails db:environment:set
abir@abir:~/Ruby code/message_me_v6$ rails c
Running via Spring preloader in process 663
Loading development environment (Rails 6.0.3.5)
2.6.5 :001 > ENV['PG_USERNAME'] 
 => "abir" 
2.6.5 :002 > 
```
What is the reason this things happening with v 5.2.4

**Comment by wasifhossain** [comment]
dont think rails 5.x has any issues with loading env vars. if you can meet the general requirements of loading such variables, then it shouldn't matter what version of rails you are using.

**Comment by sadmanahmed** [comment]
Then why it is throwing errors. What should I do ? I followed everything
```
abir@abir:~/Ruby code/message_me$ rails db:create
rails aborted!
NoMethodError: Cannot load database configuration:
undefined method `module_parent_name' for MessageMe::Application:Class
Did you mean?  module_exec
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/railtie.rb:192:in `method_missing'
(erb):30:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/application/configuration.rb:172:in `database_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.5/lib/active_record/railtie.rb:39:in `block (3 levels) in <class:Railtie>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/Ruby code/message_me/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/Ruby code/message_me/bin/spring:15:in `require'
/home/abir/Ruby code/message_me/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
NoMethodError: undefined method `module_parent_name' for MessageMe::Application:Class
Did you mean?  module_exec
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/railtie.rb:192:in `method_missing'
(erb):30:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/application/configuration.rb:172:in `database_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.5/lib/active_record/railtie.rb:39:in `block (3 levels) in <class:Railtie>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.5/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/Ruby code/message_me/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/Ruby code/message_me/bin/spring:15:in `require'
/home/abir/Ruby code/message_me/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)

```

**Comment by wasifhossain** [comment]
could you share the steps that you followed so that I can reproduce the issue on a new project

**Comment by sadmanahmed** [comment]
1. add pg gem > bundle install
2. copied the database.yml from #96
3. add dotenv gem > bundle install
4. add .env in the root of project with my desired name and password
5. rails db:create
6. rails db:environment:set

I have followed same for both projects but in rails 5 it gives error and in rails 6 its worked fine.

**Comment by wasifhossain** [comment]
just followed your steps with the following modifications:

ruby: 2.6.6
rails: 5.2.4.5

on step 3, i used https://direnv.net instead of dotenv

and skipped step 6.

after step 5, i could see this
```
Created database 'blog_development'
Created database 'blog_test'
```

**Comment by wasifhossain** [comment]
if you also manage to get the same as mine, i would assume it was dotenv that was making the issue
