### ISSUE TITLE
Shopify api 

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#149]
I was following this link https://khawa.tech/posts/develop-shopify-application-ruby-rails/ . I was trying to build a shopify app (As my learning style is build something to get learn practically from tutorail/documentations) , but it gives this error .
```
abir@abir:~/Ruby code/Shopify-Api$ rails generate shopify_app --api_key XXX --secret YYY
/home/abir/.rvm/gems/ruby-2.6.5/gems/shopify_api-4.2.2/lib/active_resource/connection_ext.rb:28:in `<class:Connection>': undefined method `alias_method_chain' for ActiveResource::Connection:Class
Did you mean?  alias_method (NoMethodError)
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/shopify_api-4.2.2/lib/active_resource/connection_ext.rb:4:in `<module:ActiveResource>'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/shopify_api-4.2.2/lib/active_resource/connection_ext.rb:3:in `<main>'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/shopify_api-4.2.2/lib/shopify_api.rb:7:in `<main>'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/shopify_app-7.0.11/lib/shopify_app.rb:4:in `<main>'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
	from /home/abir/Ruby code/Shopify-Api/config/application.rb:7:in `<top (required)>'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by wasifhossain** [comment]
similar to https://github.com/Shopify/shopify_api/issues/578

**Comment by wasifhossain** [comment]
could you try with the latest version: https://rubygems.org/gems/shopify_api

**Comment by wasifhossain** [comment]
reopen it if you have further qns. thanks
