### ISSUE TITLE
rails db:migrate error

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#160]
```
abir@abir:~/ruby codes/alpha-blog$ rails db:migrate
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/connection_handling.rb:189:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/railties/databases.rake:84:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.5/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.5/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.5/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/ruby codes/alpha-blog/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/ruby codes/alpha-blog/bin/spring:15:in `require'
/home/abir/ruby codes/alpha-blog/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by wasifhossain** [comment]
>PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

its a very common error msg, which you should have got familiar with by this time :smile: 

anyway, make sure that you have installed `postgresql` via apt and if its running by checking from task manager

**Comment by wasifhossain** [comment]
check `psql --version`

**Comment by wasifhossain** [comment]
also check `pg_lsclusters`

**Comment by sadmanahmed** [comment]
okay, need to install postgres... I was doubting this occurs because postgres is not setuped yet

**Comment by sadmanahmed** [comment]
```
abir@abir:~/ruby codes/alpha-blog$ psql --version

Command 'psql' not found, but can be installed with:

sudo apt install postgresql-client-common

abir@abir:~/ruby codes/alpha-blog$ pg_lsclusters

Command 'pg_lsclusters' not found, but can be installed with:

sudo apt install postgresql-common


```

**Comment by wasifhossain** [comment]
both of them can be installed via
```
sudo apt install postgresql
```

**Comment by sadmanahmed** [comment]
#125 solved postgres setup
