### ISSUE TITLE
Rails db:migrate:reset

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#20]
Need to drop the database then I will reseed the database by rails db:seed
```
sample_app git:(user-microposts) ✗ rails db:migrate:reset
PG::ObjectInUse: ERROR:  database "sample_app_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
Couldn't drop database 'sample_app_development'
rails aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "sample_app_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `async_exec'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `block (2 levels) in execute'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:89:in `block in execute'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:707:in `block (2 levels) in log'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:706:in `block in log'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:697:in `log'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:88:in `execute'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:54:in `drop_database'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:34:in `drop'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:192:in `drop'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:208:in `block in drop_current'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:207:in `drop_current'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:62:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/abir/environment/sample_app/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/environment/sample_app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
PG::ObjectInUse: ERROR:  database "sample_app_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `async_exec'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `block (2 levels) in execute'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:89:in `block in execute'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:707:in `block (2 levels) in log'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:706:in `block in log'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:697:in `log'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:88:in `execute'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:54:in `drop_database'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:34:in `drop'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:192:in `drop'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:208:in `block in drop_current'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:207:in `drop_current'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:62:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/abir/environment/sample_app/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/environment/sample_app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)
```

**Comment by sadmanahmed** [comment]
Okay, I have solved the issue by using --trace. I have to remove a extra migration file. Now working fine.
