### ISSUE TITLE
Error in test case

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#27]
```
sample_app git:(following-users) ✗ rails t
Running via Spring preloader in process 18952
Started with run options --seed 1128

ERROR["test_index_as_admin_including_pagination_and_delete_links", #<Minitest::Reporters::Suite:0x000055fe7f7edf50 @name="UsersIndexTest">, 0.4207876610016683]
 test_index_as_admin_including_pagination_and_delete_links#UsersIndexTest (0.42s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe7f70a638>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_index_test.rb:11:in `block in <class:UsersIndexTest>'

ERROR["test_index_as_non-admin", #<Minitest::Reporters::Suite:0x000055fe7f908b38 @name="UsersIndexTest">, 0.4425357319996692]
 test_index_as_non-admin#UsersIndexTest (0.44s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe7f887c90>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_index_test.rb:28:in `block in <class:UsersIndexTest>'

ERROR["test_password_resets", #<Minitest::Reporters::Suite:0x000055fe8117e320 @name="PasswordResetsTest">, 1.3421911150071537]
 test_password_resets#PasswordResetsTest (1.34s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `logged_in?' for #<#<Class:0x000055fe7f9adfc0>:0x000055fe7f9ac6c0>
        Did you mean?  logger?
            app/views/layouts/_header.html.erb:8
            app/views/layouts/application.html.erb:14
            test/integration/password_resets_test.rb:11:in `block in <class:PasswordResetsTest>'

ERROR["test_should_redirect_update_when_logged_in_as_wrong_user", #<Minitest::Reporters::Suite:0x000055fe8122a350 @name="UsersEditTest">, 1.3700842860125704]
 test_should_redirect_update_when_logged_in_as_wrong_user#UsersEditTest (1.37s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe811c9ac8>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_edit_test.rb:62:in `block in <class:UsersEditTest>'

ERROR["test_should_redirect_edit_when_logged_in_as_wrong_user", #<Minitest::Reporters::Suite:0x000055fe8137a840 @name="UsersEditTest">, 1.40030798400403]
 test_should_redirect_edit_when_logged_in_as_wrong_user#UsersEditTest (1.40s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe812bb5f8>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_edit_test.rb:55:in `block in <class:UsersEditTest>'

ERROR["test_should_redirect_update_when_not_logged_in", #<Minitest::Reporters::Suite:0x000055fe81051588 @name="UsersEditTest">, 1.4321289300132776]
 test_should_redirect_update_when_not_logged_in#UsersEditTest (1.43s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<UsersController:0x000055fe813f9938>
        Did you mean?  login_url
            test/integration/users_edit_test.rb:48:in `block in <class:UsersEditTest>'

ERROR["test_successful_edit_with_friendly_forwarding", #<Minitest::Reporters::Suite:0x000055fe815a7b90 @name="UsersEditTest">, 1.4597944880079012]
 test_successful_edit_with_friendly_forwarding#UsersEditTest (1.46s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<UsersController:0x000055fe8152bc98>
        Did you mean?  login_url
            test/integration/users_edit_test.rb:23:in `block in <class:UsersEditTest>'

ERROR["test_should_redirect_edit_when_not_logged_in", #<Minitest::Reporters::Suite:0x000055fe81655880 @name="UsersEditTest">, 1.486566807012423]
 test_should_redirect_edit_when_not_logged_in#UsersEditTest (1.49s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<UsersController:0x000055fe815ef3a0>
        Did you mean?  login_url
            test/integration/users_edit_test.rb:42:in `block in <class:UsersEditTest>'

ERROR["test_unsuccessful_edit", #<Minitest::Reporters::Suite:0x000055fe81717cf0 @name="UsersEditTest">, 1.5123254490026738]
 test_unsuccessful_edit#UsersEditTest (1.51s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe8169c500>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_edit_test.rb:11:in `block in <class:UsersEditTest>'

ERROR["test_should_get_new", #<Minitest::Reporters::Suite:0x000055fe81951cf0 @name="UsersControllerTest">, 1.5816871610004455]
 test_should_get_new#UsersControllerTest (1.58s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `logged_in?' for #<#<Class:0x000055fe817735c8>:0x000055fe817717a0>
        Did you mean?  logger?
            app/views/layouts/_header.html.erb:8
            app/views/layouts/application.html.erb:14
            test/controllers/users_controller_test.rb:11:in `block in <class:UsersControllerTest>'

ERROR["test_should_redirect_followers_when_not_logged_in", #<Minitest::Reporters::Suite:0x000055fe819e9b18 @name="UsersControllerTest">, 1.6585569020098774]
 test_should_redirect_followers_when_not_logged_in#UsersControllerTest (1.66s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<UsersController:0x000055fe81990a68>
        Did you mean?  login_url
            test/controllers/users_controller_test.rb:40:in `block in <class:UsersControllerTest>'

ERROR["test_should_redirect_following_when_not_logged_in", #<Minitest::Reporters::Suite:0x000055fe7f7f6ab0 @name="UsersControllerTest">, 1.68235799401009]
 test_should_redirect_following_when_not_logged_in#UsersControllerTest (1.68s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<UsersController:0x000055fe7f4a6b30>
        Did you mean?  login_url
            test/controllers/users_controller_test.rb:35:in `block in <class:UsersControllerTest>'

ERROR["test_should_redirect_destroy_when_not_logged_in", #<Minitest::Reporters::Suite:0x000055fe7fbf8898 @name="UsersControllerTest">, 1.7049301200022455]
 test_should_redirect_destroy_when_not_logged_in#UsersControllerTest (1.70s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<UsersController:0x000055fe7fa44f38>
        Did you mean?  login_url
            test/controllers/users_controller_test.rb:21:in `block (2 levels) in <class:UsersControllerTest>'
            test/controllers/users_controller_test.rb:20:in `block in <class:UsersControllerTest>'

ERROR["test_should_redirect_index_when_not_logged_in", #<Minitest::Reporters::Suite:0x000055fe7ffbe158 @name="UsersControllerTest">, 1.7289666610013228]
 test_should_redirect_index_when_not_logged_in#UsersControllerTest (1.73s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<UsersController:0x000055fe7fbd9060>
        Did you mean?  login_url
            test/controllers/users_controller_test.rb:16:in `block in <class:UsersControllerTest>'

ERROR["test_should_redirect_destroy_when_logged_in_as_a_non-admin", #<Minitest::Reporters::Suite:0x000055fe805ae950 @name="UsersControllerTest">, 1.7508284070063382]
 test_should_redirect_destroy_when_logged_in_as_a_non-admin#UsersControllerTest (1.75s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe8025d6e8>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/controllers/users_controller_test.rb:27:in `block in <class:UsersControllerTest>'

ERROR["test_micropost_interface", #<Minitest::Reporters::Suite:0x000055fe80f9e028 @name="MicropostsInterfaceTest">, 1.896397386008175]
 test_micropost_interface#MicropostsInterfaceTest (1.90s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe80f3ff28>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/microposts_interface_test.rb:10:in `block in <class:MicropostsInterfaceTest>'

ERROR["test_login_with_remembering", #<Minitest::Reporters::Suite:0x000055fe8105e698 @name="UsersLoginTest">, 1.9184929480106803]
 test_login_with_remembering#UsersLoginTest (1.92s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe80ffe3b0>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_login_test.rb:44:in `block in <class:UsersLoginTest>'

ERROR["test_login_with_valid_information_followed_by_logout", #<Minitest::Reporters::Suite:0x000055fe811e66c8 @name="UsersLoginTest">, 1.9599602650123416]
 test_login_with_valid_information_followed_by_logout#UsersLoginTest (1.96s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe811ac568>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/integration/users_login_test.rb:23:in `block in <class:UsersLoginTest>'

ERROR["test_login_with_valid_email/invalid_password", #<Minitest::Reporters::Suite:0x000055fe813ed980 @name="UsersLoginTest">, 2.018669918004889]
 test_login_with_valid_email/invalid_password#UsersLoginTest (2.02s)
NoMethodError:         NoMethodError: undefined method `logged_in?' for #<StaticPagesController:0x000055fe813bb520>
        Did you mean?  logger
            app/controllers/static_pages_controller.rb:4:in `home'
            test/integration/users_login_test.rb:17:in `block in <class:UsersLoginTest>'

ERROR["test_login_without_remembering", #<Minitest::Reporters::Suite:0x000055fe814712d0 @name="UsersLoginTest">, 2.0421917580097215]
 test_login_without_remembering#UsersLoginTest (2.04s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe8141c820>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_login_test.rb:50:in `block in <class:UsersLoginTest>'

ERROR["test_destroy_should_require_logged-in_user", #<Minitest::Reporters::Suite:0x000055fe81540490 @name="RelationshipsControllerTest">, 2.0660103090049233]
 test_destroy_should_require_logged-in_user#RelationshipsControllerTest (2.07s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<RelationshipsController:0x000055fe814e3628>
        Did you mean?  login_url
            test/controllers/relationships_controller_test.rb:14:in `block (2 levels) in <class:RelationshipsControllerTest>'
            test/controllers/relationships_controller_test.rb:13:in `block in <class:RelationshipsControllerTest>'

ERROR["test_create_should_require_logged-in_user", #<Minitest::Reporters::Suite:0x000055fe815a7d20 @name="RelationshipsControllerTest">, 2.130232084004092]
 test_create_should_require_logged-in_user#RelationshipsControllerTest (2.13s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<RelationshipsController:0x000055fe81575348>
        Did you mean?  login_url
            test/controllers/relationships_controller_test.rb:7:in `block (2 levels) in <class:RelationshipsControllerTest>'
            test/controllers/relationships_controller_test.rb:6:in `block in <class:RelationshipsControllerTest>'

ERROR["test_following_page", #<Minitest::Reporters::Suite:0x000055fe8168f030 @name="FollowingTest">, 2.1716782550065545]
 test_following_page#FollowingTest (2.17s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe81659188>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/following_test.rb:7:in `setup'

ERROR["test_followers_page", #<Minitest::Reporters::Suite:0x000055fe816ee558 @name="FollowingTest">, 2.191682672011666]
 test_followers_page#FollowingTest (2.19s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe816bf0a0>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/following_test.rb:7:in `setup'

ERROR["test_layout_links", #<Minitest::Reporters::Suite:0x000055fe8178e3a0 @name="SiteLayoutTest">, 2.228240292010014]
 test_layout_links#SiteLayoutTest (2.23s)
NoMethodError:         NoMethodError: undefined method `logged_in?' for #<StaticPagesController:0x000055fe8175eba0>
        Did you mean?  logger
            app/controllers/static_pages_controller.rb:4:in `home'
            test/integration/site_layout_test.rb:6:in `block in <class:SiteLayoutTest>'

ERROR["test_valid_signup_information_with_account_activation", #<Minitest::Reporters::Suite:0x000055fe818cacc8 @name="UsersSignupTest">, 2.278611264002393]
 test_valid_signup_information_with_account_activation#UsersSignupTest (2.28s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `logged_in?' for #<#<Class:0x000055fe817735c8>:0x000055fe817b9ac8>
        Did you mean?  logger?
            app/views/layouts/_header.html.erb:8
            app/views/layouts/application.html.erb:14
            test/integration/users_signup_test.rb:23:in `block in <class:UsersSignupTest>'

ERROR["test_invalid_signup_information", #<Minitest::Reporters::Suite:0x000055fe819c35a8 @name="UsersSignupTest">, 2.326853883001604]
 test_invalid_signup_information#UsersSignupTest (2.33s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `logged_in?' for #<#<Class:0x000055fe817735c8>:0x000055fe818ea898>
        Did you mean?  logger?
            app/views/layouts/_header.html.erb:8
            app/views/layouts/application.html.erb:14
            test/integration/users_signup_test.rb:10:in `block in <class:UsersSignupTest>'

ERROR["test_should_get_about", #<Minitest::Reporters::Suite:0x000055fe7fc4ac60 @name="StaticPagesControllerTest">, 2.3997779170022113]
 test_should_get_about#StaticPagesControllerTest (2.40s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `logged_in?' for #<#<Class:0x000055fe819e7868>:0x000055fe819e4aa0>
        Did you mean?  logger?
            app/views/layouts/_header.html.erb:8
            app/views/layouts/application.html.erb:14
            test/controllers/static_pages_controller_test.rb:18:in `block in <class:StaticPagesControllerTest>'

ERROR["test_should_get_home", #<Minitest::Reporters::Suite:0x000055fe7ff73ba8 @name="StaticPagesControllerTest">, 2.4187056200025836]
 test_should_get_home#StaticPagesControllerTest (2.42s)
NoMethodError:         NoMethodError: undefined method `logged_in?' for #<StaticPagesController:0x000055fe7fd32588>
        Did you mean?  logger
            app/controllers/static_pages_controller.rb:4:in `home'
            test/controllers/static_pages_controller_test.rb:6:in `block in <class:StaticPagesControllerTest>'

ERROR["test_should_get_contact", #<Minitest::Reporters::Suite:0x000055fe80dc2c90 @name="StaticPagesControllerTest">, 2.4660923600022215]
 test_should_get_contact#StaticPagesControllerTest (2.47s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `logged_in?' for #<#<Class:0x000055fe819e7868>:0x000055fe80204728>
        Did you mean?  logger?
            app/views/layouts/_header.html.erb:8
            app/views/layouts/application.html.erb:14
            test/controllers/static_pages_controller_test.rb:24:in `block in <class:StaticPagesControllerTest>'

ERROR["test_should_get_help", #<Minitest::Reporters::Suite:0x000055fe80ef35b0 @name="StaticPagesControllerTest">, 2.514194364004652]
 test_should_get_help#StaticPagesControllerTest (2.51s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `logged_in?' for #<#<Class:0x000055fe819e7868>:0x000055fe80dee868>
        Did you mean?  logger?
            app/views/layouts/_header.html.erb:8
            app/views/layouts/application.html.erb:14
            test/controllers/static_pages_controller_test.rb:12:in `block in <class:StaticPagesControllerTest>'

ERROR["test_profile_display", #<Minitest::Reporters::Suite:0x000055fe81717e58 @name="UsersProfileTest">, 2.629860744011239]
 test_profile_display#UsersProfileTest (2.63s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `logged_in?' for #<#<Class:0x000055fe817735c8>:0x000055fe81040a58>
        Did you mean?  logger?
            app/views/users/show.html.erb:15
            test/integration/users_profile_test.rb:11:in `block in <class:UsersProfileTest>'

ERROR["test_should_redirect_create_when_not_logged_in", #<Minitest::Reporters::Suite:0x000055fe8177aa30 @name="MicropostsControllerTest">, 2.6530230339994887]
 test_should_redirect_create_when_not_logged_in#MicropostsControllerTest (2.65s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<MicropostsController:0x000055fe8173f638>
        Did you mean?  login_url
            test/controllers/microposts_controller_test.rb:10:in `block (2 levels) in <class:MicropostsControllerTest>'
            test/controllers/microposts_controller_test.rb:9:in `block in <class:MicropostsControllerTest>'

ERROR["test_should_redirect_destroy_for_wrong_micropost", #<Minitest::Reporters::Suite:0x000055fe817dc500 @name="MicropostsControllerTest">, 2.673517883013119]
 test_should_redirect_destroy_for_wrong_micropost#MicropostsControllerTest (2.67s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe817ae2b8>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/controllers/microposts_controller_test.rb:23:in `block in <class:MicropostsControllerTest>'

ERROR["test_should_redirect_destroy_when_not_logged_in", #<Minitest::Reporters::Suite:0x000055fe8184efb0 @name="MicropostsControllerTest">, 2.7009980180009734]
 test_should_redirect_destroy_when_not_logged_in#MicropostsControllerTest (2.70s)
NoMethodError:         NoMethodError: undefined method `logged_in_user' for #<MicropostsController:0x000055fe81816b38>
        Did you mean?  login_url
            test/controllers/microposts_controller_test.rb:17:in `block (2 levels) in <class:MicropostsControllerTest>'
            test/controllers/microposts_controller_test.rb:16:in `block in <class:MicropostsControllerTest>'

  59/59: [======================================================================] 100% Time: 00:00:02, Time: 00:00:02

Finished in 2.72421s
59 tests, 53 assertions, 0 failures, 35 errors, 0 skips
```

**Comment by sadmanahmed** [comment]
Situation : I just ended up a chapter than tried the rails t,it works fine that time. Then I closed all the tabs of codes(saved obviously) . Then I made some statements in the controller file, it is working fine in the localhost now. But then I tried rails t , it showed up this whole error. Maybe a printing mistake occured while closing the tabs. I can see 2 main point 1. create and 2, logger ,but failed to find out the problem

**Comment by wasifhossain** [comment]
```
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe7f70a638>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_index_test.rb:11:in `block in <class:UsersIndexTest>'
```

can you share the code segments referred by the log above

**Comment by sadmanahmed** [comment]
sessions_controller.rb
```
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        **log_in user**
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end
```
test_helper.rb
```
ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'
require 'rails/test_help'

require "minitest/reporters"
Minitest::Reporters.use!

class ActiveSupport::TestCase
  fixtures :all

  # Returns true if a test user is logged in.
  def is_logged_in?
    !session[:user_id].nil?
  end

  # Log in as a particular user.
  def log_in_as(user)
    session[:user_id] = user.id
  end
end

class ActionDispatch::IntegrationTest

  # Log in as a particular user.
  def log_in_as(user, password: 'password', remember_me: '1')
    post login_path, params: { session: { email: user.email,
                                          password: password,
                                          remember_me: remember_me } }
  end
end


```

users_index_test.rb
```
require 'test_helper'

class UsersIndexTest < ActionDispatch::IntegrationTest

  def setup
    @admin     = users(:michael)
    @non_admin = users(:archer)
  end

  test "index as admin including pagination and delete links" do
    log_in_as(@admin)
    get users_path
    assert_template 'users/index'
    assert_select 'div.pagination'
    first_page_of_users = User.paginate(page: 1)
    first_page_of_users.each do |user|
      assert_select 'a[href=?]', user_path(user), text: user.name
      unless user == @admin
        assert_select 'a[href=?]', user_path(user), text: 'delete'
      end
    end
    assert_difference 'User.count', -1 do
      delete user_path(@non_admin)
    end
  end

  test "index as non-admin" do
    log_in_as(@non_admin)
    get users_path
    assert_select 'a', text: 'delete', count: 0
  end
end

```

**Comment by wasifhossain** [comment]
please also make a comment after the lines that are pointed by the log. otherwise its hard to see which line is meant by the error log

**Comment by sadmanahmed** [comment]
Have not understand this 
https://github.com/ormprog/rails_ama/issues/27#issuecomment-597243326

**Comment by wasifhossain** [comment]
the log below is pointing to some line in the corresponding files
```
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_index_test.rb:11:in
```
but i am not sure which lines are those in the code you shared above

**Comment by sadmanahmed** [comment]
Let me check the chapter from the beginning than

**Comment by wasifhossain** [comment]
can you highlight line 10 as mentioned in app/controllers/sessions_controller.rb:10

also line 26 in test/test_helper.rb:26

and line 11 in test/integration/users_index_test.rb:11

thats what I meant above

**Comment by sadmanahmed** [comment]
```
sessions_controller.rb
```
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        **log_in user**
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

```
test_helper.rb
```
ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'
require 'rails/test_help'

require "minitest/reporters"
Minitest::Reporters.use!

class ActiveSupport::TestCase
  fixtures :all

  # Returns true if a test user is logged in.
  def is_logged_in?
    !session[:user_id].nil?
  end

  # Log in as a particular user.
  def log_in_as(user)
    session[:user_id] = user.id
  end
end

class ActionDispatch::IntegrationTest

  # Log in as a particular user.
  def log_in_as(user, password: 'password', remember_me: '1')
    **post login_path, params: { session: { email: user.email,**
                                          password: password,
                                          remember_me: remember_me } }
  end
end



```
users_index_test.rb
```
require 'test_helper'

class UsersIndexTest < ActionDispatch::IntegrationTest

  def setup
    @admin     = users(:michael)
    @non_admin = users(:archer)
  end

  test "index as admin including pagination and delete links" do
    **log_in_as(@admin)**
    get users_path
    assert_template 'users/index'
    assert_select 'div.pagination'
    first_page_of_users = User.paginate(page: 1)
    first_page_of_users.each do |user|
      assert_select 'a[href=?]', user_path(user), text: user.name
      unless user == @admin
        assert_select 'a[href=?]', user_path(user), text: 'delete'
      end
    end
    assert_difference 'User.count', -1 do
      delete user_path(@non_admin)
    end
  end

  test "index as non-admin" do
    log_in_as(@non_admin)
    get users_path
    assert_select 'a', text: 'delete', count: 0
  end
end

**Comment by sadmanahmed** [comment]
The big highlighted lines are actually comment out lines and the **BOLD ONE'S ARE THE LINE YOU ASKED FOR**

**Comment by wasifhossain** [comment]
looks like you have whole bunch of issues in different test methods. lets fix them one by one

can you run 
```sh
rails t test/integration/users_index_test.rb:10
``` 
that points to `test "index as admin including pagination and delete links" do`

and share the output too

**Comment by sadmanahmed** [comment]
```
sample_app git:(following-users) ✗ rails t test/integration/users_index_test.rb:10
Running via Spring preloader in process 26723
Started with run options --seed 47321

ERROR["test_index_as_admin_including_pagination_and_delete_links", #<Minitest::Reporters::Suite:0x000055fe7f6be828 @name="UsersIndexTest">, 1.510449523004354]
 test_index_as_admin_including_pagination_and_delete_links#UsersIndexTest (1.51s)
NoMethodError:         NoMethodError: undefined method `log_in' for #<SessionsController:0x000055fe7f5def48>
        Did you mean?  login_url
            app/controllers/sessions_controller.rb:10:in `create'
            test/test_helper.rb:26:in `log_in_as'
            test/integration/users_index_test.rb:11:in `block in <class:UsersIndexTest>'

  2/2: [=============================================================] 100% Time: 00:00:01, Time: 00:00:01

Finished in 1.51282s
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by wasifhossain** [comment]
whats the output of `rails routes | grep login`

**Comment by sadmanahmed** [comment]
```
sample_app git:(following-users) ✗ rails routes | grep login
                                login GET    /login(.:format)                                                                         sessions#new
                                      POST   /login(.:format)                                                                         sessions#create

```

**Comment by wasifhossain** [comment]
```rb
# sessions_controller.rb

  def create
      ...
      if user.activated?
        log_in user # PLEASE SHARE THE log_in METHOD
      ...
  end
```

**Comment by sadmanahmed** [comment]
```
# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
```

**Comment by wasifhossain** [comment]
> ```
> # Logs in the given user.
>   def log_in(user)
>     session[:user_id] = user.id
>   end
> ```

where is it defined

**Comment by sadmanahmed** [comment]
sessions_helper.rb

**Comment by wasifhossain** [comment]
please prepend the relative path too. like where is the file located under the root

**Comment by sadmanahmed** [comment]
app/helpers/sessions_helper.rb

**Comment by sadmanahmed** [comment]
vaiaaaaaa

**Comment by sadmanahmed** [comment]
```
sample_app git:(following-users) ✗ rails t
Running via Spring preloader in process 27927
Started with run options --seed 30481

  63/63: [===========================================================] 100% Time: 00:00:04, Time: 00:00:04

Finished in 4.15313s
63 tests, 304 assertions, 0 failures, 0 errors, 0 skips

```

**Comment by wasifhossain** [comment]
what did you change

**Comment by sadmanahmed** [comment]
I was also with you and also going through the next lesson,there was a new test codes for test/integration/following_test.rb . So added that portion to check what actually happends and the codes are working fine now

**Comment by sadmanahmed** [comment]
Added this portion 
```
test/integration/following_test.rb
 require 'test_helper'

class FollowingTest < ActionDispatch::IntegrationTest

  def setup
    @user  = users(:michael)
    @other = users(:archer)
    log_in_as(@user)
  end
  .
  .
  .
  test "should follow a user the standard way" do
    assert_difference '@user.following.count', 1 do
      post relationships_path, params: { followed_id: @other.id }
    end
  end

  test "should follow a user with Ajax" do
    assert_difference '@user.following.count', 1 do
      post relationships_path, xhr: true, params: { followed_id: @other.id }
    end
  end

  test "should unfollow a user the standard way" do
    @user.follow(@other)
    relationship = @user.active_relationships.find_by(followed_id: @other.id)
    assert_difference '@user.following.count', -1 do
      delete relationship_path(relationship)
    end
  end

  test "should unfollow a user with Ajax" do
    @user.follow(@other)
    relationship = @user.active_relationships.find_by(followed_id: @other.id)
    assert_difference '@user.following.count', -1 do
      delete relationship_path(relationship), xhr: true
    end
  end
end
```

**Comment by wasifhossain** [comment]
good. btw how did you include sessions_helper in the controller.

i mean did you `include SessionsHelper` in any file?

**Comment by sadmanahmed** [comment]
I am still confused about this things yet,told you. Hope I can answer many things when I revise this
