### ISSUE TITLE
Faker::Date Error

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#34]
As I am following the API , the tutorial instructed to take fake data. So I followed it and then when did the rails db:seed then this error come up.

the code given in the api doc
```
authors = (1..20).map do
  Author.create!(
    first_name: Faker::Name.first_name,
    last_name: Faker::Name.last_name
  )
end

books = (1..70).map do
  Book.create!(
    title: Faker::Book.title,
    author: authors.sample
  )
end

users = (1..10).map do
  User.create!(
    first_name: Faker::Name.first_name,
    last_name: Faker::Name.last_name,
    email: Faker::Internet.email
  )
end

(1..300).map do
  BookCopy.create!(
    format: rand(1..3),
    published: Faker::Date.between(10.years.ago, Date.today),
    book: books.sample,
    isbn: Faker::Number.number(13)
  )
end

```

the error message
```
library git:(master) ✗ rails db:seed
rails aborted!
ArgumentError: missing keywords: from, to
/home/abir/.rvm/gems/ruby-2.6.5/gems/faker-2.11.0/lib/faker/default/date.rb:18:in `between'
/home/abir/library/db/seeds.rb:26:in `block in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/core_ext/range/each.rb:9:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/core_ext/range/each.rb:9:in `each'
/home/abir/library/db/seeds.rb:23:in `map'
/home/abir/library/db/seeds.rb:23:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/engine.rb:556:in `block in load_seed'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/engine.rb:676:in `with_inline_jobs'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/engine.rb:556:in `load_seed'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
/home/abir/library/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/library/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

```

**Comment by wasifhossain** [comment]
when you are debugging something, lets always start from the line where the error message points to, in this case:
```rb
published: Faker::Date.between(10.years.ago, Date.today),
```

if you look at the original doc of the Faker::Date api here: https://github.com/faker-ruby/faker/blob/master/doc/default/date.md

you will see that it accepts values in keyword arguments:
```rb
Faker::Date.between(from: 2.days.ago, to: Date.today)
```
so you need to provide the `from` and `to` keyword args to fix the case

P.S. the api might have been updated since the article was written that you are following

**Comment by sadmanahmed** [comment]
I think that to,it's 3 years old almost, that's why and a bit advanced level.

**Comment by wasifhossain** [comment]
makes sense

**Comment by wasifhossain** [comment]
closing the issue. if you still have issues regarding this, feel free to open it again

**Comment by sadmanahmed** [comment]
let's issue #35 solved then I can share the output

**Comment by sadmanahmed** [comment]
rails db:migrate works fine now.
