### ISSUE TITLE
Rails server Error: Address already in use - bind(2) for "127.0.0.1" port 3000 (Errno::EADDRINUSE)

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#38]
After removing the server.pid
```
se - bind(2) for "127.0.0.1" port 3000 (Errno::EADDRINUSE)
➜  library git:(master) ✗ rails s
=> Booting Puma
=> Rails 6.0.2.2 application starting in development 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 3.12.4 (ruby 2.6.5-p114), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
Exiting
Traceback (most recent call last):
	44: from bin/rails:3:in `<main>'
	43: from bin/rails:3:in `load'
	42: from /home/abir/library/bin/spring:15:in `<top (required)>'
	41: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	40: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	39: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	38: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	37: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	36: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	35: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	34: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	33: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	32: from /home/abir/library/bin/rails:9:in `<top (required)>'
	31: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
	30: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	29: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
	28: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	27: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	26: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	25: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	24: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	23: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
	22: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command.rb:46:in `invoke'
	21: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command/base.rb:69:in `perform'
	20: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	19: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	17: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `perform'
	16: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `tap'
	15: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	14: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:39:in `start'
	13: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/server.rb:327:in `start'
	12: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/rack/handler/puma.rb:73:in `run'
	11: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/launcher.rb:186:in `run'
	10: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/single.rb:98:in `run'
	 9: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/runner.rb:153:in `load_and_bind'
	 8: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:90:in `parse'
	 7: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:90:in `each'
	 6: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:106:in `block in parse'
	 5: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:266:in `add_tcp_listener'
	 4: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:266:in `each'
	 3: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:267:in `block in add_tcp_listener'
	 2: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `add_tcp_listener'
	 1: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `new'
/home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 3000 (Errno::EADDRINUSE)

```

**Comment by wasifhossain** [comment]
```
lsof -wni tcp:3000
```
will give you the `PID` of the former server process. use it in the following command
```
kill <PID>
```

**Comment by sadmanahmed** [comment]
```
library git:(master) ✗ lsof -wni tcp:3000
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ruby    15721 abir   14u  IPv4 298156      0t0  TCP 127.0.0.1:3000 (LISTEN)
ruby    15721 abir   15u  IPv6 298157      0t0  TCP [::1]:3000 (LISTEN)
ruby    15721 abir   20u  IPv4 295863      0t0  TCP 127.0.0.1:3000->127.0.0.1:49382 (ESTABLISHED)
curl    15746 abir    3u  IPv4 298162      0t0  TCP 127.0.0.1:49382->127.0.0.1:3000 (ESTABLISHED)
➜  library git:(master) ✗ kill 15746
➜  library git:(master) ✗ rails s           
=> Booting Puma
=> Rails 6.0.2.2 application starting in development 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 3.12.4 (ruby 2.6.5-p114), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
Exiting
Traceback (most recent call last):
	44: from bin/rails:3:in `<main>'
	43: from bin/rails:3:in `load'
	42: from /home/abir/library/bin/spring:15:in `<top (required)>'
	41: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	40: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	39: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	38: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	37: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	36: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	35: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	34: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	33: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	32: from /home/abir/library/bin/rails:9:in `<top (required)>'
	31: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
	30: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	29: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
	28: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	27: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	26: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	25: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	24: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	23: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
	22: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command.rb:46:in `invoke'
	21: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command/base.rb:69:in `perform'
	20: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	19: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	17: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `perform'
	16: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `tap'
	15: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	14: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:39:in `start'
	13: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/server.rb:327:in `start'
	12: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/rack/handler/puma.rb:73:in `run'
	11: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/launcher.rb:186:in `run'
	10: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/single.rb:98:in `run'
	 9: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/runner.rb:153:in `load_and_bind'
	 8: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:90:in `parse'
	 7: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:90:in `each'
	 6: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:106:in `block in parse'
	 5: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:266:in `add_tcp_listener'
	 4: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:266:in `each'
	 3: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:267:in `block in add_tcp_listener'
	 2: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `add_tcp_listener'
	 1: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `new'
/home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 3000 (Errno::EADDRINUSE)

```

**Comment by wasifhossain** [comment]
PID from the 1st line
```
ruby    15721 abir   14u  IPv4 298156      0t0  TCP 127.0.0.1:3000 (LISTEN)
```

**Comment by sadmanahmed** [comment]
same
```
library git:(master) ✗ lsof -wni tcp:3000
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ruby    15721 abir   14u  IPv4 298156      0t0  TCP 127.0.0.1:3000 (LISTEN)
ruby    15721 abir   15u  IPv6 298157      0t0  TCP [::1]:3000 (LISTEN)
ruby    15721 abir   20u  IPv4 295863      0t0  TCP 127.0.0.1:3000->127.0.0.1:49382 (ESTABLISHED)
curl    15746 abir    3u  IPv4 298162      0t0  TCP 127.0.0.1:49382->127.0.0.1:3000 (ESTABLISHED)
➜  library git:(master) ✗ kill 15721        
➜  library git:(master) ✗ rails s           
=> Booting Puma
=> Rails 6.0.2.2 application starting in development 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 3.12.4 (ruby 2.6.5-p114), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
Exiting
Traceback (most recent call last):
	44: from bin/rails:3:in `<main>'
	43: from bin/rails:3:in `load'
	42: from /home/abir/library/bin/spring:15:in `<top (required)>'
	41: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	40: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	39: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	38: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	37: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	36: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	35: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	34: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	33: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	32: from /home/abir/library/bin/rails:9:in `<top (required)>'
	31: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
	30: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	29: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
	28: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	27: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	26: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	25: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	24: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	23: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
	22: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command.rb:46:in `invoke'
	21: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command/base.rb:69:in `perform'
	20: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	19: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	17: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `perform'
	16: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `tap'
	15: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	14: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:39:in `start'
	13: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/server.rb:327:in `start'
	12: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/rack/handler/puma.rb:73:in `run'
	11: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/launcher.rb:186:in `run'
	10: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/single.rb:98:in `run'
	 9: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/runner.rb:153:in `load_and_bind'
	 8: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:90:in `parse'
	 7: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:90:in `each'
	 6: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:106:in `block in parse'
	 5: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:266:in `add_tcp_listener'
	 4: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:266:in `each'
	 3: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:267:in `block in add_tcp_listener'
	 2: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `add_tcp_listener'
	 1: from /home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `new'
/home/abir/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 3000 (Errno::EADDRINUSE)

```

**Comment by wasifhossain** [comment]
can you use `-9` between `kill` and the PID. e.g.
```
kill -9 <PID>
```

**Comment by sadmanahmed** [comment]
kill -9 15721 ?

**Comment by wasifhossain** [comment]
what does `lsof -wni tcp:3000` return now

**Comment by sadmanahmed** [comment]
it's working
