### ISSUE TITLE
How to read error message from the log

### ISSUE THREAD

**Issue by wasifhossain** [ormprog/rails_ama#41]
Lets assume we have got this log containing some errors
```
Traceback (most recent call last):
bin/rails: Bootsnap::LoadPathCache::FallbackScan
	50: from bin/rails:3:in `<main>'
	49: from bin/rails:3:in `load'
	48: from /home/abir/environment/sample_app/bin/spring:15:in `<top (required)>'
	47: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	46: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	45: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	44: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	43: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	42: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	41: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	40: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	39: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	38: from /home/abir/environment/sample_app/bin/rails:9:in `<top (required)>'
	37: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	36: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
	35: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
	34: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	33: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	32: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	31: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	30: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	29: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<main>'
	28: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
	27: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
	26: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	25: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	24: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	23: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands/routes/routes_command.rb:13:in `perform'
	22: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	21: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command/actions.rb:22:in `require_application!'
	20: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	19: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
	18: from /home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
	17: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	16: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	15: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	14: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	13: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	12: from /home/abir/environment/sample_app/config/application.rb:7:in `<main>'
	11: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler.rb:114:in `require'
	10: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
	 9: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
	 8: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
	 7: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
	 6: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	 5: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:26:in `require'
	 4: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:40:in `rescue in require'
	 3: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 2: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	 1: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- rspec-api_helpers (LoadError)
	60: from bin/rails:3:in `<main>'
	59: from bin/rails:3:in `load'
	58: from /home/abir/environment/sample_app/bin/spring:15:in `<top (required)>'
	57: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	56: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	55: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	54: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	53: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	52: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	51: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	50: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	49: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	48: from /home/abir/environment/sample_app/bin/rails:9:in `<top (required)>'
	47: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	46: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	45: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	44: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	43: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	42: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<main>'
	41: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
	40: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
	39: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	38: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	37: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	36: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands/routes/routes_command.rb:13:in `perform'
	35: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	34: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command/actions.rb:22:in `require_application!'
	33: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	32: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	31: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	30: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	29: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	28: from /home/abir/environment/sample_app/config/application.rb:7:in `<main>'
	27: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler.rb:114:in `require'
	26: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
	25: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
	24: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:72:in `block in require'
	23: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:95:in `rescue in block in require'
	22: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	21: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	20: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	19: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	18: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	17: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers.rb:2:in `<main>'
	16: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	15: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	14: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	13: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	12: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	11: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers/dispatcher.rb:1:in `<main>'
	10: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 9: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 8: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 7: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 6: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 5: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers/adapter/jsonapi/adapter.rb:1:in `<main>'
	 4: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers/adapter/jsonapi/adapter.rb:2:in `<class:Adapter>'
	 3: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers/adapter/jsonapi/adapter.rb:3:in `<class:JsonApi>'
	 2: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	 1: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant': uninitialized constant RSpec::Matchers (NameError)
	61: from bin/rails:3:in `<main>'
	60: from bin/rails:3:in `load'
	59: from /home/abir/environment/sample_app/bin/spring:15:in `<top (required)>'
	58: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	57: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	56: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	55: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	54: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	53: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	52: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	51: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	50: from /home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	49: from /home/abir/environment/sample_app/bin/rails:9:in `<top (required)>'
	48: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	47: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	46: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	45: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	44: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	43: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<main>'
	42: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
	41: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
	40: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	39: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	38: from /home/abir/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	37: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/commands/routes/routes_command.rb:13:in `perform'
	36: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	35: from /home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/command/actions.rb:22:in `require_application!'
	34: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	33: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	32: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	31: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	30: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	29: from /home/abir/environment/sample_app/config/application.rb:7:in `<main>'
	28: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler.rb:114:in `require'
	27: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
	26: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
	25: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:72:in `block in require'
	24: from /home/abir/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/bundler/runtime.rb:95:in `rescue in block in require'
	23: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	22: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	21: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	20: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	19: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	18: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers.rb:2:in `<main>'
	17: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	16: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	15: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	14: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	13: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	12: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers/dispatcher.rb:1:in `<main>'
	11: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	10: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 9: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 8: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 7: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 6: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers/adapter/jsonapi/adapter.rb:1:in `<main>'
	 5: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers/adapter/jsonapi/adapter.rb:2:in `<class:Adapter>'
	 4: from /home/abir/.rvm/gems/ruby-2.6.5/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers/adapter/jsonapi/adapter.rb:3:in `<class:JsonApi>'
	 3: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
	 2: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
	 1: from /home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant RSpec::Matchers (NameError)
```

How can we extract the actual error messages that we need in order to resolve the error?

**Comment by wasifhossain** [comment]
usually logs contain long traces of files that were touched along the way while executing some code in your project, but ending up with some errors.

most of the times, its highly likely there's some code in **your** project which resulted in that error. In such case, you just need to trim down the log in your mind by only looking at the traces that point to some code in **your** project only.

let's assume that we got the following lines from the above log that are inside your project, including any error messages:

```
Traceback (most recent call last):
bin/rails: Bootsnap::LoadPathCache::FallbackScan
	50: from bin/rails:3:in `<main>'
	49: from bin/rails:3:in `load'
        48: from /home/abir/environment/sample_app/bin/spring:15:in `<top (required)>'
...
        38: from /home/abir/environment/sample_app/bin/rails:9:in `<top (required)>'
...
	12: from /home/abir/environment/sample_app/config/application.rb:7:in `<main>'
...
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- rspec-api_helpers (LoadError)
...
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant': uninitialized constant RSpec::Matchers (NameError)
```
Note that, I skipped the duplicate lines relevant to your project.

here we can see that the last line is highlighting the real error message, whereas everything else are just traces how rails came to the error.
