### ISSUE TITLE
ActionController::RoutingError (uninitialized constant ActionController::Api Did you mean?  ActionController::API)

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#45]
GET request : http://localhost:3000/api/v1/users/1

server output
```
Started GET "/api/v1/users/1" for ::1 at 2020-04-17 04:28:21 +0600
  
ActionController::RoutingError (uninitialized constant ActionController::Api
Did you mean?  ActionController::API):
  
app/controllers/api/v1/base_controller.rb:4:in `<module:V1>'
app/controllers/api/v1/base_controller.rb:2:in `<module:Api>'
app/controllers/api/v1/base_controller.rb:1:in `<main>'
app/controllers/api/v1/users_controller.rb:6:in `<module:V1>'
app/controllers/api/v1/users_controller.rb:5:in `<module:Api>'
app/controllers/api/v1/users_controller.rb:4:in `<main>'
```
ADDITION
the base_controller.rb
```
module Api
  module V1

    class BaseController < ActionController::Api

    rescue_from ActiveRecord::RecordNotFound, with: :not_found

      def not_found
        return api_error(status: 404, errors: 'Not found')
      end

    end

  end
end
```

**Comment by wasifhossain** [comment]
this has nothing to do with Postman altogether - you could make this http request in numerous other ways, but still will get the same error

**Comment by wasifhossain** [comment]
your answer lies straight in the error msg. one of the reasons that I like Rails is that it's smart enough most of the times to show you the most accurate hints!

**Comment by wasifhossain** [comment]
it should be all-capital API as in `ActionController::API`; NOT the camel-cased `Api`

Reference: https://guides.rubyonrails.org/api_app.html#creating-a-new-application
