### ISSUE TITLE
undefined method `admin?' for nil:NilClass

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#46]
Just started Postman
so I send a GET request at : http://localhost:3000/users/1
in authoriazation I put the username and password

but it sends me strange output
the server output
```
Started GET "/users/1" for ::1 at 2020-04-17 03:43:17 +0600
Processing by UsersController#show as */*
  Parameters: {"id"=>"1"}
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/users_controller.rb:11:in `show'
  Rendering users/show.html.erb within layouts/application
   (0.6ms)  SELECT COUNT(*) FROM "users" INNER JOIN "relationships" ON "users"."id" = "relationships"."followed_id" WHERE "relationships"."follower_id" = $1  [["follower_id", 1]]
  ↳ app/views/shared/_stats.html.erb:5
   (0.7ms)  SELECT COUNT(*) FROM "users" INNER JOIN "relationships" ON "users"."id" = "relationships"."follower_id" WHERE "relationships"."followed_id" = $1  [["followed_id", 1]]
  ↳ app/views/shared/_stats.html.erb:11
  Rendered shared/_stats.html.erb (Duration: 5.0ms | Allocations: 1985)
  Micropost Exists? (0.7ms)  SELECT 1 AS one FROM "microposts" WHERE "microposts"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
  ↳ app/views/users/show.html.erb:16
   (0.7ms)  SELECT COUNT(*) FROM "microposts" WHERE "microposts"."user_id" = $1  [["user_id", 1]]
  ↳ app/views/users/show.html.erb:17
  Micropost Load (0.6ms)  SELECT "microposts".* FROM "microposts" WHERE "microposts"."user_id" = $1 ORDER BY "microposts"."created_at" DESC LIMIT $2 OFFSET $3  [["user_id", 1], ["LIMIT", 30], ["OFFSET", 0]]
  ↳ app/views/users/show.html.erb:19
  ActiveStorage::Attachment Load (0.5ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 295], ["record_type", "Micropost"], ["name", "image"], ["LIMIT", 1]]
  ↳ app/views/microposts/_micropost.html.erb:6
  ActiveStorage::Blob Load (0.3ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 295], ["LIMIT", 1]]
  ↳ app/models/micropost.rb:24:in `display_image'
  Rendered collection of microposts/_micropost.html.erb [30 times] (Duration: 7.3ms | Allocations: 3704)
  Rendered users/show.html.erb within layouts/application (Duration: 22.8ms | Allocations: 8526)
Completed 500 Internal Server Error in 27ms (ActiveRecord: 4.5ms | Allocations: 9834)


  
ActionView::Template::Error (undefined method `admin?' for nil:NilClass):
     7:   </span>
     8:   <span class="timestamp">
     9:     Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    10:     <% if current_user.admin? || current_user?(micropost.user) %>
    11:       <%= link_to "delete", micropost, method: :delete,
    12:                                        data: { confirm: "You sure?" } %>
    13:     <% end %>
  
app/views/microposts/_micropost.html.erb:10
app/views/users/show.html.erb:19
```
We have changed something(effectively) in #29 and seems like it is flagging that part. Can you overview it

** and also the postman json output is too big **

**Comment by wasifhossain** [comment]
this also has nothing to do exclusively with Postman; you can make the http request in various other ways, but will get the same error

**Comment by wasifhossain** [comment]
as the error log points by `app/views/microposts/_micropost.html.erb:10`, it should be this line
```erb
<% if current_user.admin? || current_user?(micropost.user) %>
```

the error is complaining that you are calling `current_user.admin?`, but `admin?` was called on a `nil` object. that implies `current_user` to be `nil`

**Comment by sadmanahmed** [comment]
Confused, why the current_user is nil?

**Comment by sadmanahmed** [comment]
Do we need to authorize? I choose the no auth authorization..

**Comment by wasifhossain** [comment]
try to look at the ApplicationController (most probably) where you might have defined the method. check if that method is called correctly where it should be. `binding.pry` might be your good friend :)

**Comment by sadmanahmed** [comment]
from users_controller.rb
```
 def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
```

from microposts_controller.rb
```
def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      if @micropost.nil? && current_user.admin?
        @micropost = Micropost.find_by(id: params[:id])
      end

      redirect_to root_url if @micropost.nil?
    end
```

**Comment by wasifhossain** [comment]
the error log reports `current_user`; not `correct_user` !

**Comment by wasifhossain** [comment]
can you share application controller pls

**Comment by sadmanahmed** [comment]
application_controller.rb
```
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

```

**Comment by wasifhossain** [comment]
what about `SessionsHelper`. lets see that

**Comment by sadmanahmed** [comment]
```
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
             # The tests still pass, so this branch is currently untested.
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  #Returns true if the given user is the current user
  def current_user?(user)
    user && user == current_user
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent  session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end



  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end


end

```

**Comment by wasifhossain** [comment]
wait...seems like this is similar to #47, where you are making a request to `GET /api/v1/users/1`. here you are doing it to `GET /users/1`

can you clarify the case if you still want to address this issue

**Comment by sadmanahmed** [comment]
I think we can leave this issue for this time, but if I need ,I will reopen it...
