### ISSUE TITLE
ActionView::MissingTemplate Missing template for `render jsonapi`

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#47]
Postman GET: http://localhost:3000/api/v1/users/1
Server output:
```
Started GET "/api/v1/users/1" for ::1 at 2020-04-17 05:09:41 +0600
Processing by Api::V1::UsersController#show as */*
  Parameters: {"id"=>"1"}
  User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:5:in `show'
Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.9ms | Allocations: 1512)


  
ActionView::MissingTemplate (Missing template api/v1/users/show, api/v1/base/show with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :vtt, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :mp3, :ogg, :m4a, :webm, :mp4, :otf, :ttf, :woff, :woff2, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/home/abir/environment/sample_app/app/views"
  * "/home/abir/.rvm/gems/ruby-2.6.5/gems/actiontext-6.0.0/app/views"
  * "/home/abir/.rvm/gems/ruby-2.6.5/gems/actionmailbox-6.0.0/app/views"
):
  
app/controllers/api/v1/users_controller.rb:7:in `show'

```

**Comment by sadmanahmed** [comment]
```
module Api
  module V1
    class UsersController < BaseController
      def show
        user = User.find(params[:id])

        render jsonapi: user
      end
    end
  end
end
```
line 7 is **render jsonapi: user**

**Comment by wasifhossain** [comment]
its not recognizing the serializer due to `jsonapi` option. let's use `json` here
```rb
render json: user
```

**Comment by wasifhossain** [comment]
i am assuming that you are using the `active_model_serializers` gem. if not, let's add it to Gemfile and install first
```rb
gem 'active_model_serializers', git: 'https://github.com/rails-api/active_model_serializers.git', branch: '0-10-stable'
```

**Comment by sadmanahmed** [comment]
> i am assuming that you are using the `active_model_serializers` gem. if not, let's add it to Gemfile and install first
> 
> ```ruby
> gem 'active_model_serializers', git: 'https://github.com/rails-api/active_model_serializers.git', branch: '0-10-stable'
> ```

Already the gem is added, but the branch is installed just now

**Comment by sadmanahmed** [comment]
Json output
```
{
    "id": 1,
    "name": "Abir",
    "email": "abirssc7@gmail.com",
    "created_at": "2020-03-26T17:16:38.166Z",
    "updated_at": "2020-03-26T17:16:38.166Z",
    "password_digest": "$2a$12$XmlVaxjArDUCFeOWjOGYWORCEcfCW3.GBMarZrsLCh1PdXeNRKHS2",
    "remember_digest": null,
    "admin": true,
    "activation_digest": "$2a$12$/Y3zRUi1gr9GXSCBKUw9Oet5o8z6T6.tL5e09g21TKSodQkxe.xoa",
    "activated": true,
    "activated_at": "2020-03-26T17:16:37.811Z",
    "reset_digest": null,
    "reset_sent_at": null
}
```
server output
```
Started GET "/api/v1/users/1" for ::1 at 2020-04-17 17:37:20 +0600
   (64.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Api::V1::UsersController#show as */*
  Parameters: {"id"=>"1"}
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:5:in `show'
Completed 200 OK in 154ms (Views: 21.1ms | ActiveRecord: 7.4ms | Allocations: 14494)

```
I guess my first api get request is successful

**Comment by sadmanahmed** [comment]
My current json output is on on here https://github.com/ormprog/rails_ama/issues/47#issuecomment-615198578
But 
**the expected output is this one(from the tutorial)**
```
{
  "data": {
    "id": "1",
    "type": "users",
    "attributes": {
      "name": "Example User",
      "email": "example@railstutorial.org",
      "created-at": "2016-11-05T10:15:26Z",
      "updated-at": "2016-11-19T21:30:10Z",
      "password-digest": "$2a$10$or7HFYm/H07/uE79wDae3uXMmHOX3BvRKdgedPJ1SPceiMA40V25O",
      "remember-digest": null,
      "admin": true,
      "activation-digest": "$2a$10$X5IeDtGZPuZQEVQ.ZiUP4eUzfw9M9Pag/nR.0ONiXwAAp3w98iAuC",
      "activated": true,
      "activated-at": "2016-11-05T10:15:26.300Z",
      "reset-digest": null,
      "reset-sent-at": null,
    },
    "relationships": {
      "microposts": {
        "links": {
          "related": "/api/v1/microposts?user_id=1"
        }
      },
      "followers": {
        "links": {
          "related": "/api/v1/users/1/followers"
        }
      },
      "followings": {
        "links": {
          "related": "/api/v1/users/1/followings"
        }
      }
    }
  }
}
```
the user_serializer.rb
```
module Api
  module V1

    class UserSerializer < ::ActiveModel::Serializer
      attributes(*User.attribute_names.map(&:to_sym))

      has_many :microposts do
        include_data(false)
        link(:related) {api_v1_microposts_path(user_id: object.id)}
      end

      has_many :followers do
        include_data(false)
        link(:related) {api_v1_user_followers_path(user_id: object.id)}
      end

      has_many :followings, key: :followings do
        include_data(false)
        link(:related) {api_v1_user_followings_path(user_id: object.id)}
      end
    end
  end
end

```
and user_controller.rb
```
module Api
  module V1
    class UsersController < BaseController
      def show
        user = User.find(params[:id])

        render json: user
      end
    end
  end
end

```

**Comment by sadmanahmed** [comment]
How the serialization call will happen ?

**Comment by wasifhossain** [comment]
provide `adapter: :json_api` option to the `render` method

**Comment by sadmanahmed** [comment]
something like this?
```
    def show
        user = User.find(params[:id])

        render adapter: :json_api, json: user
    end
```

**Comment by wasifhossain** [comment]
would work. but `json` option looks prettier if placed first
```rb
render json: user, adapter: :json_api
```

**Comment by sadmanahmed** [comment]
it worked vaia, desirable output  from this in json came https://github.com/ormprog/rails_ama/issues/47#issuecomment-615392977
