### ISSUE TITLE
how to make POST request to /api/v1/sessions using Postman

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#50]
Reference: https://github.com/vasilakisfil/rails5_api_tutorial

#### sessions_controller.rb
```rb
module Api
  module V1
    class SessionsController < BaseController
    def create
      if @user
        render(
          json: @user,
          status: 201,
          include: [:user],
          scope: @user,
          adapter: :json_api
        )
      else
        return api_error(status: 401, errors: 'Wrong password or username')
      end
    end

    private
      def create_params
        normalized_params.permit(:email, :password)
      end

      def load_resource
        @user = User.find_by(
          email: create_params[:email]
        )&.authenticate(create_params[:password])
      end

      def normalized_params
        ActionController::Parameters.new(
           ActiveModelSerializers::Deserialization.jsonapi_parse(params)
        )
      end
    end
  end
end
```

#### session_serialization.rb
```rb
module Api
  module V1
    class SessionSerializer < BaseSerializer
      type :session

      attributes :email, :token, :user_id

      has_one :user do
        link(:self) {api_v1_user_path(object.id)}
        link(:related) {api_v1_user_path(object.id)}

        object
      end

      def user
        object
      end

      def user_id
        object.id
      end

      def token
        object.token
      end

      def email
        object.email
      end
    end
  end
end
```

#### expected output
```json
{
  "data": {
    "id": "1",
    "type": "session",
    "attributes": {
      "email": "example@railstutorial.org",
      "token": "f42f5ccee3689209e7ca8e4f9bd830e2",
      "user-id": 1
    },
    "relationships": {
      "user": {
        "data": {
          "id": "1",
          "type": "users"
        },
        "links": {
          "self": "/api/v1/users/1",
          "related": "/api/v1/users/1"
        }
      }
    }
  },
  "included": [
    {
      "id": "1",
      "type": "users",
      "attributes": {
        "name": "Example User",
        "email": "example@railstutorial.org",
        "created-at": "2016-11-05T10:15:26Z",
        "updated-at": "2016-11-19T21:30:10Z",
        "password-digest": "$2a$10$or7HFYm/H07/uE79wDae3uXMmHOX3BvRKdgedPJ1SPceiMA40V25O",
        "remember-digest": null,
        "admin": true,
        "activation-digest": "$2a$10$X5IeDtGZPuZQEVQ.ZiUP4eUzfw9M9Pag/nR.0ONiXwAAp3w98iAuC",
        "activated": true,
        "activated-at": "2016-11-05T10:15:26.300Z",
        "reset-digest": null,
        "reset-sent-at": null,
        "token": "f42f5ccee3689209e7ca8e4f9bd830e2",
        "microposts-count": 99,
        "followers-count": 37,
        "followings-count": 48,
        "following-state": false,
        "follower-state": false
      },
      "relationships": {
        "microposts": {
          "links": {
            "related": "/api/v1/microposts?user_id=1"
          }
        },
        "followers": {
          "links": {
            "related": "/api/v1/users/1/followers"
          }
        },
        "followings": {
          "links": {
            "related": "/api/v1/users/1/followings"
          }
        }
      }
    }
  ]
}
```

**How to make a POST request to the endpoint?**

**Comment by wasifhossain** [comment]
please create a new issue with your 2nd question

**Comment by sadmanahmed** [comment]
Created
> please create a new issue with your 2nd question

**Comment by wasifhossain** [comment]
oh i think i screwed up with what you are asking for. to tell if the controller/serializer is defined properly, i have to know how do you want these to behave.

tbh, your question seems to be very broad in scope. please take your time to post issues with your exact intent. thanks

**Comment by sadmanahmed** [comment]
the code is okay(from the github) but as you have changed the syntax (In option 1 (module api module v1 ......)) that's why asking for the syntax..

**Comment by wasifhossain** [comment]
the nested namespace looks good. but that does not necessarily mean that its defined the way that should give you the desired output. you have to check if you are getting the desired output and if not, work on fixing the issue

**Comment by sadmanahmed** [comment]
Confused actually about the output....

**Comment by wasifhossain** [comment]
can you just share the link which you are probably trying to follow and got stuck over here

**Comment by sadmanahmed** [comment]
Currently Following this repo....
https://github.com/vasilakisfil/rails5_api_tutorial?fbclid=IwAR1vCSKKMa-dDHwR1wLACyEaDAIO4pcTqzTo5elajtX6VXnABmTlimOGJfY

**Comment by wasifhossain** [comment]
i see. i think you should better try out the codes as given in the tutorial as-is and only post any issues like any exceptions or errors that rails throws at you.

you may also ask with some code to know about how it works.

but, tbh, issues like this OP does not look like a good candidate to be one, as I don't see any errors that you are receiving, nor do I see any questions clearly what you are trying to understand

**Comment by wasifhossain** [comment]
i think we have got the question for this issue like this:

you have the controller and serializer that look like in the OP. how to get the json that matches the OP.

please correct me if I got it right

**Comment by wasifhossain** [comment]
can we see how does the `BaseSerializer` look like

**Comment by wasifhossain** [comment]
after taking another look at the OP, I think you just need to make the request properly to get that json output

**Comment by wasifhossain** [comment]
POSTMAN request to make a successful POST request with a json body
![image](https://user-images.githubusercontent.com/1168927/79703630-be8ce500-82ce-11ea-9e96-1b4ba612057f.png)

**Comment by wasifhossain** [comment]
- raw HTTP request
```
POST /api/v1/sessions HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
	"data": {
		"type": "session",
		"attributes": {
			"email": "USE-EXISTING-EMAIL-ADDRESS-WITH-WHICH-YOU-WANT-TO-LOGIN",
			"password": "USE-PASSWORD-FOR-THE-ABOVE-EMAIL"
		}
	}
}
```

- CURL request
```
curl --location --request POST 'http://localhost:3000/api/v1/sessions' \
--header 'Content-Type: application/json' \
--data-raw '{
	"data": {
		"type": "session",
		"attributes": {
			"email": "USE-EXISTING-EMAIL-ADDRESS-WITH-WHICH-YOU-WANT-TO-LOGIN",
			"password": "USE-PASSWORD-FOR-THE-ABOVE-EMAIL"
		}
	}
}'
```

- POSTMAN request
![image](https://user-images.githubusercontent.com/1168927/79703630-be8ce500-82ce-11ea-9e96-1b4ba612057f.png)

**Comment by wasifhossain** [comment]
while following the article from OP, I tried to build the request for you, so that you could run it without any other modification. but unfortunately you are trying something totally different :disappointed: 

https://github.com/ormprog/rails_ama/issues/54#issuecomment-616715829
https://github.com/ormprog/rails_ama/issues/54#issuecomment-616720100

**Comment by wasifhossain** [comment]
you can ask me why I built the request that way. but without getting the idea properly, trying something arbitrary, to be honest, does not make any sense

**Comment by sadmanahmed** [comment]
Ah I didn't make any modification. I just ran https://github.com/ormprog/rails_ama/issues/50#issue-602279853 to see what is actually going on. That's why I create the issue to ask whether it is right or wrong.
> while following the article from OP, I tried to build the request for you, so that you could run it without any other modification. but unfortunately you are trying something totally different 
> 
> [#54 (comment)](https://github.com/ormprog/rails_ama/issues/54#issuecomment-616715829)
> [#54 (comment)](https://github.com/ormprog/rails_ama/issues/54#issuecomment-616720100)

**Comment by wasifhossain** [comment]
can you share what did you get after following https://github.com/ormprog/rails_ama/issues/50#issuecomment-616250711

please share image from postman

**Comment by sadmanahmed** [comment]
what is the Key in the header for the value > Content-Type: application/json?

**Comment by wasifhossain** [comment]
you don't need to set it by hand. when you set the data type as JSON in the `Body` tab, it automatically sets a header like this: `Content-Type: application/json`

**Comment by wasifhossain** [comment]
fyi, `Content-Type: application/json` is interpreted as: `key: value`

i.e. key is `Content-Type` and value is `application/json`

**Comment by sadmanahmed** [comment]
```
{
    "errors": [
        {
            "status": 401,
            "title": "Wrong password or username",
            "detail": "Wrong password or username",
            "source": {
                "pointer": "data"
            }
        }
    ]
}
```
![ss](https://user-images.githubusercontent.com/19534210/79785910-76210600-8366-11ea-9763-e4c7fe758019.png)


Server output
```
Started POST "/api/v1/sessions" for ::1 at 2020-04-21 00:21:31 +0600
Processing by Api::V1::SessionsController#create as */*
  Parameters: {"data"=>{"type"=>"session", "attributes"=>{"email"=>"abirssc7@gmail.com", "password"=>"[FILTERED]"}}, "session"=>{"data"=>{"type"=>"session", "attributes"=>{"email"=>"abirssc7@gmail.com", "password"=>"[FILTERED]"}}}}
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.26ms)
Completed 401 Unauthorized in 3ms (Views: 1.4ms | ActiveRecord: 0.0ms | Allocations: 468)

```

**Comment by wasifhossain** [comment]
can you check in rails console what do you get by running
```rb
User.find_by(email: 'the email in the above image').authenticate('password that you used in the above image')
```

**Comment by sadmanahmed** [comment]
```
[2] pry(main)> User.find_by(email: 'abirssc7@gmail.com').authenticate('abir1234')
  User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
=> #<User:0x00007f482420cab0
 id: 1,
 name: "Abir",
 email: "abirssc7@gmail.com",
 created_at: Thu, 26 Mar 2020 17:16:38 UTC +00:00,
 updated_at: Fri, 17 Apr 2020 21:41:31 UTC +00:00,
 password_digest: [FILTERED],
 remember_digest: nil,
 admin: true,
 activation_digest: "$2a$12$/Y3zRUi1gr9GXSCBKUw9Oet5o8z6T6.tL5e09g21TKSodQkxe.xoa",
 activated: true,
 activated_at: Thu, 26 Mar 2020 17:16:37 UTC +00:00,
 reset_digest: nil,
 reset_sent_at: nil,
 token: "5cb13288cd629e9cdf72c167f3a4d750">

```

**Comment by wasifhossain** [comment]
so you have the user in db, but the sessions controller could not find it. debug time!

lets open the sessions_controller file and put `binding.pry` in the 1st line of `load_resource` method. then make the same request from postman and check if `rails server` process stops on binding.pry

**Comment by sadmanahmed** [comment]
right?
```
def load_resource
        binding.pry
        @user = User.find_by(
          email: create_params[:email]
        )&.authenticate(create_params[:password])
      end
```

**Comment by sadmanahmed** [comment]
Same output as before
```
Started POST "/api/v1/sessions" for ::1 at 2020-04-21 00:43:46 +0600
Processing by Api::V1::SessionsController#create as */*
  Parameters: {"data"=>{"type"=>"session", "attributes"=>{"email"=>"abirssc7@gmail.com", "password"=>"[FILTERED]"}}, "session"=>{"data"=>{"type"=>"session", "attributes"=>{"email"=>"abirssc7@gmail.com", "password"=>"[FILTERED]"}}}}
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.27ms)
Completed 401 Unauthorized in 4ms (Views: 2.8ms | ActiveRecord: 0.0ms | Allocations: 3938)
```

**Comment by wasifhossain** [comment]
which confirms the `load_resource` method is not called, which is required to make the endpoint work

**Comment by sadmanahmed** [comment]
adding this
```
before_action :load_resource
```

**Comment by sadmanahmed** [comment]
```
From: /home/abir/environment/sample_app/app/controllers/api/v1/sessions_controller.rb @ line 27 Api::V1::SessionsController#load_resource:

    25: def load_resource
    26:   binding.pry
 => 27:   @user = User.find_by(
    28:     email: create_params[:email]
    29:   )&.authenticate(create_params[:password])
    30: end

[1] pry(#<Api::V1::SessionsController>)> ~
[1] pry(#<Api::V1::SessionsController>)* 
[1] pry(#<Api::V1::SessionsController>)* 
[1] pry(#<Api::V1::SessionsController>)* 

```

**Comment by wasifhossain** [comment]
great! you can remove binding.pry and make another request from postman to see what result do you get now

**Comment by wasifhossain** [comment]
> ```
> From: /home/abir/environment/sample_app/app/controllers/api/v1/sessions_controller.rb @ line 27 Api::V1::SessionsController#load_resource:
> 
>     25: def load_resource
>     26:   binding.pry
>  => 27:   @user = User.find_by(
>     28:     email: create_params[:email]
>     29:   )&.authenticate(create_params[:password])
>     30: end
> 
> [1] pry(#<Api::V1::SessionsController>)> ~
> [1] pry(#<Api::V1::SessionsController>)* 
> [1] pry(#<Api::V1::SessionsController>)* 
> [1] pry(#<Api::V1::SessionsController>)* 
> ```

press `ctrl+d` to quit pry

**Comment by sadmanahmed** [comment]
how to end the input method in the output ? ctrl+d?

**Comment by sadmanahmed** [comment]
okay I get an output
```
{
    "data": {
        "id": "1",
        "type": "users",
        "attributes": {
            "name": "Abir",
            "email": "abirssc7@gmail.com",
            "created-at": "2020-03-26T17:16:38.166Z",
            "updated-at": "2020-04-17T21:41:31.696Z",
            "password-digest": "$2a$12$XmlVaxjArDUCFeOWjOGYWORCEcfCW3.GBMarZrsLCh1PdXeNRKHS2",
            "remember-digest": null,
            "admin": true,
            "activation-digest": "$2a$12$/Y3zRUi1gr9GXSCBKUw9Oet5o8z6T6.tL5e09g21TKSodQkxe.xoa",
            "activated": true,
            "activated-at": "2020-03-26T17:16:37.811Z",
            "reset-digest": null,
            "reset-sent-at": null,
            "token": "5cb13288cd629e9cdf72c167f3a4d750"
        },
        "relationships": {
            "microposts": {
                "links": {
                    "related": "/api/v1/microposts?user_id=1"
                }
            },
            "followers": {
                "links": {
                    "related": "/api/v1/users/1/followers"
                }
            },
            "followings": {
                "links": {
                    "related": "/api/v1/users/1/followings"
                }
            }
        }
    }
}
```

**Comment by wasifhossain** [comment]
can you share postman image

**Comment by wasifhossain** [comment]
and the server log

**Comment by sadmanahmed** [comment]
```
Started POST "/api/v1/sessions" for ::1 at 2020-04-21 00:52:23 +0600
Processing by Api::V1::SessionsController#create as */*
  Parameters: {"data"=>{"type"=>"session", "attributes"=>{"email"=>"abirssc7@gmail.com", "password"=>"[FILTERED]"}}, "session"=>{"data"=>{"type"=>"session", "attributes"=>{"email"=>"abirssc7@gmail.com", "password"=>"[FILTERED]"}}}}
  User Load (4.5ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/sessions_controller.rb:27:in `load_resource'
[active_model_serializers] Rendered Api::V1::UserSerializer with ActiveModelSerializers::Adapter::JsonApi (2.3ms)
Completed 201 Created in 436ms (Views: 6.5ms | ActiveRecord: 13.7ms | Allocations: 16098)

```

**Comment by sadmanahmed** [comment]
![ss](https://user-images.githubusercontent.com/19534210/79788806-095c3a80-836b-11ea-9910-81f4b0455639.png)

**Comment by wasifhossain** [comment]
can you share Api::V1::BaseSerializer class

**Comment by wasifhossain** [comment]
we identified the issue. the user is looked up successfully but its using the UserSerializer despite SessionSerializer

**Comment by sadmanahmed** [comment]
```
module Api
  module v1

    class BaseSerializer < ActiveModel::Serializer
      include Rails.application.routes.url_helpers

      def created_at
        object.created_at.to_datetime.in_time_zone('UTC').iso8601 if object.created_at
      end

      def updated_at
        object.updated_at.to_datetime.in_time_zone('UTC').iso8601 if object.updated_at
      end

      def reset_sent_at
        object.published_at.to_datetime.in_time_zone('UTC').iso8601 if object.reset_sent_at
      end
    end
  end
end

```

**Comment by sadmanahmed** [comment]
And what can be the possible solution?
> we identified the issue. the user is looked up successfully but its using the UserSerializer despite SessionSerializer

**Comment by wasifhossain** [comment]
can you share SessionsController too

**Comment by sadmanahmed** [comment]
```
module Api
  module V1

    class SessionsController < BaseController
    before_action :load_resource
    def create
      if @user
        render(
          json: @user,
          status: 201,
          include: [:user],
          scope: @user,
          adapter: :json_api
        )
      else
        return api_error(status: 401, errors: 'Wrong password or username')
      end
    end

    private
      def create_params
        normalized_params.permit(:email, :password)
      end

      def load_resource

        @user = User.find_by(
          email: create_params[:email]
        )&.authenticate(create_params[:password])
      end

      def normalized_params
        ActionController::Parameters.new(
           ActiveModelSerializers::Deserialization.jsonapi_parse(params)
        )
      end
    end
  end
end

```

**Comment by wasifhossain** [comment]
got it! the `render` method in the `create` action is missing the serializer option: `serializer: SessionSerializer`

(as the `SessionsController` and `SessionSerializer` are both nested under `Api::V1` namespace, so you can skip `Api::V1::`  while mentioning `SessionSerializer`)

**Comment by sadmanahmed** [comment]
so I should add **serializer: SessionSerializer** in the render,right?

**Comment by wasifhossain** [comment]
> so I should add **serializer: SessionSerializer** in the render,right?

better you share the updated code whatever you understand from my post, rather than repeating my post :)

**Comment by sadmanahmed** [comment]
```
module Api
  module V1

    class SessionsController < BaseController
    before_action :load_resource
    def create
      if @user
        render(
          json: @user,
          status: 201,
          include: [:user],
          scope: @user,
          serializer: SessionSerializer,

          adapter: :json_api
        )
      else
        return api_error(status: 401, errors: 'Wrong password or username')
      end
    end

    private
      def create_params
        normalized_params.permit(:email, :password)
      end

      def load_resource

        @user = User.find_by(
          email: create_params[:email]
        )&.authenticate(create_params[:password])
      end

      def normalized_params
        ActionController::Parameters.new(
           ActiveModelSerializers::Deserialization.jsonapi_parse(params)
        )
      end
    end
  end
end

```

**Comment by wasifhossain** [comment]
now lets see what response do you get after postman request

**Comment by sadmanahmed** [comment]
server result
```
Started POST "/api/v1/sessions" for ::1 at 2020-04-21 02:03:42 +0600
Processing by Api::V1::SessionsController#create as */*
  Parameters: {"data"=>{"type"=>"session", "attributes"=>{"email"=>"abirssc7@gmail.com", "password"=>"[FILTERED]"}}, "session"=>{"data"=>{"type"=>"session", "attributes"=>{"email"=>"abirssc7@gmail.com", "password"=>"[FILTERED]"}}}}
  User Load (1.4ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/sessions_controller.rb:29:in `load_resource'
[active_model_serializers] Rendered Api::V1::SessionSerializer with ActiveModelSerializers::Adapter::JsonApi (2.15ms)
Completed 201 Created in 381ms (Views: 3.0ms | ActiveRecord: 1.4ms | Allocations: 2875)

```

Json output
```
{
    "data": {
        "id": "1",
        "type": "session",
        "attributes": {
            "email": "abirssc7@gmail.com",
            "token": "5cb13288cd629e9cdf72c167f3a4d750",
            "user-id": 1
        },
        "relationships": {
            "user": {
                "data": {
                    "id": "1",
                    "type": "users"
                },
                "links": {
                    "self": "/api/v1/users/1",
                    "related": "/api/v1/users/1"
                }
            }
        }
    },
    "included": [
        {
            "id": "1",
            "type": "users",
            "attributes": {
                "name": "Abir",
                "email": "abirssc7@gmail.com",
                "created-at": "2020-03-26T17:16:38.166Z",
                "updated-at": "2020-04-17T21:41:31.696Z",
                "password-digest": "$2a$12$XmlVaxjArDUCFeOWjOGYWORCEcfCW3.GBMarZrsLCh1PdXeNRKHS2",
                "remember-digest": null,
                "admin": true,
                "activation-digest": "$2a$12$/Y3zRUi1gr9GXSCBKUw9Oet5o8z6T6.tL5e09g21TKSodQkxe.xoa",
                "activated": true,
                "activated-at": "2020-03-26T17:16:37.811Z",
                "reset-digest": null,
                "reset-sent-at": null,
                "token": "5cb13288cd629e9cdf72c167f3a4d750"
            },
            "relationships": {
                "microposts": {
                    "links": {
                        "related": "/api/v1/microposts?user_id=1"
                    }
                },
                "followers": {
                    "links": {
                        "related": "/api/v1/users/1/followers"
                    }
                },
                "followings": {
                    "links": {
                        "related": "/api/v1/users/1/followings"
                    }
                }
            }
        }
    ]
}
```

**Comment by wasifhossain** [comment]
you got the desired json at last :+1:

**Comment by sadmanahmed** [comment]
Seems like the expected one

**Comment by wasifhossain** [comment]
@sadmanahmed  as you might have seen that how much time it took us to understand your question properly. once its done, we got the solution in short time. so its really important how do we ask questions on the internet; if we can ask the right question, the solution should be very quick in most cases.

to keep the chat history clean, I have cleared up some comments that does not help too much to figure out the actual issue. I have also updated the OP that you may take a 2nd look to get an idea for your future posts.

let's keep learning :+1:

**Comment by sadmanahmed** [comment]
POSTMAN and API is totally a newthing that's why maybe the questioning was in a wrong approach.. But hopefully this issue will help in the future one's...

**Comment by wasifhossain** [comment]
in coming days, we will also learn about some other tools that we can use to make http requests, besides Postman, specially the **ruby gems**. the most I like to use are:

**HTTPX**: https://gitlab.com/honeyryderchuck/httpx
**HTTP.rb**: https://github.com/httprb/http
