### ISSUE TITLE
GET /api/v1/users with HTTP Token Authentication

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#55]
Reference: https://github.com/vasilakisfil/rails5_api_tutorial

**Before everything: I doubt maybe the authentication is making any problem**
For this get request
```
GET /api/v1/users HTTP/1.1 
User-Agent: MyClient/1.0.0 
Accept: application/vnd.api+json
```
(I just write down GET: **http://localhost:3000/api/v1/users**. Do I need to setup other lines? if then where)

**expected output**
```
HTTP/1.1 200 OK
{  
  "data":[  
    {  
      "id":"108",
      "type":"users",
      "attributes":{  
        "name":"Filippos Vasilakis",
        "email":"filippos@email.com",
        "created-at":"2017-02-19T15:14:40Z",
        "microposts-count":0,
        "followers-count":0,
        "followings-count":0,
        "following-state":false,
        "follower-state":false
      },
      "relationships":{  
        "microposts":{  
          "links":{  
            "related":"/api/v1/microposts?user_id=7"
          }
        },
        "followers":{  
          "links":{  
            "related":"/api/v1/users/7/followers"
          }
        },
        "followings":{  
          "links":{  
            "related":"/api/v1/users/7/followings"
          }
        }
      }
    }
.
.
.
.
.
  ],
  "links":{  
    "self":"http://localhost:3000/api/v1/users?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1\u0026per_page=1",
    "next":"http://localhost:3000/api/v1/users?page%5Bnumber%5D=2\u0026page%5Bsize%5D=1\u0026per_page=1",
    "last":"http://localhost:3000/api/v1/users?page%5Bnumber%5D=105\u0026page%5Bsize%5D=1\u0026per_page=1"
  },
  "meta":{  
    "current-page":1,
    "next-page":2,
    "prev-page":null,
    "total-pages":105,
    "total-count":105
  }
}
```

**original output**:
```
{
    "data": [
        {
            "id": "1",
            "type": "users",
            "attributes": {
                "name": "Abir",
                "created-at": "2020-03-26T17:16:38Z"
            },
            "relationships": {
                "feed": {
                    "links": {
                        "related": "/api/v1/users/1/feed"
                    }
                },
                "microposts": {
                    "links": {
                        "related": "/api/v1/microposts?user_id=1"
                    }
                },
                "followers": {
                    "links": {
                        "related": "/api/v1/users/1/followers"
                    }
                },
                "followings": {
                    "links": {
                        "related": "/api/v1/users/1/followings"
                    }
                }
            }
        },
        .
.
.
.

        {
            "id": "25",
            "type": "users",
            "attributes": {
                "name": "Latrisha Luettgen",
                "created-at": "2020-03-26T17:16:54Z"
            },
            "relationships": {
                "feed": {
                    "links": {
                        "related": "/api/v1/users/25/feed"
                    }
                },
                "microposts": {
                    "links": {
                        "related": "/api/v1/microposts?user_id=25"
                    }
                },
                "followers": {
                    "links": {
                        "related": "/api/v1/users/25/followers"
                    }
                },
                "followings": {
                    "links": {
                        "related": "/api/v1/users/25/followings"
                    }
                }
            }
        }
    ],
    "links": {
        "self": "http://localhost:3000/api/v1/users?page%5Bnumber%5D=1&page%5Bsize%5D=25",
        "first": "http://localhost:3000/api/v1/users?page%5Bnumber%5D=1&page%5Bsize%5D=25",
        "prev": null,
        "next": "http://localhost:3000/api/v1/users?page%5Bnumber%5D=2&page%5Bsize%5D=25",
        "last": "http://localhost:3000/api/v1/users?page%5Bnumber%5D=4&page%5Bsize%5D=25"
    },
    "meta": {
        "current-page": 1,
        "next-page": 2,
        "prev-page": null,
        "total-pages": 4,
        "total-count": 100
    }
}
```

**user_controller.rb**:
```rb
module Api
  module V1
    class UsersController < BaseController
      before_action :load_resource
      #skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      before_action :authenticate_user, only: [:index, :show]

      def index
        auth_users = policy_scope(@users)

        render json: auth_users.collection,
          each_serializer: UserSerializer,
          fields: {user: auth_users.fields(params[:fields])},
          meta: meta_attributes(auth_users.collection),
          adapter: :json_api
      end

      def show
        auth_user = authorize_with_permissions(@user)

        render json: auth_user.record, serializer: UserSerializer,adapter: :json_api,
          fields: {user: auth_user.fields}
      end

      def create
        auth_user = authorize_with_permissions(@user)

        if @user.save && @user.send_activation_email(ember_url: true) && @user.activate
          render json: auth_user.record, serializer: UserSerializer,
            fields: {user: auth_user.fields}, status: 201, scope: @user , adapter: :json_api
        else
          invalid_resource!(@user.errors)
        end
      end

      def update
        auth_user = authorize_with_permissions(@user, :update?)

        if @user.update(update_params)
          render json: auth_user.record, serializer: UserSerializer , adapter: :json_api,
            fields: {user: auth_user.fields}
        else
          invalid_resource!(@user.errors)
        end
      end

      def destroy
        auth_user = authorize_with_permissions(@user, :destroy?)

        @user.destroy!

        render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
          fields: {user: auth_user.fields}
      end

      def activate
        auth_user = authorize_with_permissions(@user, :activate?)

        if @user.authenticated?(:activation, params[:token])
          render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
            fields: {user: auth_user.fields}, status: 200, scope: @user
        else
          not_found!
        end
      end

      private
        def load_resource
          case params[:action].to_sym
          when :index
            @users = paginate(apply_filters(User.all, params))
          when :create
            @user = User.new(create_params)
          when :show, :update, :destroy
            @user = User.find(params[:id])
          when :activate
            @user = User.find_by!(email: params[:email])
          end
        end

        def create_params
          normalized_params.permit(
            :email, :password, :password_confirmation, :name
          )
        end
        def update_params
          create_params
        end

        def normalized_params
          ActionController::Parameters.new(
             ActiveModelSerializers::Deserialization.jsonapi_parse(params)
          )
        end
    end
  end
end
```

**base_controller.rb**:
```rb
module Api
  module V1

    class BaseController < ActionController::API
      include Pundit
      include ActiveHashRelation
      include CustomErrors

      before_action :authenticate_user!, except: :options

      rescue_from ActionController::ParameterMissing do
        api_error(status: 400, errors: 'Invalid parameters')
      end

      rescue_from Pundit::NotAuthorizedError do
        unauthorized!
      end

      rescue_from ActiveRecord::RecordNotFound do
        api_error(status: 404, errors: 'Resource not found!')
      end

      rescue_from UnauthenticatedError do
        unauthenticated!
      end

      protected
        def current_user
          @current_user
        end

        def authenticate_user
          token, options = ActionController::HttpAuthentication::Token.token_and_options(
            request
          )

          return nil unless token && options.is_a?(Hash)

          user = User.find_by(email: options['email'])
          if user && ActiveSupport::SecurityUtils.secure_compare(user.token, token)
            @current_user = user
          else
            return nil
          end
        end

        def authenticate_user!
          authenticate_user or raise UnauthenticatedError
        end

        def unauthorized!
          unless Rails.env.production? || Rails.env.test?
            Rails.logger.warn { "unauthorized for: #{current_user.try(:id)}" }
          end

          api_error(status: 403, errors: 'Not Authorized')
        end

        def unauthenticated!
          unless Rails.env.production? || Rails.env.test?
            Rails.logger.warn { "Unauthenticated user not granted access" }
          end

          api_error(status: 401, errors: 'Not Authenticated')
        end

        def not_found!
          Rails.logger.warn { "not_found for: #{current_user.try(:id)}" }

          api_error(status: 404, errors: 'Resource not found')
        end

        def invalid_resource!(errors = [])
          api_error(status: 422, errors: errors)
        end

        def paginate(resource)
          default_per_page = Rails.application.secrets.default_per_page || 25

          resource.paginate({
            page: params[:page] || 1, per_page: params[:per_page] || default_per_page
          })
        end

        #expects paginated resource!
        def meta_attributes(resource, extra_meta = {})

          meta = {
            current_page: resource.current_page,
            next_page: resource.next_page,
            prev_page: resource.previous_page,
            total_pages: resource.total_pages,
            total_count: resource.total_entries
          }.merge(extra_meta)

          return meta
        end

        def api_error(status: 500, errors: [])
          puts errors.full_messages if errors.respond_to?(:full_messages)

          render json: ErrorSerializer.new(status, errors).as_json,
            status: status,
            adapter: :json_api
        end
    end
  end
end
```

**user_serializer.rb**:
```rb
module Api
  module V1
    class UserSerializer < BaseSerializer
      attributes(*User.attribute_names.map(&:to_sym))

      attribute :following_state
      attribute :follower_state

      def following_state
        Relationship.where(
          follower_id: current_user.id,
          followed_id: object.id
        ).exists?
      end

      def follower_state
        Relationship.where(
          follower_id: object.id,
          followed_id: current_user.id
        ).exists?
      end

      has_one :feed, serializer: MicropostSerializer do
        include_data(false)
        link(:related) {api_v1_user_feed_path(user_id: object.id)}
      end

      has_many :microposts, serializer: MicropostSerializer do
        include_data(false)
        link(:related) {api_v1_microposts_path(user_id: object.id)}
      end

      has_many :followers, serializer: UserSerializer do
        include_data(false)
        link(:related) {api_v1_user_followers_path(user_id: object.id)}
      end

      has_many :followings, key: :followings, serializer: UserSerializer do
        include_data(false)
        link(:related) {api_v1_user_followings_path(user_id: object.id)}
      end
    end
  end
end
```

**server log**:
```
Started GET "/api/v1/users" for ::1 at 2020-04-23 04:00:03 +0600
Processing by Api::V1::UsersController#index as */*
  User Load (5.1ms)  SELECT "users".* FROM "users" WHERE "users"."email" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/controllers/api/v1/base_controller.rb:39:in `authenticate_user'
   (1.8ms)  SELECT COUNT(*) FROM "users"
  ↳ app/controllers/api/v1/base_controller.rb:90:in `meta_attributes'
  User Load (0.7ms)  SELECT "users".* FROM "users" LIMIT $1 OFFSET $2  [["LIMIT", 25], ["OFFSET", 0]]
  ↳ app/controllers/api/v1/users_controller.rb:11:in `index'
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::JsonApi (43.92ms)
Completed 200 OK in 61ms (Views: 47.6ms | ActiveRecord: 7.6ms | Allocations: 21573)
```

**Comment by sadmanahmed** [comment]
But this is the postman outcome. Is this something related with the authenticity?
```
{
    "data": [
        {
            "id": "1",
            "type": "users",
            "attributes": {
                "name": "Abir",
                "created-at": "2020-03-26T17:16:38Z"
            },
            "relationships": {
                "feed": {
                    "links": {
                        "related": "/api/v1/users/1/feed"
                    }
                },
                "microposts": {
                    "links": {
                        "related": "/api/v1/microposts?user_id=1"
                    }
                },
                "followers": {
                    "links": {
                        "related": "/api/v1/users/1/followers"
                    }
                },
                "followings": {
                    "links": {
                        "related": "/api/v1/users/1/followings"
                    }
                }
            }
        },
        .
.
.
.

        {
            "id": "25",
            "type": "users",
            "attributes": {
                "name": "Latrisha Luettgen",
                "created-at": "2020-03-26T17:16:54Z"
            },
            "relationships": {
                "feed": {
                    "links": {
                        "related": "/api/v1/users/25/feed"
                    }
                },
                "microposts": {
                    "links": {
                        "related": "/api/v1/microposts?user_id=25"
                    }
                },
                "followers": {
                    "links": {
                        "related": "/api/v1/users/25/followers"
                    }
                },
                "followings": {
                    "links": {
                        "related": "/api/v1/users/25/followings"
                    }
                }
            }
        }
    ],
    "links": {
        "self": "http://localhost:3000/api/v1/users?page%5Bnumber%5D=1&page%5Bsize%5D=25",
        "first": "http://localhost:3000/api/v1/users?page%5Bnumber%5D=1&page%5Bsize%5D=25",
        "prev": null,
        "next": "http://localhost:3000/api/v1/users?page%5Bnumber%5D=2&page%5Bsize%5D=25",
        "last": "http://localhost:3000/api/v1/users?page%5Bnumber%5D=4&page%5Bsize%5D=25"
    },
    "meta": {
        "current-page": 1,
        "next-page": 2,
        "prev-page": null,
        "total-pages": 4,
        "total-count": 100
    }
}
```

**Comment by wasifhossain** [comment]
i think you need to set the `Authorization` header in this way: https://github.com/ormprog/rails_ama/issues/53#issuecomment-616235655

first you have to make a call to sessions endpoint to obtain the token, and then use it in subsequent api calls like users endpoint

**Comment by sadmanahmed** [comment]
no change in the output
![ss](https://user-images.githubusercontent.com/19534210/80038016-8841a680-8516-11ea-9fd5-7f0a22c77d7e.png)

**Comment by wasifhossain** [comment]
server log pls

**Comment by sadmanahmed** [comment]
server log
```
Started GET "/api/v1/users" for ::1 at 2020-04-23 04:00:03 +0600
Processing by Api::V1::UsersController#index as */*
  User Load (5.1ms)  SELECT "users".* FROM "users" WHERE "users"."email" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/controllers/api/v1/base_controller.rb:39:in `authenticate_user'
   (1.8ms)  SELECT COUNT(*) FROM "users"
  ↳ app/controllers/api/v1/base_controller.rb:90:in `meta_attributes'
  User Load (0.7ms)  SELECT "users".* FROM "users" LIMIT $1 OFFSET $2  [["LIMIT", 25], ["OFFSET", 0]]
  ↳ app/controllers/api/v1/users_controller.rb:11:in `index'
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::JsonApi (43.92ms)
Completed 200 OK in 61ms (Views: 47.6ms | ActiveRecord: 7.6ms | Allocations: 21573)

```

**Comment by sadmanahmed** [comment]
I have add columns in the user to get this types of value
```
        "microposts-count":0,
        "followers-count":0,
        "followings-count":0,
        "following-state":false,
        "follower-state":false
```
but no change actually come up

**Comment by wasifhossain** [comment]
> I have add columns in the user to get this types of value
> 
> ```
>         "microposts-count":0,
>         "followers-count":0,
>         "followings-count":0,
>         "following-state":false,
>         "follower-state":false
> ```
> 
> but no change actually come up

is it part of the expected output?

**Comment by sadmanahmed** [comment]
![ss](https://user-images.githubusercontent.com/19534210/80040265-86c6ad00-851b-11ea-9643-774203347eb0.png)

output:
```
{
    "data": {
        "id": "1",
        "type": "session",
        "attributes": {
            "email": "abirssc7@gmail.com",
            "token": "5cb13288cd629e9cdf72c167f3a4d750",
            "user-id": 1
        },
        "relationships": {
            "user": {
                "data": {
                    "id": "1",
                    "type": "users"
                },
                "links": {
                    "self": "/api/v1/users/1",
                    "related": "/api/v1/users/1"
                }
            }
        }
    },
    "included": [
        {
            "id": "1",
            "type": "users",
            "attributes": {
                "name": "Abir",
                "email": "abirssc7@gmail.com",
                "created-at": "2020-03-26T17:16:38Z",
                "updated-at": "2020-04-17T21:41:31Z",
                "password-digest": "$2a$12$XmlVaxjArDUCFeOWjOGYWORCEcfCW3.GBMarZrsLCh1PdXeNRKHS2",
                "remember-digest": null,
                "admin": true,
                "activation-digest": "$2a$12$/Y3zRUi1gr9GXSCBKUw9Oet5o8z6T6.tL5e09g21TKSodQkxe.xoa",
                "activated": true,
                "activated-at": "2020-03-26T17:16:37.811Z",
                "reset-digest": null,
                "reset-sent-at": null,
                "token": "5cb13288cd629e9cdf72c167f3a4d750",
                "microposts-count": 0,
                "followers-count": 0,
                "followings-count": 0,
                "following-state": false,
                "follower-state": false
            },
            "relationships": {
                "feed": {
                    "links": {
                        "related": "/api/v1/users/1/feed"
                    }
                },
                "microposts": {
                    "links": {
                        "related": "/api/v1/microposts?user_id=1"
                    }
                },
                "followers": {
                    "links": {
                        "related": "/api/v1/users/1/followers"
                    }
                },
                "followings": {
                    "links": {
                        "related": "/api/v1/users/1/followings"
                    }
                }
            }
        }
    ]
}
```
You can see in the session we are getting them perfectly

**Comment by sadmanahmed** [comment]
> > I have add columns in the user to get this types of value
> > ```
> >         "microposts-count":0,
> >         "followers-count":0,
> >         "followings-count":0,
> >         "following-state":false,
> >         "follower-state":false
> > ```
> > 
> > 
> > but no change actually come up
> 
> is it part of the expected output?

YES

**Comment by wasifhossain** [comment]
but i can't see it. can you update the OP to include this so that I have better idea how this fits into the output json

**Comment by sadmanahmed** [comment]
https://github.com/ormprog/rails_ama/issues/55#issue-605080142 They are here from the begining(in the expected one)

**Comment by wasifhossain** [comment]
please include the user controller and serializer in the OP too

**Comment by sadmanahmed** [comment]
This is my outcome https://github.com/ormprog/rails_ama/issues/55#issuecomment-618045392

**Comment by sadmanahmed** [comment]
user_controller.rb
```
module Api
  module V1
    class UsersController < BaseController
      before_action :load_resource
      skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      before_action :authenticate_user, only: [:index, :show]

      def index
        auth_users = policy_scope(@users)

        render json: auth_users.collection,
          each_serializer: UserSerializer,
          fields: {user: auth_users.fields(params[:fields])},
          meta: meta_attributes(auth_users.collection),
          adapter: :json_api
      end

      def show
        auth_user = authorize_with_permissions(@user)

        render json: auth_user.record, serializer: UserSerializer,adapter: :json_api,
          fields: {user: auth_user.fields}
      end

      def create
        auth_user = authorize_with_permissions(@user)

        if @user.save && @user.send_activation_email(ember_url: true) && @user.activate
          render json: auth_user.record, serializer: UserSerializer,
            fields: {user: auth_user.fields}, status: 201, scope: @user , adapter: :json_api
        else
          invalid_resource!(@user.errors)
        end
      end

      def update
        auth_user = authorize_with_permissions(@user, :update?)

        if @user.update(update_params)
          render json: auth_user.record, serializer: UserSerializer , adapter: :json_api,
            fields: {user: auth_user.fields}
        else
          invalid_resource!(@user.errors)
        end
      end

      def destroy
        auth_user = authorize_with_permissions(@user, :destroy?)

        @user.destroy!

        render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
          fields: {user: auth_user.fields}
      end

      def activate
        auth_user = authorize_with_permissions(@user, :activate?)

        if @user.authenticated?(:activation, params[:token])
          render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
            fields: {user: auth_user.fields}, status: 200, scope: @user
        else
          not_found!
        end
      end

      private
        def load_resource
          case params[:action].to_sym
          when :index
            @users = paginate(apply_filters(User.all, params))
          when :create
            @user = User.new(create_params)
          when :show, :update, :destroy
            @user = User.find(params[:id])
          when :activate
            @user = User.find_by!(email: params[:email])
          end
        end

        def create_params
          normalized_params.permit(
            :email, :password, :password_confirmation, :name
          )
        end
        def update_params
          create_params
        end

        def normalized_params
          ActionController::Parameters.new(
             ActiveModelSerializers::Deserialization.jsonapi_parse(params)
          )
        end
    end
  end
end

```
user_serializer.rb
```
module Api
  module V1
    class UserSerializer < BaseSerializer
      attributes(*User.attribute_names.map(&:to_sym))

      attribute :following_state
      attribute :follower_state

      def following_state
        Relationship.where(
          follower_id: current_user.id,
          followed_id: object.id
        ).exists?
      end

      def follower_state
        Relationship.where(
          follower_id: object.id,
          followed_id: current_user.id
        ).exists?
      end

      has_one :feed, serializer: MicropostSerializer do
        include_data(false)
        link(:related) {api_v1_user_feed_path(user_id: object.id)}
      end

      has_many :microposts, serializer: MicropostSerializer do
        include_data(false)
        link(:related) {api_v1_microposts_path(user_id: object.id)}
      end

      has_many :followers, serializer: UserSerializer do
        include_data(false)
        link(:related) {api_v1_user_followers_path(user_id: object.id)}
      end

      has_many :followings, key: :followings, serializer: UserSerializer do
        include_data(false)
        link(:related) {api_v1_user_followings_path(user_id: object.id)}
      end
    end
  end
end

```

**Comment by wasifhossain** [comment]
the following lines are contradictory
```rb
      skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      before_action :authenticate_user, only: [:index, :show]
```

please decide whether do you want to authenticate `index` and `show` actions. then remove these names from `skip_before_action`

**Comment by wasifhossain** [comment]
also i think the method signature contains the bang `!` like `authenticate_user!`. in that case, let's fix it in `before_action` too

**Comment by sadmanahmed** [comment]
> the following lines are contradictory
> 
> ```ruby
>       skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
>       before_action :authenticate_user, only: [:index, :show]
> ```
> 
> please decide whether do you want to authenticate `index` and `show` actions. then remove these names from `skip_before_action`

what should be better here?
this one?
 ```
skip_before_action :authenticate_user, only: [ :create, :activate]
      before_action :authenticate_user, only: [:index, :show]
```

**Comment by sadmanahmed** [comment]
How is this gems?(heard It doesn’t require authentication.)
https://github.com/kollegorna/active_hash_relation

**Comment by wasifhossain** [comment]
if you want to authenticate some action, then you mention it in `only` option in `before_action`. and i think its always a good idea to protect some endpoints (actions) through requiring authentication; otherwise unauthenticated users would get your data

so i think all of the actions in all controllers should require authentication and you can do it easily by calling the method (that defines the authentication logic) in `before_action`

for your case: `before_action :authenticate_request!`, which would impose auth for all actions in that controller

its much better to use the above statement in the root controller, which I assume for your case is `Api::V1::BaseController`

as all controllers inherit from this base controller, every action defined in each controller would then require authentication to allow a request.

that might also require auth for `SessionsController#create`, which I think works different than other actions (accepts only email and password). so you need to tell the controller to skip requiring the method by `skip_before_action :authenticate_request!, only: :create` in that controller

**Comment by sadmanahmed** [comment]
what will be the method for `authenticate_request`?(Is it :authenticate_request or :authenticate_user? you are talking about)
Yes ,my root controller is Api::V1::BaseController

**Comment by sadmanahmed** [comment]
BaseController.rb
```
module Api
  module V1

    class BaseController < ActionController::API
      include Pundit
      include ActiveHashRelation
      include CustomErrors

      before_action :authenticate_user!, except: :options

      rescue_from ActionController::ParameterMissing do
        api_error(status: 400, errors: 'Invalid parameters')
      end

      rescue_from Pundit::NotAuthorizedError do
        unauthorized!
      end

      rescue_from ActiveRecord::RecordNotFound do
        api_error(status: 404, errors: 'Resource not found!')
      end

      rescue_from UnauthenticatedError do
        unauthenticated!
      end

      protected
        def current_user
          @current_user
        end

        def authenticate_user
          token, options = ActionController::HttpAuthentication::Token.token_and_options(
            request
          )

          return nil unless token && options.is_a?(Hash)

          user = User.find_by(email: options['email'])
          if user && ActiveSupport::SecurityUtils.secure_compare(user.token, token)
            @current_user = user
          else
            return nil
          end
        end

        def authenticate_user!
          authenticate_user or raise UnauthenticatedError
        end

        def unauthorized!
          unless Rails.env.production? || Rails.env.test?
            Rails.logger.warn { "unauthorized for: #{current_user.try(:id)}" }
          end

          api_error(status: 403, errors: 'Not Authorized')
        end

        def unauthenticated!
          unless Rails.env.production? || Rails.env.test?
            Rails.logger.warn { "Unauthenticated user not granted access" }
          end

          api_error(status: 401, errors: 'Not Authenticated')
        end

        def not_found!
          Rails.logger.warn { "not_found for: #{current_user.try(:id)}" }

          api_error(status: 404, errors: 'Resource not found')
        end

        def invalid_resource!(errors = [])
          api_error(status: 422, errors: errors)
        end

        def paginate(resource)
          default_per_page = Rails.application.secrets.default_per_page || 25

          resource.paginate({
            page: params[:page] || 1, per_page: params[:per_page] || default_per_page
          })
        end

        #expects paginated resource!
        def meta_attributes(resource, extra_meta = {})

          meta = {
            current_page: resource.current_page,
            next_page: resource.next_page,
            prev_page: resource.previous_page,
            total_pages: resource.total_pages,
            total_count: resource.total_entries
          }.merge(extra_meta)

          return meta
        end

        def api_error(status: 500, errors: [])
          puts errors.full_messages if errors.respond_to?(:full_messages)

          render json: ErrorSerializer.new(status, errors).as_json,
            status: status,
            adapter: :json_api
        end
    end
  end
end

```

**Comment by wasifhossain** [comment]
i see. `before_action :authenticate_user!` is already present in the root controller. then you probably can remove this statement from any child controller

the sessions controller might need to skip the method by using `skip_before_action`
```rb
skip_before_action :authenticate_user!
```

**Comment by wasifhossain** [comment]
a small refactoring:

you can rewrite the `meta_attributes` from
```rb
def meta_attributes(resource, extra_meta = {})
  meta = {
    current_page: resource.current_page,
    next_page: resource.next_page,
    prev_page: resource.previous_page,
    total_pages: resource.total_pages,
    total_count: resource.total_entries
  }.merge(extra_meta)

  return meta
end
```
to the following
```rb
def meta_attributes(resource, extra_meta = {})
  {
    current_page: resource.current_page,
    next_page: resource.next_page,
    prev_page: resource.previous_page,
    total_pages: resource.total_pages,
    total_count: resource.total_entries
  }.merge(extra_meta)
end
```

Ruby methods return the value of the last statement, so you can skip the `return` keyword when its in the last line of the method block.

**Comment by wasifhossain** [comment]
for some reason, the serializer is returning only these attributes
```
"attributes": {
    "name": "Abir",
    "created-at": "2020-03-26T17:16:38Z"
}
```
:thinking:

**Comment by wasifhossain** [comment]
can you put binding.pry in users#index like this way
```rb
def index
  auth_users = policy_scope(@users)

  binding.pry

  render json: auth_users.collection,
    each_serializer: UserSerializer,
    fields: {user: auth_users.fields(params[:fields])},
    meta: meta_attributes(auth_users.collection),
    adapter: :json_api
end
```
and share what do you see as output for the following statements
```rb
params[:fields]
auth_users.fields(params[:fields])
auth_users.fields
```

**Comment by sadmanahmed** [comment]
> i see. `before_action :authenticate_user!` is already present in the root controller. then you probably can remove this statement from any child controller
> 
> the sessions controller might need to skip the method by using `skip_before_action`
> 
> ```ruby
> skip_before_action :authenticate_user!
> ```

the user_controller.rb has also this. Should I comment out `skip_before_action` here?
```
before_action :load_resource
      skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      before_action :authenticate_user, only: [:index, :show]
```

**Comment by sadmanahmed** [comment]
> ```ruby
> params[:fields]
> ```

can you elaborate the last instructions? 
```
and share what do you see as output for the following statements

params[:fields]
auth_users.fields(params[:fields])
auth_users.fields
```

**Comment by wasifhossain** [comment]
> the user_controller.rb has also this. Should I comment out `skip_before_action` here?

I think thats what I meant by 
> then you probably can remove this statement from any child controller

**Comment by wasifhossain** [comment]
> > ```ruby
> > params[:fields]
> > ```
> 
> can you elaborate the last instructions?
> 
> ```
> and share what do you see as output for the following statements
> 
> params[:fields]
> auth_users.fields(params[:fields])
> auth_users.fields
> ```

when the `rails server` stops on binding.pry, run each of the above statements and share the output

**Comment by sadmanahmed** [comment]
Get localhost:3000/api/v1/users

```
pry(#<Api::V1::UsersController>)> params[:fields]
=> nil
[18] pry(#<Api::V1::UsersController>)> auth_users.fields(params[:fields])
=> [:id,
 :name,
 :created_at,
 :links,
 :microposts,
 :active_relationships,
 :passive_relationships,
 :followings,
 :followers,
 :feed]
[19] pry(#<Api::V1::UsersController>)> auth_users.fields
=> [:id,
 :name,
 :created_at,
 :links,
 :microposts,
 :active_relationships,
 :passive_relationships,
 :followings,
 :followers,
 :feed]
[20] pry(#<Api::V1::UsersController>)> 

```

**Comment by wasifhossain** [comment]
let me know what json it returns after making changes with `before_action` and `skip_before_action` callbacks

**Comment by sadmanahmed** [comment]
GET localhost:3000/api/v1/users
```
{
    "errors": [
        {
            "status": 401,
            "title": "Not Authenticated",
            "detail": "Not Authenticated",
            "source": {
                "pointer": "data"
            }
        }
    ]
}
```

server log
```
Started GET "/api/v1/users" for ::1 at 2020-04-23 14:36:58 +0600
Processing by Api::V1::UsersController#index as */*
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."email" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/controllers/api/v1/base_controller.rb:39:in `authenticate_user'
Unauthenticated user not granted access
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.2ms)
Completed 401 Unauthorized in 4ms (Views: 0.9ms | ActiveRecord: 0.6ms | Allocations: 1410)
```

**Comment by wasifhossain** [comment]
> ↳ app/controllers/api/v1/base_controller.rb:39:in `authenticate_user'

we need to debug the method. lets put binding.pry this way
```rb
def authenticate_user
  token, options = ActionController::HttpAuthentication::Token.token_and_options(
    request
  )

  binding.pry

  return nil unless token && options.is_a?(Hash)

  user = User.find_by(email: options['email'])
  if user && ActiveSupport::SecurityUtils.secure_compare(user.token, token)
    @current_user = user
  else
    return nil
  end
end
```
and from rails server, share the output for the following
- token
- options

**Comment by sadmanahmed** [comment]
current user_controller.rb
```
class UsersController < BaseController
      before_action :load_resource
      #skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      #before_action :authenticate_user, only: [:index, :show]
```

**Comment by sadmanahmed** [comment]
```
pry(#<Api::V1::UsersController>)> token
=> "email=abirssc7@gmail.com"
[4] pry(#<Api::V1::UsersController>)> options
=> {"token"=>"5cb13288cd629e9cdf72c167f3a4d750"}
[5] pry(#<Api::V1::UsersController>)> 

```

**Comment by wasifhossain** [comment]
oops! looks like the authorization header is set in wrong order, which is why its wrongly parsed.

i have updated my post in the other thread. you may take a look at https://github.com/ormprog/rails_ama/issues/53#issuecomment-616235655 and come back to fix it

once you are able to correctly set the Authorization header, you should get the desired result

**Comment by wasifhossain** [comment]
any updates?

**Comment by sadmanahmed** [comment]
Yes, now the GET: http://localhost:3000/api/v1/users is showing result perfectly.
