### ISSUE TITLE
Post /api/v1/users with HTTP Token Authentication

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#56]
**Post localhost:3000/api/v1/users**
**Input json**
```
{  
  "data":{  
    "type":"users",
    "attributes":{  
      "name": "Kenna ",
    "email": "abirssc12@gmail.com",
    "password": "12345678"
    
    }
  }
}
```

**server log**
```
Started POST "/api/v1/users" for ::1 at 2020-04-23 05:07:31 +0600
Processing by Api::V1::UsersController#create as */*
  Parameters: {"data"=>{"type"=>"users", "attributes"=>{"name"=>"Kenna ", "email"=>"abirssc12@gmail.com", "password"=>"[FILTERED]"}}, "user"=>{}}
   (0.4ms)  BEGIN
  ↳ app/models/user.rb:161:in `block in generate_hex'
  User Exists? (0.5ms)  SELECT 1 AS one FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "3d8e8c7c8fce739058ebceb5fc2ec82d"], ["LIMIT", 1]]
  ↳ app/models/user.rb:161:in `block in generate_hex'
  User Exists? (0.4ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc12@gmail.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:28:in `create'
  CACHE User Exists? (0.0ms)  SELECT 1 AS one FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "3d8e8c7c8fce739058ebceb5fc2ec82d"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:28:in `create'
  User Create (0.9ms)  INSERT INTO "users" ("name", "email", "created_at", "updated_at", "password_digest", "activation_digest", "token") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["name", "Kenna "], ["email", "abirssc12@gmail.com"], ["created_at", "2020-04-22 23:07:31.788115"], ["updated_at", "2020-04-22 23:07:31.788115"], ["password_digest", "$2a$12$M681OWW4sj5.uTNOuniw/usz/GRqhI6L.Ov.gTs2lINLIsyNr9L2q"], ["activation_digest", "$2a$12$M8ehmD7GgfT7osHwEzGL.ecb1brY/a/wQpPMXuYd0FSYVlBb6dUX6"], ["token", "3d8e8c7c8fce739058ebceb5fc2ec82d"]]
  ↳ app/controllers/api/v1/users_controller.rb:28:in `create'
   (18.6ms)  COMMIT
  ↳ app/controllers/api/v1/users_controller.rb:28:in `create'
Completed 500 Internal Server Error in 758ms (ActiveRecord: 20.8ms | Allocations: 5738)


  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/models/user.rb:85:in `send_activation_email'
app/controllers/api/v1/users_controller.rb:28:in `create'

```

**output json**

`ACTUALLY NO OUTPUT`
![ss](https://user-images.githubusercontent.com/19534210/80042447-d0fe5d00-8520-11ea-95f7-9aff8ac36288.png)

**Comment by wasifhossain** [comment]
the error message reports that `@user.send_activation_email(ember_url: true)` was called with 1 argument, when the method in the user model is defined with NO argument.

let's call it with NO arguments and see what you get afterwards

**Comment by sadmanahmed** [comment]
> the error message reports that `@user.send_activation_email(ember_url: true)` was called with 1 argument, when the method in the user model is defined with NO argument.
> 
> let's call it with NO arguments and see what you get afterwards

and how can I do that?

**Comment by wasifhossain** [comment]
just remove `(ember_url: true)` after `@user.send_activation_email`

**Comment by wasifhossain** [comment]
any updates?

**Comment by sadmanahmed** [comment]
new user created succesfully.
