### ISSUE TITLE
Delete /api/v1/users/25 with HTTP Token Authentication

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#57]
Delete : localhost:3000/api/v1/users/25

**SERVER LOG**
```
Started DELETE "/api/v1/users/25" for ::1 at 2020-04-23 05:11:57 +0600
Processing by Api::V1::UsersController#destroy as */*
  Parameters: {"id"=>"25"}
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."email" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/controllers/api/v1/base_controller.rb:39:in `authenticate_user'
Unauthenticated user not granted access
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.12ms)
Completed 401 Unauthorized in 3ms (Views: 0.6ms | ActiveRecord: 0.5ms | Allocations: 1415)

```
![ss](https://user-images.githubusercontent.com/19534210/80042524-1589f880-8521-11ea-803e-23fd56ad8d8f.png)

```
def authenticate_user
          token, options = ActionController::HttpAuthentication::Token.token_and_options(
            request
          )

          return nil unless token && options.is_a?(Hash)

          user = User.find_by(email: options['email'])
          if user && ActiveSupport::SecurityUtils.secure_compare(user.token, token)
            @current_user = user
          else
            return nil
          end
        end
```

```
 def authenticate_user!
          authenticate_user or raise UnauthenticatedError
        end
```

users_controller.rb
```
module Api
  module V1
    class UsersController < BaseController
      before_action :load_resource
      skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      before_action :authenticate_user, only: [:index, :show]

      def index
        auth_users = policy_scope(@users)
        
        render json: auth_users.collection,
          each_serializer: UserSerializer,
          fields: {user: auth_users.fields(params[:fields])},
          meta: meta_attributes(auth_users.collection),
          adapter: :json_api
      end

      def show
        auth_user = authorize_with_permissions(@user)

        render json: auth_user.record, serializer: UserSerializer,adapter: :json_api,
          fields: {user: auth_user.fields}
      end

      def create
        auth_user = authorize_with_permissions(@user)

        if @user.save && @user.send_activation_email(ember_url: true) && @user.activate
          render json: auth_user.record, serializer: UserSerializer,
            fields: {user: auth_user.fields}, status: 201, scope: @user , adapter: :json_api
        else
          invalid_resource!(@user.errors)
        end
      end

      def update
        auth_user = authorize_with_permissions(@user, :update?)

        if @user.update(update_params)
          render json: auth_user.record, serializer: UserSerializer , adapter: :json_api,
            fields: {user: auth_user.fields}
        else
          invalid_resource!(@user.errors)
        end
      end

      def destroy
        auth_user = authorize_with_permissions(@user, :destroy?)

        @user.destroy!

        render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
          fields: {user: auth_user.fields}
      end

      def activate
        auth_user = authorize_with_permissions(@user, :activate?)

        if @user.authenticated?(:activation, params[:token])
          render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
            fields: {user: auth_user.fields}, status: 200, scope: @user
        else
          not_found!
        end
      end

      private
        def load_resource
          case params[:action].to_sym
          when :index
            @users = paginate(apply_filters(User.all, params))
          when :create
            @user = User.new(create_params)
          when :show, :update, :destroy
            @user = User.find(params[:id])
          when :activate
            @user = User.find_by!(email: params[:email])
          end
        end

        def create_params
          normalized_params.permit(
            :email, :password, :password_confirmation, :name
          )
        end
        def update_params
          create_params
        end

        def normalized_params
          ActionController::Parameters.new(
             ActiveModelSerializers::Deserialization.jsonapi_parse(params)
          )
        end
    end
  end
end

```

**Comment by sadmanahmed** [comment]
401 | Unauthorized – You try to access a protected resource without providing authentication credentials or with wrong credentials

**Comment by wasifhossain** [comment]
can you share the following methods
- authenticate_user
- authenticate_user!

**Comment by sadmanahmed** [comment]
```
def authenticate_user
          token, options = ActionController::HttpAuthentication::Token.token_and_options(
            request
          )

          return nil unless token && options.is_a?(Hash)

          user = User.find_by(email: options['email'])
          if user && ActiveSupport::SecurityUtils.secure_compare(user.token, token)
            @current_user = user
          else
            return nil
          end
        end
```
```
        def authenticate_user!
          authenticate_user or raise UnauthenticatedError
        end

```

**Comment by wasifhossain** [comment]
pls also update the OP (the original post; not in a new comment) by including the user controller

**Comment by sadmanahmed** [comment]
DONE

**Comment by wasifhossain** [comment]
i see the authenticate_request! method is still referenced from the callbacks. can you please remove these 2 lines and make another call. let me know if you get the same json output as well as same server log
```rb
      skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      before_action :authenticate_user, only: [:index, :show]
```

**Comment by sadmanahmed** [comment]
users_controller.rb
```
before_action :load_resource
      #skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      #before_action :authenticate_user, only: [:index, :show]
```


server log
```
Started DELETE "/api/v1/users/25" for ::1 at 2020-04-23 14:42:44 +0600
Processing by Api::V1::UsersController#destroy as */*
  Parameters: {"id"=>"25"}
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."email" IS NULL LIMIT $1  [["LIMIT", 1]]
  ↳ app/controllers/api/v1/base_controller.rb:39:in `authenticate_user'
Unauthenticated user not granted access
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.23ms)
Completed 401 Unauthorized in 5ms (Views: 1.0ms | ActiveRecord: 0.5ms | Allocations: 1410)
```
json output
```
{
    "errors": [
        {
            "status": 401,
            "title": "Not Authenticated",
            "detail": "Not Authenticated",
            "source": {
                "pointer": "data"
            }
        }
    ]
}
```

**Comment by wasifhossain** [comment]
okay lets solve #55 first. that will hopefully help you to solve this case too

**Comment by sadmanahmed** [comment]
USER DELETATION SUCCESSFUL
