### ISSUE TITLE
POST request with jsonapi params as input

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#62]
post http://localhost:3000/api/v1/microposts

json input
```
{  
  "data":{  
    "type":"microposts",
    "attributes":{  
      "micropost": {
        "content": "A simple micropost",
        "user_id": 1
      }
    }
  }
}

```

json output
```
{
    "errors": [
        {
            "status": 422,
            "title": "can't be blank",
            "detail": "can't be blank",
            "source": {
                "pointer": "data/attributes/content"
            }
        }
    ]
}
```

server log
```
Started POST "/api/v1/microposts" for ::1 at 2020-04-26 01:31:48 +0600
   (0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Api::V1::MicropostsController#create as */*
  Parameters: {"data"=>{"type"=>"microposts", "attributes"=>{"micropost"=>{"content"=>"A simple micropost", "user_id"=>1}}}, "micropost"=>{}}
  User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/base_controller.rb:40:in `authenticate_user'
Unpermitted parameter: :micropost
   (0.3ms)  BEGIN
  ↳ app/controllers/api/v1/microposts_controller.rb:28:in `create'
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/microposts_controller.rb:28:in `create'
   (0.2ms)  ROLLBACK
  ↳ app/controllers/api/v1/microposts_controller.rb:28:in `create'
Content can't be blank
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.18ms)
Completed 422 Unprocessable Entity in 176ms (Views: 2.2ms | ActiveRecord: 15.9ms | Allocations: 204020)


```

MicropostsController#create
```

      def create
        auth_micropost = authorize_with_permissions(@micropost)

        if @micropost.save
          render json: auth_micropost.record,
            serializer: MicropostSerializer,
          adapter: :json_api,
            fields: {mircopost: auth_micropost.fields}, status: 201
        else
          invalid_resource!(@micropost.errors)
        end
      end
```

**Comment by wasifhossain** [comment]
the input json does not look to be a valid JSONAPI structure. lets fix it this way
```json
{  
  "data":{  
    "type":"microposts",
    "attributes":{  
      "content": "A simple micropost",
      "user_id": 1
    }
  }
}
```
and see if it fixes the request

otherwise lets see the whole micropost controller

**Comment by sadmanahmed** [comment]
Okay it worked..
