### ISSUE TITLE
PUT request with jsonapi params as input

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#63]
PUT localhost:3000/api/v1/microposts/301

RAW JSON input
```
{  
  "data":{  
    "type":"microposts",
    "attributes":{  
      "micropost": {
        "content":"Another micropost"
      }
    }
  }
}

```

JSON output
```
{
    "data": {
        "id": "301",
        "type": "microposts",
        "attributes": {
            "content": "s",
            "user-id": 1,
            "created-at": "2020-04-23T05:42:01Z",
            "updated-at": "2020-04-23T05:42:01Z"
        },
        "relationships": {
            "user": {
                "links": {
                    "related": "/api/v1/users/1"
                }
            }
        }
    }
}

```

Server Log
```
Started PUT "/api/v1/microposts/301" for ::1 at 2020-04-26 02:30:41 +0600
Processing by Api::V1::MicropostsController#update as */*
  Parameters: {"data"=>{"type"=>"microposts", "attributes"=>{"micropost"=>{"content"=>"Another micropost"}}}, "id"=>"301", "micropost"=>{}}
  User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/base_controller.rb:40:in `authenticate_user'
  Micropost Load (0.7ms)  SELECT "microposts".* FROM "microposts" WHERE "microposts"."id" = $1 ORDER BY "microposts"."created_at" DESC LIMIT $2  [["id", 301], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/microposts_controller.rb:70:in `load_resource'
Unpermitted parameter: :micropost
   (0.4ms)  BEGIN
  ↳ app/controllers/api/v1/microposts_controller.rb:41:in `update'
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/microposts_controller.rb:41:in `update'
  ActiveStorage::Attachment Load (0.6ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 301], ["record_type", "Micropost"], ["name", "image"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/microposts_controller.rb:41:in `update'
   (0.5ms)  COMMIT
  ↳ app/controllers/api/v1/microposts_controller.rb:41:in `update'
[active_model_serializers] Rendered Api::V1::MicropostSerializer with ActiveModelSerializers::Adapter::JsonApi (0.88ms)
Completed 200 OK in 24ms (Views: 1.4ms | ActiveRecord: 4.0ms | Allocations: 6738)
```
**(I want to add an important addition info : the update action in the api/v1/microposts_controller.rb is different than the one in the main microposts_controller.rb)**

update action
```
def update
        auth_micropost = authorize_with_permissions(@micropost, :update?)

        if @micropost.update(update_params)
          render json: auth_micropost.record,
            serializer: MicropostSerializer,
          adapter: :json_api,
            micropost: {user: auth_micropost.fields}
        else
          invalid_resource!(@micropost.errors)
        end
      end
```

**Comment by wasifhossain** [comment]
similar to #62 

you need to make the input json to be a valid JSONAPI structure
```diff
{  
  "data":{  
    "type":"microposts",
    "attributes":{  
-      "micropost": {
        "content":"Another micropost"
-      }
    }
  }
}
```

**Comment by sadmanahmed** [comment]
It worked too..
