### ISSUE TITLE
Heroku API 500 internal server error

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#66]
GET :  https://obscure-hollows-36531.herokuapp.com/api/v1/users

HEROKU logs
```
sample_app git:(master) ✗ heroku logs
2020-04-27T13:27:19.389609+00:00 heroku[router]: at=info method=GET path="/api/v1/users" host=obscure-hollows-36531.herokuapp.com request_id=9949a5f4-1dd1-4085-aad8-d0a57b74043d fwd="116.204.255.31" dyno=web.1 connect=13ms service=111ms status=500 bytes=1905 protocol=https
2020-04-27T13:27:19.299809+00:00 app[web.1]: I, [2020-04-27T13:27:19.299689 #9]  INFO -- : [9949a5f4-1dd1-4085-aad8-d0a57b74043d] Started GET "/api/v1/users" for 116.204.255.31 at 2020-04-27 13:27:19 +0000
2020-04-27T13:27:19.308106+00:00 app[web.1]: I, [2020-04-27T13:27:19.308029 #9]  INFO -- : [9949a5f4-1dd1-4085-aad8-d0a57b74043d] Processing by Api::V1::UsersController#index as */*
2020-04-27T13:27:19.350838+00:00 app[web.1]: D, [2020-04-27T13:27:19.350718 #9] DEBUG -- : [9949a5f4-1dd1-4085-aad8-d0a57b74043d]   User Load (17.4ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
2020-04-27T13:27:19.379828+00:00 app[web.1]: I, [2020-04-27T13:27:19.379704 #9]  INFO -- : [9949a5f4-1dd1-4085-aad8-d0a57b74043d] Completed 500 Internal Server Error in 71ms (ActiveRecord: 17.4ms | Allocations: 3524)
2020-04-27T13:27:19.387866+00:00 app[web.1]: F, [2020-04-27T13:27:19.387766 #9] FATAL -- : [9949a5f4-1dd1-4085-aad8-d0a57b74043d]
2020-04-27T13:27:19.387868+00:00 app[web.1]: [9949a5f4-1dd1-4085-aad8-d0a57b74043d] NoMethodError (undefined method `token' for #<User:0x00007f102c2044a8>
2020-04-27T13:27:19.387869+00:00 app[web.1]: Did you mean?  to_key):
2020-04-27T13:27:19.387869+00:00 app[web.1]: [9949a5f4-1dd1-4085-aad8-d0a57b74043d]
2020-04-27T13:27:19.387870+00:00 app[web.1]: [9949a5f4-1dd1-4085-aad8-d0a57b74043d] app/controllers/api/v1/base_controller.rb:41:in `authenticate_user'
2020-04-27T13:27:19.387870+00:00 app[web.1]: [9949a5f4-1dd1-4085-aad8-d0a57b74043d] app/controllers/api/v1/base_controller.rb:49:in `authenticate_user!'
2020-04-27T13:27:42.265568+00:00 app[web.1]: I, [2020-04-27T13:27:42.265433 #9]  INFO -- : [c146ab83-4cd9-45c6-bb8d-410bda26e707] Started GET "/api/v1/users" for 116.204.255.31 at 2020-04-27 13:27:42 +0000
2020-04-27T13:27:42.280677+00:00 app[web.1]: I, [2020-04-27T13:27:42.280559 #9]  INFO -- : [c146ab83-4cd9-45c6-bb8d-410bda26e707] Processing by Api::V1::UsersController#index as */*
2020-04-27T13:27:42.293120+00:00 app[web.1]: D, [2020-04-27T13:27:42.292996 #9] DEBUG -- : [c146ab83-4cd9-45c6-bb8d-410bda26e707]   User Load (5.6ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
2020-04-27T13:27:42.307222+00:00 app[web.1]: I, [2020-04-27T13:27:42.307106 #9]  INFO -- : [c146ab83-4cd9-45c6-bb8d-410bda26e707] Completed 500 Internal Server Error in 26ms (ActiveRecord: 5.6ms | Allocations: 3417)
2020-04-27T13:27:42.309018+00:00 app[web.1]: F, [2020-04-27T13:27:42.308944 #9] FATAL -- : [c146ab83-4cd9-45c6-bb8d-410bda26e707]
2020-04-27T13:27:42.309019+00:00 app[web.1]: [c146ab83-4cd9-45c6-bb8d-410bda26e707] NoMethodError (undefined method `token' for #<User:0x00007f103425bd18>
2020-04-27T13:27:42.309020+00:00 app[web.1]: Did you mean?  to_key):
2020-04-27T13:27:42.309021+00:00 app[web.1]: [c146ab83-4cd9-45c6-bb8d-410bda26e707]
2020-04-27T13:27:42.309022+00:00 app[web.1]: [c146ab83-4cd9-45c6-bb8d-410bda26e707] app/controllers/api/v1/base_controller.rb:41:in `authenticate_user'
2020-04-27T13:27:42.309022+00:00 app[web.1]: [c146ab83-4cd9-45c6-bb8d-410bda26e707] app/controllers/api/v1/base_controller.rb:49:in `authenticate_user!'
2020-04-27T13:27:42.310745+00:00 heroku[router]: at=info method=GET path="/api/v1/users" host=obscure-hollows-36531.herokuapp.com request_id=c146ab83-4cd9-45c6-bb8d-410bda26e707 fwd="116.204.255.31" dyno=web.1 connect=5ms service=53ms status=500 bytes=1905 protocol=https

```

**Comment by sadmanahmed** [comment]
Seems like user authentication problem

**Comment by wasifhossain** [comment]
i have removed irrelevant logs to make it read easily. the error says:
> NoMethodError (undefined method `token' for #<User:0x00007f103425bd18>

any chance you might not have run migration?

**Comment by sadmanahmed** [comment]
Heroku logs
```
 sample_app git:(master) heroku logs
2020-04-27T17:42:17.963178+00:00 heroku[router]: at=info method=POST path="/api/v1/sessions" host=obscure-hollows-36531.herokuapp.com request_id=8f361762-5c3d-476f-9896-bb3bcbcf47fd fwd="103.125.234.200" dyno=web.1 connect=1ms service=12ms status=401 bytes=636 protocol=https
2020-04-27T17:42:17.952845+00:00 app[web.1]: I, [2020-04-27T17:42:17.952755 #18]  INFO -- : [8f361762-5c3d-476f-9896-bb3bcbcf47fd] Started POST "/api/v1/sessions" for 103.125.234.200 at 2020-04-27 17:42:17 +0000
2020-04-27T17:42:17.955032+00:00 app[web.1]: I, [2020-04-27T17:42:17.954961 #18]  INFO -- : [8f361762-5c3d-476f-9896-bb3bcbcf47fd] Processing by Api::V1::SessionsController#create as */*
2020-04-27T17:42:17.955832+00:00 app[web.1]: I, [2020-04-27T17:42:17.955770 #18]  INFO -- : [8f361762-5c3d-476f-9896-bb3bcbcf47fd] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.13ms)
2020-04-27T17:42:17.956036+00:00 app[web.1]: I, [2020-04-27T17:42:17.955985 #18]  INFO -- : [8f361762-5c3d-476f-9896-bb3bcbcf47fd] Completed 401 Unauthorized in 1ms (Views: 0.6ms | ActiveRecord: 0.0ms | Allocations: 397)
2020-04-27T17:46:21.553858+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=obscure-hollows-36531.herokuapp.com request_id=83b9efb8-3f9b-4227-8a0e-f82923fcabca fwd="103.125.234.200" dyno=web.1 connect=0ms service=1ms status=200 bytes=221 protocol=https
2020-04-27T17:47:19.207105+00:00 heroku[router]: at=info method=GET path="/api/v1/users" host=obscure-hollows-36531.herokuapp.com request_id=0f7680e3-e93d-4dcc-a8c2-5e281823004c fwd="103.125.234.200" dyno=web.1 connect=0ms service=11ms status=401 bytes=636 protocol=https
2020-04-27T17:47:19.196589+00:00 app[web.1]: I, [2020-04-27T17:47:19.196503 #9]  INFO -- : [0f7680e3-e93d-4dcc-a8c2-5e281823004c] Started GET "/api/v1/users" for 103.125.234.200 at 2020-04-27 17:47:19 +0000
2020-04-27T17:47:19.199704+00:00 app[web.1]: I, [2020-04-27T17:47:19.199643 #9]  INFO -- : [0f7680e3-e93d-4dcc-a8c2-5e281823004c] Processing by Api::V1::UsersController#index as */*
2020-04-27T17:47:19.203406+00:00 app[web.1]: D, [2020-04-27T17:47:19.203343 #9] DEBUG -- : [0f7680e3-e93d-4dcc-a8c2-5e281823004c]   User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
2020-04-27T17:47:19.205269+00:00 app[web.1]: I, [2020-04-27T17:47:19.205205 #9]  INFO -- : [0f7680e3-e93d-4dcc-a8c2-5e281823004c] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.16ms)
2020-04-27T17:47:19.205489+00:00 app[web.1]: I, [2020-04-27T17:47:19.205437 #9]  INFO -- : [0f7680e3-e93d-4dcc-a8c2-5e281823004c] Completed 401 Unauthorized in 6ms (Views: 1.5ms | ActiveRecord: 0.8ms | Allocations: 1065)
2020-04-27T17:47:32.374141+00:00 heroku[router]: at=info method=GET path="/api/v1/users" host=obscure-hollows-36531.herokuapp.com request_id=45bae102-70ff-4b7e-b7d8-00f25ebcecf5 fwd="103.125.234.200" dyno=web.1 connect=1ms service=8ms status=401 bytes=636 protocol=https
2020-04-27T17:47:32.365788+00:00 app[web.1]: I, [2020-04-27T17:47:32.365691 #9]  INFO -- : [45bae102-70ff-4b7e-b7d8-00f25ebcecf5] Started GET "/api/v1/users" for 103.125.234.200 at 2020-04-27 17:47:32 +0000
2020-04-27T17:47:32.368054+00:00 app[web.1]: I, [2020-04-27T17:47:32.367984 #9]  INFO -- : [45bae102-70ff-4b7e-b7d8-00f25ebcecf5] Processing by Api::V1::UsersController#index as */*
2020-04-27T17:47:32.370801+00:00 app[web.1]: D, [2020-04-27T17:47:32.370732 #9] DEBUG -- : [45bae102-70ff-4b7e-b7d8-00f25ebcecf5]   User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
2020-04-27T17:47:32.371646+00:00 app[web.1]: I, [2020-04-27T17:47:32.371569 #9]  INFO -- : [45bae102-70ff-4b7e-b7d8-00f25ebcecf5] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.13ms)
2020-04-27T17:47:32.371831+00:00 app[web.1]: I, [2020-04-27T17:47:32.371772 #9]  INFO -- : [45bae102-70ff-4b7e-b7d8-00f25ebcecf5] Completed 401 Unauthorized in 4ms (Views: 0.6ms | ActiveRecord: 0.9ms | Allocations: 624)

```
json output
```
{
    "errors": [
        {
            "status": 401,
            "title": "Not Authenticated",
            "detail": "Not Authenticated",
            "source": {
                "pointer": "data"
            }
        }
    ]
}
```

**Comment by wasifhossain** [comment]
awesome :tada: the error is resolved

**Comment by wasifhossain** [comment]
to make a successful request, you have to make sure that the user record already exists in db

**Comment by sadmanahmed** [comment]
may I get the shell command?

**Comment by wasifhossain** [comment]
use the email to find out if the user is available in db. create it otherwise
```rb
user = User.find_by(email: "<enter-user-email>")
unless user
  User.create!(email: "<enter-user-email>", password: "enter-user-password")
end
```

**Comment by sadmanahmed** [comment]
`heroku run bash`
then this? 
```
user = User.find_by(email: "<enter-user-email>")
unless user
  User.create!(email: "<enter-user-email>", password: "enter-user-password")
end
```

**Comment by sadmanahmed** [comment]
Is this an error or what? What is the syntax error here

```
➜  sample_app git:(master) heroku run bash
Running bash on ⬢ obscure-hollows-36531... up, run.9092 (Free)
~ $ user = User.find_by(email: "abirssc7@gmail.com")
bash: syntax error near unexpected token `('
~ $ user = User.find_by ( email: "abirssc7@gmail.com" )
bash: syntax error near unexpected token `('
```

**Comment by wasifhossain** [comment]
think about **heroku as your computer**. what would you do to run the above commands?
1. open the terminal (bash)
2. run `rails console`
3. execute the ruby code

the same you can do on heroku:
1. `heroku run bash`
2. `rails console`
3. run the ruby code

heroku provides a single command to perform step 1 and 2: `heroku run rails console`

in fact, you can run **any rails command** by prefixing `heroku run`
e.g.
```
$ heroku run rails db:migrate
$ heroku run rails db:migrate:status
```

**Comment by sadmanahmed** [comment]
```
sample_app git:(master) heroku run rails c
Running rails c on ⬢ obscure-hollows-36531... up, run.4344 (Free)
Loading production environment (Rails 6.0.0)
irb(main):001:0>  user = User.find_by(email: "abirssc7@gmail.com")
D, [2020-04-27T18:22:37.420240 #4] DEBUG -- :   User Load (1.5ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
=> #<User id: 1, name: "Abir", email: "abirssc7@gmail.com", created_at: "2020-04-27 16:58:37", updated_at: "2020-04-27 16:58:37", password_digest: [FILTERED], remember_digest: nil, admin: true, activation_digest: "$2a$12$6S7dG1qZMWLsri10YhqLguriA2URTZeH4j8l/L5qWHg...", activated: true, activated_at: "2020-04-27 16:58:37", reset_digest: nil, reset_sent_at: nil, token: "03a7dfc4c9d60004d864044a23f8e754", microposts_count: 50, followers_count: 38, followings_count: 49>

```

**Comment by wasifhossain** [comment]
can you share `authenticate_request` method from base controller

**Comment by sadmanahmed** [comment]
there is nothing `authenticate_request` here

```
module Api
  module V1

    class BaseController < ActionController::API
      include Pundit
      include ActiveHashRelation
      include CustomErrors

      before_action :authenticate_user!, except: :options

      rescue_from ActionController::ParameterMissing do
        api_error(status: 400, errors: 'Invalid parameters')
      end

      rescue_from Pundit::NotAuthorizedError do
        unauthorized!
      end

      rescue_from ActiveRecord::RecordNotFound do
        api_error(status: 404, errors: 'Resource not found!')
      end

      rescue_from UnauthenticatedError do
        unauthenticated!
      end

      protected
        def current_user
          @current_user
        end

        def authenticate_user
          token, options = ActionController::HttpAuthentication::Token.token_and_options(
            request
          )
           #binding.pry

          return nil unless token && options.is_a?(Hash)

          user = User.find_by(email: options['email'])
          if user && ActiveSupport::SecurityUtils.secure_compare(user.token, token)
            @current_user = user
          else
            return nil
          end
        end

        def authenticate_user!
          authenticate_user or raise UnauthenticatedError
        end

        def unauthorized!
          unless Rails.env.production? || Rails.env.test?
            Rails.logger.warn { "unauthorized for: #{current_user.try(:id)}" }
          end

          api_error(status: 403, errors: 'Not Authorized')
        end

        def unauthenticated!
          unless Rails.env.production? || Rails.env.test?
            Rails.logger.warn { "Unauthenticated user not granted access" }
          end

          api_error(status: 401, errors: 'Not Authenticated')
        end

        def not_found!
          Rails.logger.warn { "not_found for: #{current_user.try(:id)}" }

          api_error(status: 404, errors: 'Resource not found')
        end

        def invalid_resource!(errors = [])
          api_error(status: 422, errors: errors)
        end

        def paginate(resource)
          default_per_page = Rails.application.secrets.default_per_page || 25

          resource.paginate({
            page: params[:page] || 1, per_page: params[:per_page] || default_per_page
          })
        end

        #expects paginated resource!
        def meta_attributes(resource, extra_meta = {})
          {
            current_page: resource.current_page,
            next_page: resource.next_page,
            prev_page: resource.previous_page,
            total_pages: resource.total_pages,
            total_count: resource.total_entries
          }.merge(extra_meta)
        end

        def api_error(status: 500, errors: [])
          puts errors.full_messages if errors.respond_to?(:full_messages)

          render json: ErrorSerializer.new(status, errors).as_json,
            status: status,
            adapter: :json_api
        end
    end
  end
end

```

**Comment by sadmanahmed** [comment]
**2ndly** 
I have used this new token from the **heroku run rails console** `Token token="03a7dfc4c9d60004d864044a23f8e754",email=abirssc7@gmail.com`
and get this result for 
`POST : https://obscure-hollows-36531.herokuapp.com/api/v1/users/1`
```
{
    "data": {
        "id": "1",
        "type": "users",
        "attributes": {
            "name": "Abir",
            "email": "abirssc7@gmail.com",
            "created-at": "2020-04-27T16:58:37Z",
            "updated-at": "2020-04-27T16:58:37Z",
            "password-digest": "$2a$12$PVGzSdeQejLkf.sTXgg6tu/VK.CN6Z9xnFUTglWSOs2ImLCjtN3kW",
            "remember-digest": null,
            "admin": true,
            "activation-digest": "$2a$12$6S7dG1qZMWLsri10YhqLguriA2URTZeH4j8l/L5qWHgI8qQiPeilS",
            "activated": true,
            "activated-at": "2020-04-27T16:58:37.011Z",
            "reset-digest": null,
            "reset-sent-at": null,
            "token": "03a7dfc4c9d60004d864044a23f8e754",
            "microposts-count": 50,
            "followers-count": 38,
            "followings-count": 49,
            "following-state": false,
            "follower-state": false
        },
        "relationships": {
            "feed": {
                "links": {
                    "related": "/api/v1/users/1/feed"
                }
            },
            "microposts": {
                "links": {
                    "related": "/api/v1/microposts?user_id=1"
                }
            },
            "followers": {
                "links": {
                    "related": "/api/v1/users/1/followers"
                }
            },
            "followings": {
                "links": {
                    "related": "/api/v1/users/1/followings"
                }
            }
        }
    }
}
```

**It is the expected result actually**

**Comment by wasifhossain** [comment]
congrats! then we don't need to wait anymore before closing the issue! right?
