### ISSUE TITLE
Errors in the test file

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#7]
```
sample_app git:(account-activation) ✗ rails test:mailers
Started with run options --seed 40749

 FAIL["test_account_activation", #<Minitest::Reporters::Suite:0x000056268638b8e8 @name="UserMailerTest">, 0.14540133700006663]
 test_account_activation#UserMailerTest (0.15s)
        Expected /Michael\ Example/ to match # encoding: US-ASCII
        "\r\n----==_mimepart_5df7ebe85e8c6_1f152b13409f995c43224\r\nContent-Type: text/plain;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\nUserMailer#account_activation\r\n\r\n, find me in app/views/user_mailer/account_activation.text.erb\r\n\r\n\r\n----==_mimepart_5df7ebe85e8c6_1f152b13409f995c43224\r\nContent-Type: text/html;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n  <head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n    <style>\r\n      /* Email styles need to be inline */\r\n    </style>\r\n  </head>\r\n\r\n  <body>\r\n    <h1>UserMailer#account_activation</h1>\r\n\r\n<p>\r\n  , find me in app/views/user_mailer/account_activation.html.erb\r\n</p>\r\n\r\n  </body>\r\n</html>\r\n\r\n----==_mimepart_5df7ebe85e8c6_1f152b13409f995c43224--\r\n".
        test/mailers/user_mailer_test.rb:12:in `block in <class:UserMailerTest>'

  1/1: [============================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.14603s
1 tests, 5 assertions, 1 failures, 0 errors, 0 skips
```
user_mailer_test.rb
``` 
require 'test_helper'

class UserMailerTest < ActionMailer::TestCase

  test "account_activation" do
    user = users(:michael)
    user.activation_token = User.new_token
    mail = UserMailer.account_activation(user)
    assert_equal "Account activation", mail.subject
    assert_equal [user.email], mail.to
    assert_equal ["noreply@example.com"], mail.from
    assert_match user.name,               mail.body.encoded
    assert_match user.activation_token,   mail.body.encoded
    assert_match CGI.escape(user.email),  mail.body.encoded
  end
end
```

**Comment by wasifhossain** [comment]
could you please paste the contents as text instead of image with proper formatting using 3 backtick? thanks

**Comment by sadmanahmed** [comment]
```➜  sample_app git:(account-activation) ✗ rails test:mailers
Started with run options --seed 40749

 FAIL["test_account_activation", #<Minitest::Reporters::Suite:0x000056268638b8e8 @name="UserMailerTest">, 0.14540133700006663]
 test_account_activation#UserMailerTest (0.15s)
        Expected /Michael\ Example/ to match # encoding: US-ASCII
        "\r\n----==_mimepart_5df7ebe85e8c6_1f152b13409f995c43224\r\nContent-Type: text/plain;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\nUserMailer#account_activation\r\n\r\n, find me in app/views/user_mailer/account_activation.text.erb\r\n\r\n\r\n----==_mimepart_5df7ebe85e8c6_1f152b13409f995c43224\r\nContent-Type: text/html;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n  <head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n    <style>\r\n      /* Email styles need to be inline */\r\n    </style>\r\n  </head>\r\n\r\n  <body>\r\n    <h1>UserMailer#account_activation</h1>\r\n\r\n<p>\r\n  , find me in app/views/user_mailer/account_activation.html.erb\r\n</p>\r\n\r\n  </body>\r\n</html>\r\n\r\n----==_mimepart_5df7ebe85e8c6_1f152b13409f995c43224--\r\n".
        test/mailers/user_mailer_test.rb:12:in `block in <class:UserMailerTest>'

  1/1: [============================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.14603s
1 tests, 5 assertions, 1 failures, 0 errors, 0 skips

**Comment by wasifhossain** [comment]
looks good :+1: 

can you share the method `test_account_activation#UserMailerTest`

**Comment by sadmanahmed** [comment]
``` sample_app git:(account-activation) ✗ rails test:mailers
Started with run options --seed 40749

 FAIL["test_account_activation", #<Minitest::Reporters::Suite:0x000056268638b8e8 @name="UserMailerTest">, 0.14540133700006663]
 test_account_activation#UserMailerTest (0.15s)
        Expected /Michael\ Example/ to match # encoding: US-ASCII
        "\r\n----==_mimepart_5df7ebe85e8c6_1f152b13409f995c43224\r\nContent-Type: text/plain;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\nUserMailer#account_activation\r\n\r\n, find me in app/views/user_mailer/account_activation.text.erb\r\n\r\n\r\n----==_mimepart_5df7ebe85e8c6_1f152b13409f995c43224\r\nContent-Type: text/html;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n  <head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n    <style>\r\n      /* Email styles need to be inline */\r\n    </style>\r\n  </head>\r\n\r\n  <body>\r\n    <h1>UserMailer#account_activation</h1>\r\n\r\n<p>\r\n  , find me in app/views/user_mailer/account_activation.html.erb\r\n</p>\r\n\r\n  </body>\r\n</html>\r\n\r\n----==_mimepart_5df7ebe85e8c6_1f152b13409f995c43224--\r\n".
        test/mailers/user_mailer_test.rb:12:in `block in <class:UserMailerTest>'

  1/1: [============================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.14603s
1 tests, 5 assertions, 1 failures, 0 errors, 0 skips

**Comment by sadmanahmed** [comment]
but why the whole error lines is not shared in ``` format?

**Comment by wasifhossain** [comment]
not clear what are you talking about

**Comment by wasifhossain** [comment]
can you check if your post is showing properly

**Comment by sadmanahmed** [comment]
Yes ,it's(errors) showing properly now

**Comment by wasifhossain** [comment]
you need to write texts between 2 sets of ```, putting backticks on their own line

**Comment by wasifhossain** [comment]
looks good :+1: 

can you share the method `test_account_activation#UserMailerTest`

**Comment by sadmanahmed** [comment]
user_mailer_test.rb
```require 'test_helper'

class UserMailerTest < ActionMailer::TestCase

  test "account_activation" do
    user = users(:michael)
    user.activation_token = User.new_token
    mail = UserMailer.account_activation(user)
    assert_equal "Account activation", mail.subject
    assert_equal [user.email], mail.to
    assert_equal ["noreply@example.com"], mail.from
    assert_match user.name,               mail.body.encoded
    assert_match user.activation_token,   mail.body.encoded
    assert_match CGI.escape(user.email),  mail.body.encoded
  end
end

```

**Comment by sadmanahmed** [comment]
Have I done something wrong?

**Comment by wasifhossain** [comment]
```rb
assert_match user.name,               mail.body.encoded
```
failed due to the user name missing from mail body

**Comment by sadmanahmed** [comment]
what should I do next?

**Comment by wasifhossain** [comment]
do you expect the user name to be present in the mail body?

**Comment by sadmanahmed** [comment]
Yes (but I am confused with this and also with **TEST** method )

**Comment by wasifhossain** [comment]
now i am getting confused with your comment :confused:

**Comment by sadmanahmed** [comment]
Sharing the Situation : I was on the tutorial of authenticate users email id and following the tutorials. Everything going fine,the *rails t* is showing no error then I have edited the development.rb and after that everything broke.

**Comment by wasifhossain** [comment]
can you share the difference that you have edited (which you believe might have broken the tests)?

**Comment by sadmanahmed** [comment]
I have double checked the codes from the very beginning of chapter 11.  The tutorial said to restart the server , so I shut down the server and when trying to start it,it was showing errors .I thought maybe it is a problem of terminator as it was saying that there is already a server running. SO i restart the pc. So can not share the previous ones test results
.

**Comment by sadmanahmed** [comment]
I know I am sound like too much confusing and I am confused here actually. Is it wise to delete this branch and start properly again?

**Comment by wasifhossain** [comment]
may be. if revamping the whole thing does not cost too much.
