### ISSUE TITLE
Why we need authorization token to signup?

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#70]
**Without any authorization token**
POST :  localhost:3000/api/v1/users
INPUT json
```
{  
  "data":{  
    "type":"users",
    "attributes":{  
      "password":"12341234",
      "email":"ab1@email.com",
      "name":"Filippos Vasilakis"
    }
  }
}
```
Json out
```
{
    "errors": [
        {
            "status": 401,
            "title": "Not Authenticated",
            "detail": "Not Authenticated",
            "source": {
                "pointer": "data"
            }
        }
    ]
}
```

server log
```
Processing by Api::V1::UsersController#create as */*
  Parameters: {"data"=>{"type"=>"users", "attributes"=>{"password"=>"[FILTERED]", "email"=>"ab1@email.com", "name"=>"Filippos Vasilakis"}}, "user"=>{}}
Unauthenticated user not granted access
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.18ms)
Completed 401 Unauthorized in 8ms (Views: 2.4ms | ActiveRecord: 3.3ms | Allocations: 4511)

```

users_controller.rb
```

module Api
  module V1
    class UsersController < BaseController
      before_action :load_resource
      #skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      # before_action :authenticate_user, only: [:index, :show]

      def index
        auth_users = policy_scope(@users)
        # binding.pry
        render json: auth_users.collection,
               each_serializer: UserSerializer,
               fields: { user: auth_users.fields(params[:fields]) },
               meta: meta_attributes(auth_users.collection),
               adapter: :json_api
      end

      def show
        auth_user = authorize_with_permissions(@user)

        render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
               fields: { user: auth_user.fields }
      end

      def create
        auth_user = authorize_with_permissions(@user)

        if @user.save && @user.send_activation_email && @user.activate
          render json: auth_user.record, serializer: UserSerializer,
                 fields: { user: auth_user.fields }, status: 201, scope: @user, adapter: :json_api
        else
          invalid_resource!(@user.errors)
        end
      end

      def update
        auth_user = authorize_with_permissions(@user, :update?)

        if @user.update(update_params)
          render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
                 fields: { user: auth_user.fields }
        else
          invalid_resource!(@user.errors)
        end
      end

      def destroy
        auth_user = authorize_with_permissions(@user, :destroy?)

        @user.destroy!

        render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
               fields: { user: auth_user.fields }
      end

      def activate
        auth_user = authorize_with_permissions(@user, :activate?)

        if @user.authenticated?(:activation, params[:token])
          render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
                 fields: { user: auth_user.fields }, status: 200, scope: @user
        else
          not_found!
        end
      end

      private

      def load_resource
        case params[:action].to_sym
        when :index
          @users = paginate(apply_filters(User.all, params))
        when :create
          @user = User.new(create_params)
        when :show, :update, :destroy
          @user = User.find(params[:id])
        when :activate
          @user = User.find_by!(email: params[:email])
        end
      end

      def create_params
        normalized_params.permit(
          :email, :password, :password_confirmation, :name
        )
      end

      def update_params
        create_params
      end

      def normalized_params
        ActionController::Parameters.new(
          ActiveModelSerializers::Deserialization.jsonapi_parse(params)
        )
      end
    end
  end
end

```

**Comment by wasifhossain** [comment]
you already answered your own question!

if you like to allow users to signup on their own, then you need to skip regular authentication process for that specific endpoint, for this case, its `users#create`

so you can do it as:
```rb
skip_before_action :authenticate_user!, only: :create
```

**Comment by sadmanahmed** [comment]
what is the effect of this two code on the api? I tried to figure out but making it more confusing
` skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate] `

` before_action :authenticate_user, only: [:index, :show] `

**Comment by wasifhossain** [comment]
let me explain each case

```rb
before_action :authenticate_user, only: [:index, :show]
```
here `before_action` callback makes sure that the provided method (`authenticate_user`) is called **before** the actions listed under the `only` option

and as the name suggests, `skip_before_action` callback **SKIPS** the method from being called **before** the actions listed under the `only` option

**Comment by sadmanahmed** [comment]
so now internal server error came up 
```
Started POST "/api/v1/users" for ::1 at 2020-05-01 01:00:23 +0600
Processing by Api::V1::UsersController#create as */*
  Parameters: {"data"=>{"type"=>"users", "attributes"=>{"password"=>"[FILTERED]", "email"=>"ab1@email.com", "name"=>"Filippos Vasilakis"}}, "user"=>{}}
Completed 500 Internal Server Error in 556ms (ActiveRecord: 2.5ms | Allocations: 75057)


  
NoMethodError (undefined method `authorize_with_permissions' for #<Api::V1::UsersController:0x000055c5ece80910>):
  
app/controllers/api/v1/users_controller.rb:31:in `create'

```

If I am commenting out auth_user like this 
```
def create
        #auth_user = authorize_with_permissions(@user)

        if @user.save && @user.send_activation_email && @user.activate
          render json: auth_user.record, serializer: UserSerializer,
                 fields: { user: auth_user.fields }, status: 201, scope: @user, adapter: :json_api
        else
          invalid_resource!(@user.errors)
        end
      end
```
this error is coming
```
app/controllers/api/v1/users_controller.rb:31:in `create'
Started POST "/api/v1/users" for ::1 at 2020-05-01 01:03:11 +0600
Processing by Api::V1::UsersController#create as */*
  Parameters: {"data"=>{"type"=>"users", "attributes"=>{"password"=>"[FILTERED]", "email"=>"ab1@email.com", "name"=>"Filippos Vasilakis"}}, "user"=>{}}
   (0.3ms)  BEGIN
  ↳ app/models/user.rb:161:in `block in generate_hex'
  User Exists? (82.8ms)  SELECT 1 AS one FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "560ba88ace2dfbce335f995444db7eb4"], ["LIMIT", 1]]
  ↳ app/models/user.rb:161:in `block in generate_hex'
  User Exists? (0.9ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "ab1@email.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:33:in `create'
  CACHE User Exists? (0.0ms)  SELECT 1 AS one FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "560ba88ace2dfbce335f995444db7eb4"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:33:in `create'
  User Create (69.2ms)  INSERT INTO "users" ("name", "email", "created_at", "updated_at", "password_digest", "activation_digest", "token") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["name", "Filippos Vasilakis"], ["email", "ab1@email.com"], ["created_at", "2020-04-30 19:03:11.729559"], ["updated_at", "2020-04-30 19:03:11.729559"], ["password_digest", "$2a$12$cIrTKmfdhdNp6WEU3FOUI.Np9amye20/lk/gD761ddD7BniMlDP5O"], ["activation_digest", "$2a$12$Gq4N8hVHNZYMtZB6oKYT7u./n4qPCPTfMP93ZpsVCuBsb55DUdzcC"], ["token", "560ba88ace2dfbce335f995444db7eb4"]]
  ↳ app/controllers/api/v1/users_controller.rb:33:in `create'
   (50.0ms)  COMMIT
  ↳ app/controllers/api/v1/users_controller.rb:33:in `create'
  Rendering user_mailer/account_activation.html.erb within layouts/mailer
  Rendered user_mailer/account_activation.html.erb within layouts/mailer (Duration: 11.0ms | Allocations: 216)
  Rendering user_mailer/account_activation.text.erb within layouts/mailer
  Rendered user_mailer/account_activation.text.erb within layouts/mailer (Duration: 6.6ms | Allocations: 175)
UserMailer#account_activation: processed outbound mail in 51.6ms
Delivered mail 5eab20f0cdb12_674f2ae2f6b557e4537d7@abir-dell.mail (19.0ms)
Date: Fri, 01 May 2020 01:03:12 +0600
From: noreply@example.com
To: ab1@email.com
Message-ID: <5eab20f0cdb12_674f2ae2f6b557e4537d7@abir-dell.mail>
Subject: Account activation
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5eab20f0ca95f_674f2ae2f6b557e453675";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_5eab20f0ca95f_674f2ae2f6b557e453675
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hi Filippos Vasilakis,

Welcome to the Sample App! Click on the link below to activate your account:

http://localhost:3000/account_activations/Wuov0LuiNyTnyc_6oaoozQ/edit?email=ab1%40email.com


----==_mimepart_5eab20f0ca95f_674f2ae2f6b557e453675
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <h1>Sample App</h1>

<p>Hi Filippos Vasilakis,</p>

<p>
Welcome to the Sample App! Click on the link below to activate your account:
</p>

<a href="http://localhost:3000/account_activations/Wuov0LuiNyTnyc_6oaoozQ/edit?email=ab1%40email.com">Activate</a>

  </body>
</html>

----==_mimepart_5eab20f0ca95f_674f2ae2f6b557e453675--

   (0.3ms)  BEGIN
  ↳ app/models/user.rb:82:in `activate'
  User Update (60.4ms)  UPDATE "users" SET "updated_at" = $1, "activated" = $2 WHERE "users"."id" = $3  [["updated_at", "2020-04-30 19:03:12.853748"], ["activated", true], ["id", 105]]
  ↳ app/models/user.rb:82:in `activate'
   (13.4ms)  COMMIT
  ↳ app/models/user.rb:82:in `activate'
   (0.3ms)  BEGIN
  ↳ app/models/user.rb:83:in `activate'
  User Update (36.0ms)  UPDATE "users" SET "updated_at" = $1, "activated_at" = $2 WHERE "users"."id" = $3  [["updated_at", "2020-04-30 19:03:12.949434"], ["activated_at", "2020-04-30 19:03:12.949115"], ["id", 105]]
  ↳ app/models/user.rb:83:in `activate'
   (24.4ms)  COMMIT
  ↳ app/models/user.rb:83:in `activate'
Completed 500 Internal Server Error in 2247ms (ActiveRecord: 344.1ms | Allocations: 170186)


  
NameError (undefined local variable or method `auth_user' for #<Api::V1::UsersController:0x000055c5eaf7c988>):
  
app/controllers/api/v1/users_controller.rb:34:in `create'
```

seems like it almost created but failed

**Comment by wasifhossain** [comment]
you should be able to debug the case. just start from the line which is being referred in the **last line** of the log above

**Comment by wasifhossain** [comment]
if you comment out this line
```rb
# auth_user = authorize_with_permissions(@user)
```
then it means `auth_user` is not defined. but still you are using it in `render`

**Comment by sadmanahmed** [comment]
Yes ... I saw that log ,then what should be the create action?

**Comment by wasifhossain** [comment]
first you need to get rid of `authorize_with_permissions` if you don't want to authorize the current action

second, pass the `@user` straight into `json` option and mention the fields explicitly in the `fields` option. (both of which were being done by authorize_with_permissions before)

**Comment by sadmanahmed** [comment]
is it something like this?
```
 def create
       # auth_user = authorize_with_permissions(@user)

        if @user.save && @user.send_activation_email && @user.activate
          render json: @user.record, serializer: UserSerializer,
                 fields: { user: @user.fields }, status: 201, scope: @user, adapter: :json_api
        else
          invalid_resource!(@user.errors)
        end
      end
```

**Comment by sadmanahmed** [comment]
full api is breaking down now........

the session is creating new user(i can found them in the user list on website but here it is saying internal server error)

log
```
Started POST "/api/v1/users" for ::1 at 2020-05-01 01:34:57 +0600
Processing by Api::V1::UsersController#create as */*
  Parameters: {"data"=>{"type"=>"users", "attributes"=>{"password"=>"[FILTERED]", "email"=>"ab3@email.com", "name"=>" shafin"}}, "user"=>{}}
   (0.4ms)  BEGIN
  ↳ app/models/user.rb:161:in `block in generate_hex'
  User Exists? (0.5ms)  SELECT 1 AS one FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "2fad59328fdd8d8fb978497c53ddb491"], ["LIMIT", 1]]
  ↳ app/models/user.rb:161:in `block in generate_hex'
  User Exists? (0.4ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "ab3@email.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:32:in `create'
  CACHE User Exists? (0.0ms)  SELECT 1 AS one FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "2fad59328fdd8d8fb978497c53ddb491"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:32:in `create'
  User Create (1.1ms)  INSERT INTO "users" ("name", "email", "created_at", "updated_at", "password_digest", "activation_digest", "token") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["name", " shafin"], ["email", "ab3@email.com"], ["created_at", "2020-04-30 19:34:57.774864"], ["updated_at", "2020-04-30 19:34:57.774864"], ["password_digest", "$2a$12$XvSpih3t/yCQcVQzXmMf5OJctVkuDXuP8VSoTOUar8q1UvQFf9nge"], ["activation_digest", "$2a$12$x8.v4k5IDUcMoaf4TJf5W.P2HpIf1vGMuFCQhNj6qG9v1HlYQhloS"], ["token", "2fad59328fdd8d8fb978497c53ddb491"]]
  ↳ app/controllers/api/v1/users_controller.rb:32:in `create'
   (10.0ms)  COMMIT
  ↳ app/controllers/api/v1/users_controller.rb:32:in `create'
  Rendering user_mailer/account_activation.html.erb within layouts/mailer
  Rendered user_mailer/account_activation.html.erb within layouts/mailer (Duration: 1.9ms | Allocations: 201)
  Rendering user_mailer/account_activation.text.erb within layouts/mailer
  Rendered user_mailer/account_activation.text.erb within layouts/mailer (Duration: 0.8ms | Allocations: 175)
UserMailer#account_activation: processed outbound mail in 9.6ms
Delivered mail 5eab2862317f8_15862af897fe6bbc61642@abir-dell.mail (7.5ms)
Date: Fri, 01 May 2020 01:34:58 +0600
From: noreply@example.com
To: ab3@email.com
Message-ID: <5eab2862317f8_15862af897fe6bbc61642@abir-dell.mail>
Subject: Account activation
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5eab286230074_15862af897fe6bbc615b4";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_5eab286230074_15862af897fe6bbc615b4
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hi  shafin,

Welcome to the Sample App! Click on the link below to activate your account:

http://localhost:3000/account_activations/wNAN32nJgQRBMhx4a3Z2og/edit?email=ab3%40email.com


----==_mimepart_5eab286230074_15862af897fe6bbc615b4
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <h1>Sample App</h1>

<p>Hi  shafin,</p>

<p>
Welcome to the Sample App! Click on the link below to activate your account:
</p>

<a href="http://localhost:3000/account_activations/wNAN32nJgQRBMhx4a3Z2og/edit?email=ab3%40email.com">Activate</a>

  </body>
</html>

----==_mimepart_5eab286230074_15862af897fe6bbc615b4--

   (0.7ms)  BEGIN
  ↳ app/models/user.rb:82:in `activate'
  User Update (1.0ms)  UPDATE "users" SET "updated_at" = $1, "activated" = $2 WHERE "users"."id" = $3  [["updated_at", "2020-04-30 19:34:58.207787"], ["activated", true], ["id", 107]]
  ↳ app/models/user.rb:82:in `activate'
   (10.9ms)  COMMIT
  ↳ app/models/user.rb:82:in `activate'
   (0.2ms)  BEGIN
  ↳ app/models/user.rb:83:in `activate'
  User Update (0.6ms)  UPDATE "users" SET "updated_at" = $1, "activated_at" = $2 WHERE "users"."id" = $3  [["updated_at", "2020-04-30 19:34:58.226410"], ["activated_at", "2020-04-30 19:34:58.225741"], ["id", 107]]
  ↳ app/models/user.rb:83:in `activate'
   (4.8ms)  COMMIT
  ↳ app/models/user.rb:83:in `activate'
Completed 500 Internal Server Error in 835ms (ActiveRecord: 30.7ms | Allocations: 40359)
```
It created shafin in the user list

**Comment by sadmanahmed** [comment]
and the new error is 
GET : http://localhost:3000/api/v1/users/1
(it bring back the first user data)

log
```
Started GET "/api/v1/users/1" for ::1 at 2020-05-01 01:42:47 +0600
Processing by Api::V1::UsersController#show as */*
  Parameters: {"id"=>"1"}
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/base_controller.rb:40:in `authenticate_user'
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:80:in `load_resource'
Completed 500 Internal Server Error in 227ms (ActiveRecord: 1.5ms | Allocations: 81638)


  
NoMethodError (undefined method `authorize_with_permissions' for #<Api::V1::UsersController:0x00007f85d6992ba0>):
  
app/controllers/api/v1/users_controller.rb:23:in `show'


```

**Comment by sadmanahmed** [comment]
we have to deal with this 
**NoMethodError (undefined method `authorize_with_permissions' for #<Api::V1::UsersController:0x00007f85d6992ba0>):**

**Comment by wasifhossain** [comment]
can you share `users_controller`

**Comment by sadmanahmed** [comment]
```
# frozen_string_literal: true

module Api
  module V1
    class UsersController < BaseController
      before_action :load_resource
      skip_before_action :authenticate_user!, only: :create

      # skip_before_action :authenticate_user!, only: [:index, :show, :create, :activate]
      # before_action :authenticate_user, only: [:index, :show]

      def index
        auth_users = policy_scope(@users)
        # binding.pry
        render json: auth_users.collection,
               each_serializer: UserSerializer,
               fields: { user: auth_users.fields(params[:fields]) },
               meta: meta_attributes(auth_users.collection),
               adapter: :json_api
      end

      def show
        auth_user = authorize_with_permissions(@user)

        render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
               fields: { user: auth_user.fields }
      end

      def create
        # auth_user = authorize_with_permissions(@user)

        if @user.save && @user.send_activation_email && @user.activate
          render json: @user.record, serializer: UserSerializer,
                 fields: { user: @user.fields }, status: 201, scope: @user, adapter: :json_api
        else
          invalid_resource!(@user.errors)
        end
      end

      def update
        auth_user = authorize_with_permissions(@user, :update?)

        if @user.update(update_params)
          render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
                 fields: { user: auth_user.fields }
        else
          invalid_resource!(@user.errors)
        end
      end

      def destroy
        auth_user = authorize_with_permissions(@user, :destroy?)

        @user.destroy!

        render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
               fields: { user: auth_user.fields }
      end

      def activate
        auth_user = authorize_with_permissions(@user, :activate?)

        if @user.authenticated?(:activation, params[:token])
          render json: auth_user.record, serializer: UserSerializer, adapter: :json_api,
                 fields: { user: auth_user.fields }, status: 200, scope: @user
        else
          not_found!
        end
      end

      private

      def load_resource
        case params[:action].to_sym
        when :index
          @users = paginate(apply_filters(User.all, params))
        when :create
          @user = User.new(create_params)
        when :show, :update, :destroy
          @user = User.find(params[:id])
        when :activate
          @user = User.find_by!(email: params[:email])
        end
      end

      def create_params
        normalized_params.permit(
          :email, :password, :password_confirmation, :name
        )
      end

      def update_params
        create_params
      end

      def normalized_params
        ActionController::Parameters.new(
          ActiveModelSerializers::Deserialization.jsonapi_parse(params)
        )
      end
    end
  end
end

```

**Comment by sadmanahmed** [comment]
method  authorize_with_permissions
```
# frozen_string_literal: true

module AuthorizeWithReturn
  def authorize_with_permissions(record, query = nil)
    query ||= params[:action].to_s + '?'
    @_pundit_policy_authorized = true

    policy = policy(record)
    policy.public_send(query)
  end

  def included
    super
    hide_action :authorize
  end
end

module Pundit
  prepend AuthorizeWithReturn
end

```

**Comment by wasifhossain** [comment]
lets resolve the `create` action first

```rb
render json: @user.record, # CHECK THE VALUE: @user.record
       serializer: UserSerializer,
       fields: { user: @user.fields }, # CHECK THE VALUE: @user.fields
       status: 201, 
       scope: @user, 
       adapter: :json_api
```
put a `binding.pry` before render and check the values as suggested above. they should fail btw

**Comment by sadmanahmed** [comment]
```
Started POST "/api/v1/users" for ::1 at 2020-05-01 01:53:06 +0600
Processing by Api::V1::UsersController#create as */*
  Parameters: {"data"=>{"type"=>"users", "attributes"=>{"password"=>"[FILTERED]", "email"=>"ab4@email.com", "name"=>" shafin1"}}, "user"=>{}}
   (0.2ms)  BEGIN
  ↳ app/models/user.rb:161:in `block in generate_hex'
  User Exists? (1.0ms)  SELECT 1 AS one FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "678993ad6bb742241e004886eb64872b"], ["LIMIT", 1]]
  ↳ app/models/user.rb:161:in `block in generate_hex'
  User Exists? (0.5ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "ab4@email.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:32:in `create'
  CACHE User Exists? (0.0ms)  SELECT 1 AS one FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "678993ad6bb742241e004886eb64872b"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:32:in `create'
  User Create (0.7ms)  INSERT INTO "users" ("name", "email", "created_at", "updated_at", "password_digest", "activation_digest", "token") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["name", " shafin1"], ["email", "ab4@email.com"], ["created_at", "2020-04-30 19:53:07.486736"], ["updated_at", "2020-04-30 19:53:07.486736"], ["password_digest", "$2a$12$g.eihQCm5kEAws6xQRyjt.YWkY2Z89DSQMBwV2eEjjEVv21XnisSO"], ["activation_digest", "$2a$12$lQ8YQC4DzqWxqqCM/PUFpuhuu5eT1fcYAoBOOzqX2LE9semgg1p2G"], ["token", "678993ad6bb742241e004886eb64872b"]]
  ↳ app/controllers/api/v1/users_controller.rb:32:in `create'
   (8.6ms)  COMMIT
  ↳ app/controllers/api/v1/users_controller.rb:32:in `create'
  Rendering user_mailer/account_activation.html.erb within layouts/mailer
  Rendered user_mailer/account_activation.html.erb within layouts/mailer (Duration: 0.5ms | Allocations: 79)
  Rendering user_mailer/account_activation.text.erb within layouts/mailer
  Rendered user_mailer/account_activation.text.erb within layouts/mailer (Duration: 0.3ms | Allocations: 59)
UserMailer#account_activation: processed outbound mail in 7.7ms
Delivered mail 5eab2ca3d6659_15862af897fe6a90618e@abir-dell.mail (3.3ms)
Date: Fri, 01 May 2020 01:53:07 +0600
From: noreply@example.com
To: ab4@email.com
Message-ID: <5eab2ca3d6659_15862af897fe6a90618e@abir-dell.mail>
Subject: Account activation
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5eab2ca3d583f_15862af897fe6a9061734";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_5eab2ca3d583f_15862af897fe6a9061734
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hi  shafin1,

Welcome to the Sample App! Click on the link below to activate your account:

http://localhost:3000/account_activations/vPeYz5N2g2aLrLh1vGKf0w/edit?email=ab4%40email.com


----==_mimepart_5eab2ca3d583f_15862af897fe6a9061734
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <h1>Sample App</h1>

<p>Hi  shafin1,</p>

<p>
Welcome to the Sample App! Click on the link below to activate your account:
</p>

<a href="http://localhost:3000/account_activations/vPeYz5N2g2aLrLh1vGKf0w/edit?email=ab4%40email.com">Activate</a>

  </body>
</html>

----==_mimepart_5eab2ca3d583f_15862af897fe6a9061734--

   (0.3ms)  BEGIN
  ↳ app/models/user.rb:82:in `activate'
  User Update (0.9ms)  UPDATE "users" SET "updated_at" = $1, "activated" = $2 WHERE "users"."id" = $3  [["updated_at", "2020-04-30 19:53:07.881251"], ["activated", true], ["id", 108]]
  ↳ app/models/user.rb:82:in `activate'
   (12.9ms)  COMMIT
  ↳ app/models/user.rb:82:in `activate'
   (0.3ms)  BEGIN
  ↳ app/models/user.rb:83:in `activate'
  User Update (0.8ms)  UPDATE "users" SET "updated_at" = $1, "activated_at" = $2 WHERE "users"."id" = $3  [["updated_at", "2020-04-30 19:53:07.902218"], ["activated_at", "2020-04-30 19:53:07.901750"], ["id", 108]]
  ↳ app/models/user.rb:83:in `activate'
   (4.3ms)  COMMIT
  ↳ app/models/user.rb:83:in `activate'

From: /home/abir/environment/sample_app/app/controllers/api/v1/users_controller.rb @ line 34 Api::V1::UsersController#create:

    29: def create
    30:   # auth_user = authorize_with_permissions(@user)
    31: 
    32:   if @user.save && @user.send_activation_email && @user.activate
    33:     binding.pry
 => 34:     render json: @user.record,
    35:     serializer: UserSerializer,
    36:     fields: { user: @user.fields },
    37:     status: 201, scope: @user,
    38:     adapter: :json_api
    39:   else
    40:     invalid_resource!(@user.errors)
    41:   end
    42: end

[1] pry(#<Api::V1::UsersController>)> 
[2] pry(#<Api::V1::UsersController>)> 
[3] pry(#<Api::V1::UsersController>)> 
[4] pry(#<Api::V1::UsersController>)> 
[5] pry(#<Api::V1::UsersController>)> 
[6] pry(#<Api::V1::UsersController>)> 
[7] pry(#<Api::V1::UsersController>)> 
[8] pry(#<Api::V1::UsersController>)> 
[9] pry(#<Api::V1::UsersController>)> 
[10] pry(#<Api::V1::UsersController>)> 
[11] pry(#<Api::V1::UsersController>)> 
[12] pry(#<Api::V1::UsersController>)> 
[13] pry(#<Api::V1::UsersController>)> 
[14] pry(#<Api::V1::UsersController>)> 
[15] pry(#<Api::V1::UsersController>)> 
[16] pry(#<Api::V1::UsersController>)> 
[17] pry(#<Api::V1::UsersController>)> 
[18] pry(#<Api::V1::UsersController>)> ~
[18] pry(#<Api::V1::UsersController>)* 
[18] pry(#<Api::V1::UsersController>)* 
[18] pry(#<Api::V1::UsersController>)* 

```

**Comment by sadmanahmed** [comment]
```
 pry(#<Api::V1::UsersController>)* @user.record
NoMethodError: undefined method `record' for #<User:0x00007f85d61d4828>
from /home/abir/.rvm/gems/ruby-2.6.5/gems/activemodel-6.0.0/lib/active_model/attribute_methods.rb:431:in `method_missing'
[19] pry(#<Api::V1::UsersController>)> @user.fields
NoMethodError: undefined method `fields' for #<User:0x00007f85d61d4828>
from /home/abir/.rvm/gems/ruby-2.6.5/gems/activemodel-6.0.0/lib/active_model/attribute_methods.rb:431:in `method_missing'
[20] pry(#<Api::V1::UsersController>)> 

```

**Comment by wasifhossain** [comment]
so you can see which code is breaking the app. 

`record` and `fields` methods were available for the instance that you would get from calling the authorize method. but not anymore, as you have disabled that

**Comment by wasifhossain** [comment]
ANOTHER IMPORTANT FACT:

though there is no syntax error here, but I do believe you are missing an important thing in the following logic
```rb
if @user.save && @user.send_activation_email && @user.activate
```
in an ideal scenario, account activation should work like this: the user should get an email which would include the activation link. clicking on that link would only allow the server to activate the **user owning the email**.

now think what would happen if a malicious user makes the api call using YOUR email to create the user. 

the above logic, though would send the email to the address, but would also activate it by calling `@user.activate`, which would make the activation process through email completely useless, allowing random users to occupy the accounts using someone else's emails

**Comment by sadmanahmed** [comment]
Yes I saw that flaw as no email activation is need to create user by the api calling...

**Comment by sadmanahmed** [comment]
So I should made it like this?
` if @user.save && @user.send_activation_email `

**Comment by sadmanahmed** [comment]
> so you can see which code is breaking the app.
> 
> `record` and `fields` methods were available for the instance that you would get from calling the authorize method. but not anymore, as you have disabled that

But I didnot do anything to disable them

**Comment by wasifhossain** [comment]
you have indeed disabled them this way
```rb
# auth_user = authorize_with_permissions(@user)
```
check in the console: `auth_user` and `@user` are instances of different classes
```rb
auth_user.class
@user.class
```

`auth_user` seems to provide instance methods like `record` and `fields`, but `@user` does not do that

**Comment by sadmanahmed** [comment]
then what can be the possible new create action ?

**Comment by wasifhossain** [comment]
as you are using AMS to serialize the response, knowing how AMS controls different options in the `render` method should help:

https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/rendering.md

**Comment by sadmanahmed** [comment]
Okay there is a new MOVEMENT happened

**Comment by sadmanahmed** [comment]
I just made this modified
```
skip_before_action :authenticate_user!, only: [
        :create, :activate]
```

**Comment by sadmanahmed** [comment]
new user is creating now without any authorization token...

**Comment by sadmanahmed** [comment]
but still the activation is not necessary here in the api call.... How to fix the email activation?

**Comment by wasifhossain** [comment]
> new user is creating now without any authorization token...

how did it work before this change

**Comment by sadmanahmed** [comment]
but good thing is the email activation (link from the server log) is working now.. Maybe the user list is showing the user but we need to active it before signup....

**Comment by sadmanahmed** [comment]
> > new user is creating now without any authorization token...
> 
> how did it work before this change

Our problem was I mistakenly put the authorization of admin in the header and without authorization I can't even sign up a new user.... thus we changed the code and `skip_before_action :authenticate_user!, only: [
        :create, :activate]` this portion was written again(it was commented out)

**Comment by wasifhossain** [comment]
> new user is creating now without any authorization token...

do you mean this has become a problem?

**Comment by sadmanahmed** [comment]
no , now it solved ...

**Comment by wasifhossain** [comment]
> but still the activation is not necessary here in the api call.... How to fix the email activation?

can you elaborate more on this

**Comment by sadmanahmed** [comment]
> > but still the activation is not necessary here in the api call.... How to fix the email activation?
> 
> can you elaborate more on this

Now it fixed also as u told to do this `if @user.save && @user.send_activation_email #&& @user.activate` , I just comment out that now the activation email is also working

**Comment by wasifhossain** [comment]
oh i see :smile:
