### ISSUE TITLE
 authorize_with_permission method

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#71]
I want to know if it can be possible to replace this authorize_with_permission method
```
module AuthorizeWithReturn
  def authorize_with_permissions(record, query = nil)
    query ||= params[:action].to_s + '?'
    @_pundit_policy_authorized = true

    policy = policy(record)
    policy.public_send(query)
  end

  def included
    super
    hide_action :authorize
  end
end

module Pundit
  prepend AuthorizeWithReturn
end
```

**Comment by sadmanahmed** [comment]
as when I am trying to see **users/1**
the server error log
```
app/controllers/api/v1/users_controller.rb:19:in `show'
Started GET "/api/v1/users/1" for ::1 at 2020-05-01 02:55:42 +0600
Processing by Api::V1::UsersController#show as */*
  Parameters: {"id"=>"1"}
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:75:in `load_resource'
  User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "abirssc7@gmail.com"], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/base_controller.rb:40:in `authenticate_user'
Completed 500 Internal Server Error in 403ms (ActiveRecord: 1.6ms | Allocations: 67561)


  
NoMethodError (undefined method `authorize_with_permissions' for #<Api::V1::UsersController:0x00007f85d52542b8>):
  
app/controllers/api/v1/users_controller.rb:19:in `show'

```

**Comment by sadmanahmed** [comment]
The error fixed for now . But if we want to see our api's without any authorization what can be the possible input for auth_user as in many action auth_user = authorize_with_permissions(@user) ?

**Comment by wasifhossain** [comment]
just do the same as you did for the `create` action: disable the line and replace `auth_user` with `@user`
