### ISSUE TITLE
How to set environment variable

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#98]
#PG #PG_Name #PG_Password
How can I do it? Following the issue here #96 
```
Note: the above template contains some environment variables that you need to set. only PG_USERNAME and PG_PASSWORD are required
```

**Comment by wasifhossain** [comment]
check this out! https://github.com/bkeepers/dotenv

**Comment by sadmanahmed** [comment]
This repo is too confusing .. I installed the gem but in the `usage` I am lost where to go

**Comment by sadmanahmed** [comment]
```
Usage
Add your application configuration to your .env file in the root of your project:

S3_BUCKET=YOURS3BUCKET
SECRET_KEY=YOURSECRETKEYGOESHERE
Whenever your application loads, these variables will be available in ENV:

config.fog_directory  = ENV['S3_BUCKET']
You may also add export in front of each line so you can source the file in bash:

export S3_BUCKET=YOURS3BUCKET
export SECRET_KEY=YOURSECRETKEYGOESHERE
Multi-line values
```

**Comment by wasifhossain** [comment]
can you highlight what did you find **confusing** here

**Comment by sadmanahmed** [comment]
How it relates with postgresql and where to write the codes
![ss](https://user-images.githubusercontent.com/19534210/88237843-f7f43880-cca1-11ea-9d2f-d4e45d7b2540.png)

**Comment by wasifhossain** [comment]
indeed it does NOT relate to postgresql, rather a generic strategy to set environment variables which your app needs to be present inside its runtime environment (development/test/production etc)

dotenv helps you set env vars in a user-friendly way

**Comment by sadmanahmed** [comment]
So where will I write them ?

**Comment by wasifhossain** [comment]
revisit the USAGE section of the gem documentation. you should be able to get the idea

**Comment by wasifhossain** [comment]
sample `.env` file containing PG_USERNAME and PG_PASSWORD
```
# .env
PG_USERNAME=<your postgresql user>
PG_PASSWORD=<password for the above pg user>
```

DON'T FORGET TO IGNORE `.env` file from indexing into git. 

to ensure the case, add the filename (.env in this case) in `.gitignore`
```
# .gitignore

/.env
```

**Comment by sadmanahmed** [comment]
vaia will this work?
```
sudo -u postgres psql
postgres=# create database MyDatabase;
postgres=# alter user postgres with encrypted password 'MyPassword';
\q
```

**Comment by sadmanahmed** [comment]
I have read this but still rounding and rounding on it .
.env
```
PG_USERNAME=abir
PG_PASSWORD=abir1234

```

```
cabinet git:(master) ✗ rails db:create                                          
fe_sendauth: no password supplied
Couldn't create 'cabinet_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:189:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:126:in `create'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/home/abir/PRACTICE/cabinet/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/PRACTICE/cabinet/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)

```

**Comment by wasifhossain** [comment]
did you set the environment for the db?
```
rails db:environment:set
```

**Comment by sadmanahmed** [comment]
```
tumblr git:(master) ✗ rails db:environment:set
rails aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/home/abir/.rvm/gems/ruby-2.6.5/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:189:in `connection'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/internal_metadata.rb:32:in `table_exists?'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/internal_metadata.rb:37:in `create_table'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:10:in `block (2 levels) in <main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/home/abir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/abir/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/abir/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/home/abir/PRACTICE/tumblr/bin/rails:9:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/abir/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/abir/PRACTICE/tumblr/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:environment:set
(See full trace by running task with --trace)

```

**Comment by wasifhossain** [comment]
or I think you need to stop **spring** in order for the rake task to reload the environment
```
bundle exec spring stop
```

**Comment by sadmanahmed** [comment]
```
tumblr git:(master) ✗ bundle exec spring stop
Spring is not running

```

**Comment by wasifhossain** [comment]
run the following command in the console
```
echo $PG_USERNAME
```

if you can see the output that matches with the value you set in the .env file, then you should be able to run the rails commands

**Comment by sadmanahmed** [comment]
```
tumblr git:(master) ✗ echo $PG_USERNAME

➜  tumblr git:(master) ✗ 

```

**Comment by sadmanahmed** [comment]
should not we create .env manually ? and then put the code snippet like this?
```
PG_USERNAME= abir
PG_PASSWORD= abir1234

```

**Comment by wasifhossain** [comment]
not loaded yet! then something must be missing from dotenv

**Comment by wasifhossain** [comment]
you have the `.env` under root, right?

**Comment by wasifhossain** [comment]
can you list down all the steps that you followed so far to configure the environment variables

**Comment by sadmanahmed** [comment]
I guess in the root
![ss](https://user-images.githubusercontent.com/19534210/88342407-2e44bd00-cd61-11ea-9fe2-0eebcfe08260.png)

**Comment by wasifhossain** [comment]
> I guess in the root
> ![ss](https://user-images.githubusercontent.com/19534210/88342407-2e44bd00-cd61-11ea-9fe2-0eebcfe08260.png)

always handy to use `ls -al <filename>` to check a file's presence than using file manager :smile: 
```
ls -al .env
```

**Comment by sadmanahmed** [comment]
1. Replace the gem (pg in place of sqlite)
2. updated the database.yml
3. Dotenv gem installed
4. Go through the link but lost then you told me to setup .env

**Comment by wasifhossain** [comment]
can you elaborate step 4 above

**Comment by sadmanahmed** [comment]
We are missing something ,as last time we setup postgres very easily... and the database.yml is not same like you shared the new one yesterday.

**Comment by wasifhossain** [comment]
does not matter if database.yml is same or different. your current issue is all about failing to read an env var

**Comment by wasifhossain** [comment]
can you elaborate step 3 above
> 3. Dotenev gem installed

**Comment by sadmanahmed** [comment]
> can you elaborate step 4 above

1. set Gem 'pg' and delete sqlite3
2. you gave me a database.yml, I replaced that with the then database.yml
3. dotenv gem installed and added this as instructed 
```
# config/application.rb
Bundler.require(*Rails.groups)

Dotenv::Railtie.load

HOSTNAME = ENV['HOSTNAME']
```

4. .env setuped

**Comment by wasifhossain** [comment]
```
# config/application.rb
Bundler.require(*Rails.groups)

Dotenv::Railtie.load

HOSTNAME = ENV['HOSTNAME']
```
NOT required. can you revert these

**Comment by sadmanahmed** [comment]
okay ,without it I just installed the gem in step 3 

> ```
> # config/application.rb
> Bundler.require(*Rails.groups)
> 
> Dotenv::Railtie.load
> 
> HOSTNAME = ENV['HOSTNAME']
> ```
> 
> NOT required. can you revert these

**Comment by wasifhossain** [comment]
all you need in order for dotenv to work in a rails app is to add it in Gemfile for both `development` and `test` group:
```
group :development, :test do
    gem 'dotenv-rails'
end
```

and run: `bundle install`

**Comment by sadmanahmed** [comment]
> all you need in order for dotenv to work in a rails app is to add it in Gemfile for both `development` and `test` group:
> 
> ```
> group :development, :test do
>     gem 'dotenv-rails'
> end
> ```
> 
> and run: `bundle install`

Then?

**Comment by wasifhossain** [comment]
my last post covers the OP (How to set environment variable),  I believe

after that, you are good to run the commands that you were trying earlier that lead you to this issue

**Comment by sadmanahmed** [comment]
Nothing happened
```
  tumblr git:(master) ✗ echo $PG_USERNAME

➜  tumblr git:(master) ✗ 

```

**Comment by wasifhossain** [comment]
inside `rails console`, check the output
```rb
ENV['PG_USERNAME'] 
```

**Comment by sadmanahmed** [comment]
```
 tumblr git:(master) ✗ rails db:create                                    
Created database 'tumblr_development'
Created database 'tumblr_test'
➜  tumblr git:(master) ✗ rails db:environment:set
➜  tumblr git:(master) ✗ echo $PG_USERNAME       

➜  tumblr git:(master) ✗ 

```

**Comment by wasifhossain** [comment]
there you go!

**Comment by sadmanahmed** [comment]
```
tumblr git:(master) ✗ rails c
Running via Spring preloader in process 23965
Loading development environment (Rails 6.0.3.2)
2.6.5 :001 > ENV['PG_USERNAME'] 
 => "abir" 
2.6.5 :002 > 

```

**Comment by sadmanahmed** [comment]
#PG #PG_Name #PG_Password

**Comment by wasifhossain** [comment]
this is a generic issue. lets keep it that way by not attaching to a pg-specific env var only

**Comment by wasifhossain** [comment]
**PLEASE KEEP IN MIND**

ENVIRONMENT VARIABLE is a very important topic for app management on server-side. You will encounter this topic time and again the more you get yourself deeper into server management

**Comment by sadmanahmed** [comment]
But both #96 and #98 helped to setup the postgre for the project

**Comment by wasifhossain** [comment]
#96 depends on this, but not the other way around. so you may put a common label to both of these issues, e.g. #environment-variable

what do you think

**Comment by sadmanahmed** [comment]
Actually confused, for me both of them are same important to setup the postgres

**Comment by wasifhossain** [comment]
but going forward, you might come back to this issue time and again due to an issue completely unrelated to **postgre**

**Comment by sadmanahmed** [comment]
#postgresql_environemnt_setup

**Comment by wasifhossain** [comment]
might apply to #96, but not this.

okay i am going to apply #environment-variable on this
